### ISSUE TITLE
Sharing chat from Whatsapp with lots of media crashes K-9

### ISSUE THREAD

**Issue by Nutomic** [thunderbird/thunderbird-android#1040]
I tried to share a big chat from Whatsapp (Open chat -> More -> Email chat), which caused K-9 to crash. Crash log:

```
D/AndroidRuntime(21342): Shutting down VM
E/AndroidRuntime(21342): FATAL EXCEPTION: main
E/AndroidRuntime(21342): Process: com.fsck.k9, PID: 21342
E/AndroidRuntime(21342): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9/com.fsck.k9.activity.MessageCompose}: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@adb174b rejected from java.util.concurrent.ThreadPoolExecutor@2f63f528[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 0]
E/AndroidRuntime(21342):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime(21342):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime(21342):        at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime(21342):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime(21342):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21342):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(21342):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(21342):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21342):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(21342):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(21342):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(21342): Caused by: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@adb174b rejected from java.util.concurrent.ThreadPoolExecutor@2f63f528[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 0]
E/AndroidRuntime(21342):        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
E/AndroidRuntime(21342):        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
E/AndroidRuntime(21342):        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
E/AndroidRuntime(21342):        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:594)
E/AndroidRuntime(21342):        at android.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:235)
E/AndroidRuntime(21342):        at android.content.AsyncTaskLoader.onForceLoad(AsyncTaskLoader.java:166)
E/AndroidRuntime(21342):        at android.content.Loader.forceLoad(Loader.java:347)
E/AndroidRuntime(21342):        at com.fsck.k9.activity.loader.AttachmentInfoLoader.onStartLoading(AttachmentInfoLoader.java:35)
E/AndroidRuntime(21342):        at android.content.Loader.startLoading(Loader.java:290)
E/AndroidRuntime(21342):        at android.app.LoaderManagerImpl$LoaderInfo.start(LoaderManager.java:280)
E/AndroidRuntime(21342):        at android.app.LoaderManagerImpl.doStart(LoaderManager.java:772)
E/AndroidRuntime(21342):        at android.app.Activity.onStart(Activity.java:1164)
E/AndroidRuntime(21342):        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
E/AndroidRuntime(21342):        at android.app.Activity.performStart(Activity.java:6006)
E/AndroidRuntime(21342):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
E/AndroidRuntime(21342):        ... 10 more
```

**Comment by cketti** [comment]
We should probably serialize loading the attachments data.

**Comment by philipwhiuk** [comment]
Has this been done - I couldn't reproduce the issue on master.

**Comment by cketti** [comment]
No, this hasn't been fixed.

But I guess it's not that easy to reproduce.The thread pool queue size seems to be 128. The thread pool size 9. So you need at least 128+9+1 attachments and loading the first can't complete before attempting to enqueue the last item.

**Comment by philipwhiuk** [comment]
Hmm. And WhatsApp seems to have a finite limit on the number of items it will try and attach - I added a more media to a conversation to test this and it then only attached the actual conversation.

**Comment by Nutomic** [comment]
I just tried again, and I can't reproduce the crash any more. However, I think not all images are added to the new email.

**Comment by GNUDimarik** [comment]
Hey guys!
I able to reproduce it always during the export of a huge chat with a lot of audio messages with this log:

2020-09-07 17:11:50.583 30112-30112/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fsck.k9.debug, PID: 30112
    java.lang.AssertionError: more than 63 attachments? hum.
        at com.fsck.k9.activity.compose.AttachmentPresenter.getNextFreeLoaderId(AttachmentPresenter.java:245)
        at com.fsck.k9.activity.compose.AttachmentPresenter.addAttachment(AttachmentPresenter.java:167)
        at com.fsck.k9.activity.compose.AttachmentPresenter.addAttachment(AttachmentPresenter.java:159)
        at com.fsck.k9.activity.MessageCompose.initFromIntent(MessageCompose.java:560)
        at com.fsck.k9.activity.MessageCompose.onCreate(MessageCompose.java:380)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
2020-09-07 17:11:50.653 30112-30112/com.fsck.k9.debug I/Process: Sending signal. PID: 30112 SIG: 9

I've 100% working scenario for crash the app. But sees it's another issue related with loaders limit
@cketti please let me know if it needs to be fixed
