### ISSUE TITLE
"Next Poll" time is in the past

### ISSUE THREAD

**Issue by GWRon** [thunderbird/thunderbird-android#1141]
### Expected behaviour

I would expect to ignore negative amounts of "next poll"-time and either repair or set to a reasonable time (default time).
### Actual behaviour

It displays a negative value and does not try to poll in its intervals then.

![screenshot_2016-03-04-14-34-52](https://cloud.githubusercontent.com/assets/2625226/13528873/2b3f0fc6-e219-11e5-9288-64eb2c2e6cc6.png)
### Steps to reproduce
1. Install K-9
2. Setup accounts
3. let it run
### Environment

K-9 Mail version: 5.008

Android version: 6.0 (Marshmallow)

Account type (IMAP, POP3, WebDAV/Exchange): imap
### Thoughts on this

I assume it has to do with "doze" (which I thought to have disabled, but somehow is still active ... thanks to Huawei's EMUI and their PhoneManager). With Android 6.0's  "doze"-function applications get hibernated.
So when K-9 is waking up, it might have a outdated timer (lastPollRealTime + pollIntervall = "next PollRealTime") or something similar (I know that this sounds really artificial, but grown code tends to have odd things in it). With such an outdated timer time displays will have good chances to show past times.
#### logcat for manual "check mails"

```
03-04 14:59:35.862 11295 11317 I k9      : Running Background command 'checkMail', seq = 289
03-04 14:59:35.862 11295 11317 I k9      : Starting mail check
03-04 14:59:35.862 11295 11317 I k9      : Synchronizing account ron@gw
03-04 14:59:35.866 11295 11317 I k9      : Synchronizing account ron@TUC
03-04 14:59:35.867 11295 11317 I k9      : Synchronizing account ron@GMail
03-04 14:59:35.869 11295 11317 I k9      : Background Command 'checkMail' completed
03-04 14:59:35.869 11295 11317 I k9      : Running Background command 'sendPendingMessages', seq = 290
03-04 14:59:35.873 11295 11317 I k9      : Background Command 'sendPendingMessages' completed
03-04 14:59:35.873 11295 11317 I k9      : Running Background command 'syncDrafts', seq = 291
03-04 14:59:35.879 11295 11317 I k9      : Synchronizing folder ron@gw:Drafts
03-04 14:59:36.408 11295 11317 I SendBroadcastPermission: action:com.fsck.k9.intent.action.REFRESH_OBSERVER, mPermissionType:0
03-04 14:59:36.441 11295 11317 I k9      : Done synchronizing folder ron@gw:Drafts
03-04 14:59:36.444 11295 11317 I k9      : Background Command 'syncDrafts' completed
03-04 14:59:36.444 11295 11317 I k9      : Running Background command 'syncPosteingangClean', seq = 292
03-04 14:59:36.454 11295 11317 I k9      : Synchronizing folder ron@gw:PosteingangClean
03-04 14:59:36.734 11295 11317 I SendBroadcastPermission: action:com.fsck.k9.intent.action.REFRESH_OBSERVER, mPermissionType:0
03-04 14:59:36.765 11295 11317 I k9      : Done synchronizing folder ron@gw:PosteingangClean
03-04 14:59:36.765 11295 11317 I k9      : Background Command 'syncPosteingangClean' completed
03-04 14:59:36.766 11295 11317 I k9      : Running Background command 'clear notification flag for ron@gw', seq = 293
03-04 14:59:36.786 11295 11317 I k9      : Background Command 'clear notification flag for ron@gw' completed
03-04 14:59:36.786 11295 11317 I k9      : Running Background command 'sendPendingMessages', seq = 294
03-04 14:59:36.789 11295 11317 I k9      : Background Command 'sendPendingMessages' completed
03-04 14:59:36.790 11295 11317 I k9      : Running Background command 'syncEntwürfe', seq = 295
03-04 14:59:36.795 11295 11317 I k9      : Synchronizing folder ron@TUC:Entwürfe
03-04 14:59:37.384 11295 11317 I k9      : Compression enabled for conn70978259
03-04 14:59:37.481 11295 11317 I SendBroadcastPermission: action:com.fsck.k9.intent.action.REFRESH_OBSERVER, mPermissionType:0
03-04 14:59:37.497  3136  3166 I ActivityManager: Displayed com.fsck.k9/.activity.Accounts: +308ms
03-04 14:59:37.502 11295 11302 E StrictMode:    at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2573)
03-04 14:59:37.502 11295 11302 E StrictMode:    at com.fsck.k9.mail.store.ImapStore$ImapFolder.getPrefixedName(ImapStore.java:842)
03-04 14:59:37.502 11295 11302 E StrictMode:    at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:901)
03-04 14:59:37.502 11295 11302 E StrictMode:    at com.fsck.k9.mail.store.ImapStore$ImapFolder.open(ImapStore.java:867)
03-04 14:59:37.502 11295 11302 E StrictMode:    at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1041)
03-04 14:59:37.502 11295 11302 E StrictMode:    at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
03-04 14:59:37.502 11295 11302 E StrictMode:    at com.fsck.k9.controller.MessagingController$35.run(MessagingController.java:4506)
03-04 14:59:37.502 11295 11302 E StrictMode:    at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
03-04 14:59:37.538 11295 11317 I k9      : Done synchronizing folder ron@TUC:Entwürfe
03-04 14:59:37.540 11295 11317 I k9      : Background Command 'syncEntwürfe' completed
03-04 14:59:37.540 11295 11317 I k9      : Running Background command 'syncINBOX', seq = 296
03-04 14:59:37.556 11295 11317 I k9      : Synchronizing folder ron@TUC:INBOX
03-04 14:59:37.884 11295 11317 I SendBroadcastPermission: action:com.fsck.k9.intent.action.REFRESH_OBSERVER, mPermissionType:0
03-04 14:59:37.927 11295 11317 I k9      : Done synchronizing folder ron@TUC:INBOX
03-04 14:59:37.927 11295 11317 I k9      : Background Command 'syncINBOX' completed
03-04 14:59:37.927 11295 11317 I k9      : Running Background command 'clear notification flag for ron@TUC', seq = 297
03-04 14:59:37.950 11295 11317 I k9      : Background Command 'clear notification flag for ron@TUC' completed
03-04 14:59:37.950 11295 11317 I k9      : Running Background command 'sendPendingMessages', seq = 298
03-04 14:59:37.955 11295 11317 I k9      : Background Command 'sendPendingMessages' completed
03-04 14:59:37.955 11295 11317 I k9      : Running Background command 'syncINBOX', seq = 299
03-04 14:59:37.965 11295 11317 I k9      : Synchronizing folder ron@GMail:INBOX
03-04 14:59:38.271 11295 11317 I k9      : Did not get capabilities in banner, requesting CAPABILITY for conn87053025
03-04 14:59:39.138 11295 11317 I k9      : Compression enabled for conn87053025
03-04 14:59:39.565 11295 11317 I SendBroadcastPermission: action:com.fsck.k9.intent.action.REFRESH_OBSERVER, mPermissionType:0
03-04 14:59:39.610 11295 11317 I k9      : Done synchronizing folder ron@GMail:INBOX
03-04 14:59:39.611 11295 11317 I k9      : Background Command 'syncINBOX' completed
03-04 14:59:39.611 11295 11317 I k9      : Running Background command 'sync[Gmail]/Entwürfe', seq = 300
03-04 14:59:39.635 11295 11317 I k9      : Synchronizing folder ron@GMail:[Gmail]/Entwürfe
03-04 14:59:39.946 11295 11317 I SendBroadcastPermission: action:com.fsck.k9.intent.action.REFRESH_OBSERVER, mPermissionType:0
03-04 14:59:40.002 11295 11317 I k9      : Done synchronizing folder ron@GMail:[Gmail]/Entwürfe
03-04 14:59:40.007 11295 11317 I k9      : Background Command 'sync[Gmail]/Entwürfe' completed
03-04 14:59:40.007 11295 11317 I k9      : Running Background command 'clear notification flag for ron@GMail', seq = 301
03-04 14:59:40.041 11295 11317 I k9      : Background Command 'clear notification flag for ron@GMail' completed
03-04 14:59:40.041 11295 11317 I k9      : Running Background command 'finalize sync', seq = 302
03-04 14:59:40.041 11295 11317 I k9      : Finished mail sync
03-04 14:59:40.043 11295 11317 I k9      : Background Command 'finalize sync' completed
```

---

And this is a portion, once I disconnected from wifi:

```
03-04 15:04:03.247 11295 11295 I k9      : CoreReceiver.onReceiveIntent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 cmp=com.fsck.k9/.service.BootReceiver (has extras) }
03-04 15:04:03.247 11295 11295 I k9      : BootReceiver.onReceiveIntent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 cmp=com.fsck.k9/.service.BootReceiver (has extras) }
03-04 15:04:03.253 11295 11295 I k9      : CoreService: com.fsck.k9.service.MailService.onCreate()
03-04 15:04:03.258 11295 11295 I k9      : CoreService: com.fsck.k9.service.MailService.onStart(Intent { act=com.fsck.k9.intent.action.MAIL_SERVICE_CONNECTIVITY_CHANGE cmp=com.fsck.k9/.service.MailService (has extras) }, 1)
03-04 15:04:03.258 11295 11295 I SendBroadcastPermission: action:com.fsck.k9.service.CoreReceiver.wakeLockRelease, mPermissionType:0
03-04 15:04:03.261 11295 11295 I k9      : MailService.onStart(Intent { act=com.fsck.k9.intent.action.MAIL_SERVICE_CONNECTIVITY_CHANGE cmp=com.fsck.k9/.service.MailService (has extras) }, 1), hasConnectivity = true, doBackground = true
03-04 15:04:03.264 11295 11295 I k9      : Got connectivity action with hasConnectivity = true, doBackground = true
03-04 15:04:03.264 11295 11295 I k9      : MailService.onStart took 5ms
03-04 15:04:03.273 11295 20314 I k9      : Committing preference changes
03-04 15:04:03.284 11295 20314 I k9      : Preferences commit took 11ms
03-04 15:04:03.284 11295 20314 I k9      : previousInterval = 120, shortestInterval = 120, lastCheckEnd = Fri Mar 04 11:57:13 GMT+01:00 2016, considerLastCheckEnd = true
03-04 15:04:03.284 11295 20314 I k9      : Next check for package com.fsck.k9 scheduled for Fri Mar 04 13:57:13 GMT+01:00 2016
```

In the last lines you see that it schedules for something in the past.

---

Shortly after this, k-9 is able to calculates 2hrs plus the current time:

```
03-04 15:04:05.227 11295 11295 I k9      : MailService.onStart(Intent { act=com.fsck.k9.intent.action.MAIL_SERVICE_WAKEUP cmp=com.fsck.k9/.service.MailService (has extras) }, 1), hasConnectivity = true, doBackground = true
03-04 15:04:05.227 11295 11295 I k9      : ***** MailService *****: checking mail
03-04 15:04:05.236 11295 11295 I k9      : MailService.onStart took 10ms
03-04 15:04:05.237 11295 20403 I k9      : Committing preference changes
03-04 15:04:05.240 11295 11295 I k9      : CoreService: com.fsck.k9.service.PollService.onCreate()
03-04 15:04:05.243 11295 11295 I k9      : CoreService: com.fsck.k9.service.PollService.onStart(Intent { act=com.fsck.k9.service.PollService.startService cmp=com.fsck.k9/.service.PollService (has extras) }, 1)
03-04 15:04:05.245 11295 11295 I k9      : PollService started with startId = 1
03-04 15:04:05.245 11295 11295 I k9      : ***** PollService *****: starting new check
03-04 15:04:05.245 11295 20403 I k9      : Preferences commit took 8ms
03-04 15:04:05.245 11295 20403 I k9      : previousInterval = 120, shortestInterval = 120, lastCheckEnd = Fri Mar 04 11:57:13 GMT+01:00 2016, considerLastCheckEnd = false
03-04 15:04:05.245 11295 20403 I k9      : Next check for package com.fsck.k9 scheduled for Fri Mar 04 17:04:05 GMT+01:00 2016
```

Dunno if this is expected to be this way.

**Comment by Melog01** [comment]
I have same problem on my Huawei P8

**Comment by cketti** [comment]
With the power optimizations in recent Android versions we can't reliably tell when the next mail sync is going to be. So the next K-9 Mail version won't show the next poll time.

**Comment by abidal3** [comment]
> With the power optimizations in recent Android versions we can't reliably tell when the next mail sync is going to be. So the next K-9 Mail version won't show the next poll time.

Maybe you can add option for binding a sync scheduling to local time only?
