### ISSUE TITLE
Message deletions not synchronized on server

### ISSUE THREAD

**Issue by semiaddict** [thunderbird/thunderbird-android#1155]
### Expected behaviour

When the "_Sync server deletions_" setting is checked and the "_When I delete a message_" setting is set to "_Delete from server_", I would expect messaged that are deleted through K-9 Mail to be also deleted on the server.
### Actual behaviour

Messages deleted through K-9 Mail still appear in the server's inbox.
### Steps to reproduce
1. Create an IMAP account
2. Make sure the  "Sync server deletions" setting is active
3. Make sure the "When I delete a message" setting is set to "Delete from server"
4. Delete a message from K-9 Mail
5. Check to verify if it was also removed from the server through another mail client (ie. Thunderbird) or webmail
### Environment

K-9 Mail version:5.008

Android version:6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
### Log message

**SSLException: Write error: ssl=0x977e7680: I/O error during system call, Broken pipe**

K9-Mail version: 5.008
Device make: LGE
Device model: Nexus 5
Android version: 6.0.1

com.fsck.k9.mail.MessagingException: IO Error
    at com.fsck.k9.mail.store.ImapStore$ImapFolder.ioExceptionHandler(ImapStore.java:2208)
    at com.fsck.k9.mail.store.ImapStore$ImapFolder.appendMessages(ImapStore.java:2072)
    at com.fsck.k9.controller.MessagingController.processPendingAppend(MessagingController.java:2117)
    at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:1987)
    at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:975)
    at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
    at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
    at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
    at
java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLException: Write error: ssl=0x977e7680: I/O error during system call, Broken pipe
    at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
    at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:771)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:174)
    at java.io.FilterOutputStream.write(FilterOutputStream.java:129)
    at com.fsck.k9.mail.filter.EOLConvertingOutputStream.write(EOLConvertingOutputStream.java:21)
    at java.io.FilterOutputStream.write(FilterOutputStream.java:114)
    at com.fsck.k9.mail.filter.Base64OutputStream.flush(Base64OutputStream.java:149)
    at
com.fsck.k9.mail.filter.Base64OutputStream.flush(Base64OutputStream.java:165)
    at com.fsck.k9.mail.filter.Base64OutputStream.close(Base64OutputStream.java:180)
    at com.fsck.k9.mail.store.LocalStore$BinaryAttachmentBody.writeTo(LocalStore.java:4082)
    at com.fsck.k9.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:141)
    at com.fsck.k9.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:89)
    at com.fsck.k9.mail.internet.MimeMessage.writeTo(MimeMessage.java:458)
    at com.fsck.k9.mail.store.LocalStore$LocalMessage.writeTo(LocalStore.java:3616)
    at com.fsck.k9.mail.store.ImapStore$ImapFolder.appendMessages(ImapStore.java:2016)
    ... 7 more

**Comment by philipwhiuk** [comment]
From the trace this looks like IMAP, not WebDAV/Exchange

I think we need to be slightly more intelligent and less prone to erroring out on basic IO disconnection behaviour - poor mobile signal is not a K-9 error.

**Comment by semiaddict** [comment]
Thank you. This is indeed an IMAP account on an Exchange server. I rectified this mistake in my original post.
The errors also occur on a good WiFi connection, so I do not think this is a connectivity issue.

**Comment by cketti** [comment]
Are you trying to send/save a message with a large attachment? It's possible the server is closing the connection once it realizes the message is larger than allowed. I believe we're currently not handling that case very well and it could lead to this error.

If an upload is failing all other commands in the queue won't be sent to the server. That would explain why messages are not deleted from the server.

**Comment by semiaddict** [comment]
No, most of the messages are simple ones with no attachements. It happens on every message on that account when I delete them one by one or in a bulk.
I have other IMAP accounts on which those errors do not occur.

**Comment by philipwhiuk** [comment]
We should probably be a bit better at logging information about the message that failed to synchronize.

**Comment by cketti** [comment]
Sorry, I guess I should have explained better. The error message you posted shows that a message upload fails. Messages are only uploaded in two cases:
1. when saving a draft
2. when uploading a copy of a sent message to the 'Sent' folder

It is that operation that fails. And when that happens all other operations in the 'command queue', e.g. marking a message as read or deleting a message, are skipped. So what you're seeing is only a symptom of the upload issue. Chances are deleting messages works just fine, it's only that K-9 Mail doesn't get to the delete commands because there's a failing upload command stuck in the command queue.

What would help us are answers to the following questions:
1. Are there any messages in K-9 Mail's 'Drafts' folder that are not yet on the server?
2. Are there any messages in K-9 Mail's 'Sent' folder that are not yet on the server?

If so, please check if there's anything odd about them. Large attachments, missing recipient, etc.

**Comment by semiaddict** [comment]
Thank you for your help.

I have no messages in the 'Drafts' folder, but I have way too many messages in the 'Sent' folder to be able to easily check if they are all on the server.
Is there a way to know what is in the command queue to simplify the search for the stuck command ?

**Comment by philipwhiuk** [comment]
If you look at the verbose logging you might get some info, but having seen this for other mails it's pretty impenetrable. However, we need to fix #1124 to help really.

**Comment by semiaddict** [comment]
Thank you philipwhiuk and cketti for your help.

The problem seems to have vanished with no particular action on my end. It thus seems to have been a command stuck in the queue as suggested by cketti.
I restarted my phone a couple of times for another separate issue unrelated to K-9, which might be the reason behind the fix.

Thank you again for all your help.
Best regards.

**Comment by cpieloth** [comment]
The IMAP sync of deleted messages is working again on my devices:

**Device 1:**
- Android 5.0.1
- k9 Mail **5.402**

**Device 2:**
- Android 4.1.2
- k9 Mail **5.402**

**Desktop:**
- Windows 10
- Thunderbird Mail Client

Only k9 Mail was updated to latest version: 5.402

**Comment by cketti** [comment]
Please create a new issue if this is still a problem.
