### ISSUE TITLE
Local Save Failure

### ISSUE THREAD

**Issue by philipwhiuk** [thunderbird/thunderbird-android#1164]
### Expected behaviour

Large messages should always be saved correctly to local storage
### Actual behaviour

Occasionally it appears to fail to create the file.

It doesn't appear to be a persistent failure - it did succeed on retry. Maybe we should retry if we get an ENOENT error?

```
com.fsck.k9.mail.MessagingException: Error appending message: <<SUBJECT>>
at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1301)
at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1174)
at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1169)
at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1169)
at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1096)
at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1544)
at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1212)
at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:967)
at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:99)
at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:754)
at com.fsck.k9.controller.MessagingController.run(MessagingController.java:257)
at java.lang.Thread.run(Thread.java:818)
Caused by: com.fsck.k9.mail.MessagingException: Unable to open body
at com.fsck.k9.mail.internet.BinaryTempFileBody.getInputStream(BinaryTempFileBody.java:102)
at com.fsck.k9.mail.internet.BinaryTempFileBody.writeTo(BinaryTempFileBody.java:107)
at com.fsck.k9.mailstore.LocalFolder.getBodyBytes(LocalFolder.java:1501)
at com.fsck.k9.mailstore.LocalFolder.leafPartToContentValues(LocalFolder.java:1426)
at com.fsck.k9.mailstore.LocalFolder.updateOrInsertMessagePart(LocalFolder.java:1364)
at com.fsck.k9.mailstore.LocalFolder.saveMessagePart(LocalFolder.java:1336)
at com.fsck.k9.mailstore.LocalFolder.saveMessageParts(LocalFolder.java:1306)
at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1244)
... 12 more
Caused by: java.io.FileNotFoundException: /data/user/0/com.fsck.k9.debug/cache/body-1246622353.tmp: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:452)
at java.io.FileInputStream.<init>(FileInputStream.java:76)
at com.fsck.k9.mail.internet.BinaryTempFileBody.getInputStream(BinaryTempFileBody.java:100)
... 19 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
at libcore.io.IoBridge.open(IoBridge.java:438)
... 21 more
```
### Steps to reproduce
1. Receive a large email
2. Wait for/trigger synchronisation
3. Error reported
### Environment

K9-Mail version: Master (+ adding subject of email to debug output)
Device make: Huawei
Device model: Nexus 6P
Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): WebDAV

**Comment by philipwhiuk** [comment]
It is this problem that causes the HtmlConverter to be given null - `MessageExtractor.getTextFromPart` returns null in several cases.

MessageExtractor needs more work generally - it is catching OOM's and Exceptions - I dislike it catching either of these. I think it should be catch almost nothing. If we get an OOM we should be dealing with it.

```
k9.debug E/k9: Unable to getTextFromPart
com.fsck.k9.mail.MessagingException: Unable to open body
      at com.fsck.k9.mail.internet.BinaryTempFileBody.getInputStream(BinaryTempFileBody.java:96)
      at com.fsck.k9.mail.internet.MimeUtility.decodeBody(MimeUtility.java:1021)
      at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:78)
      at com.fsck.k9.message.preview.EncryptionDetector.containsInlinePgpEncryptedText(EncryptionDetector.java:44)
      at com.fsck.k9.message.preview.EncryptionDetector.isEncrypted(EncryptionDetector.java:31)
      at com.fsck.k9.message.preview.MessagePreviewCreator.createPreview(MessagePreviewCreator.java:31)
      at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1237)
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1174)
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1169)
      at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1169)
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1096)
      at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1545)
      at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1213)
      at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:968)
      at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:99)
      at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:755)
      at com.fsck.k9.controller.MessagingController.run(MessagingController.java:258)
      at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.FileNotFoundException: /data/user/0/com.fsck.k9.debug/cache/body-991001268.tmp: open failed: ENOENT (No such file or directory)
      at libcore.io.IoBridge.open(IoBridge.java:452)
      at java.io.FileInputStream.<init>(FileInputStream.java:76)
      at com.fsck.k9.mail.internet.BinaryTempFileBody.getInputStream(BinaryTempFileBody.java:94)
      at com.fsck.k9.mail.internet.MimeUtility.decodeBody(MimeUtility.java:1021) 
      at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:78) 
      at com.fsck.k9.message.preview.EncryptionDetector.containsInlinePgpEncryptedText(EncryptionDetector.java:44) 
      at com.fsck.k9.message.preview.EncryptionDetector.isEncrypted(EncryptionDetector.java:31) 
      at com.fsck.k9.message.preview.MessagePreviewCreator.createPreview(MessagePreviewCreator.java:31)
      at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1237)
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1174) 
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1169) 
      at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275) 
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1169) 
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1096) 
      at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1545) 
      at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1213) 
      at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:968) 
      at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:99) 
      at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:755) 
      at com.fsck.k9.controller.MessagingController.run(MessagingController.java:258) 
      at java.lang.Thread.run(Thread.java:818) 
                                                        Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
      at libcore.io.Posix.open(Native Method)
      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
      at libcore.io.IoBridge.open(IoBridge.java:438)
      at java.io.FileInputStream.<init>(FileInputStream.java:76) 
      at com.fsck.k9.mail.internet.BinaryTempFileBody.getInputStream(BinaryTempFileBody.java:94) 
      at com.fsck.k9.mail.internet.MimeUtility.decodeBody(MimeUtility.java:1021) 
      at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:78) 
      at com.fsck.k9.message.preview.EncryptionDetector.containsInlinePgpEncryptedText(EncryptionDetector.java:44) 
      at com.fsck.k9.message.preview.EncryptionDetector.isEncrypted(EncryptionDetector.java:31) 
      at com.fsck.k9.message.preview.MessagePreviewCreator.createPreview(MessagePreviewCreator.java:31) 
      at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1237) 
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1174) 
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1169) 
      at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275) 
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1169) 
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1096) 
      at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1545) 
      at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1213) 
      at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:968) 
      at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:99) 
      at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:755) 
      at com.fsck.k9.controller.MessagingController.run(MessagingController.java:258) 
      at java.lang.Thread.run(Thread.java:818) 
03-11 12:13:38.323 32690-32719/com.fsck.k9.debug E/k9: Unable to getTextFromPart
com.fsck.k9.mail.MessagingException: Unable to open body
      at com.fsck.k9.mail.internet.BinaryTempFileBody.getInputStream(BinaryTempFileBody.java:96)
      at com.fsck.k9.mail.internet.MimeUtility.decodeBody(MimeUtility.java:1021)
      at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:78)
      at com.fsck.k9.message.preview.PreviewTextExtractor.extractPreview(PreviewTextExtractor.java:19)
      at com.fsck.k9.message.preview.MessagePreviewCreator.extractText(MessagePreviewCreator.java:44)
      at com.fsck.k9.message.preview.MessagePreviewCreator.createPreview(MessagePreviewCreator.java:35)
      at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1237)
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1174)
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1169)
      at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1169)
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1096)
      at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1545)
      at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1213)
      at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:968)
      at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:99)
      at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:755)
      at com.fsck.k9.controller.MessagingController.run(MessagingController.java:258)
      at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.FileNotFoundException: /data/user/0/com.fsck.k9.debug/cache/body-991001268.tmp: open failed: ENOENT (No such file or directory)
      at libcore.io.IoBridge.open(IoBridge.java:452)
      at java.io.FileInputStream.<init>(FileInputStream.java:76)
      at com.fsck.k9.mail.internet.BinaryTempFileBody.getInputStream(BinaryTempFileBody.java:94)
      at com.fsck.k9.mail.internet.MimeUtility.decodeBody(MimeUtility.java:1021) 
      at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:78) 
      at com.fsck.k9.message.preview.PreviewTextExtractor.extractPreview(PreviewTextExtractor.java:19) 
      at com.fsck.k9.message.preview.MessagePreviewCreator.extractText(MessagePreviewCreator.java:44) 
      at com.fsck.k9.message.preview.MessagePreviewCreator.createPreview(MessagePreviewCreator.java:35) 
      at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1237) 
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1174) 
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1169) 
      at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275) 
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1169) 
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1096) 
      at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1545) 
      at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1213) 
      at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:968) 
      at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:99) 
      at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:755) 
      at com.fsck.k9.controller.MessagingController.run(MessagingController.java:258) 
      at java.lang.Thread.run(Thread.java:818) 
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
      at libcore.io.Posix.open(Native Method)
      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
      at libcore.io.IoBridge.open(IoBridge.java:438)
      at java.io.FileInputStream.<init>(FileInputStream.java:76) 
      at com.fsck.k9.mail.internet.BinaryTempFileBody.getInputStream(BinaryTempFileBody.java:94) 
      at com.fsck.k9.mail.internet.MimeUtility.decodeBody(MimeUtility.java:1021) 
      at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:78) 
      at com.fsck.k9.message.preview.PreviewTextExtractor.extractPreview(PreviewTextExtractor.java:19) 
      at com.fsck.k9.message.preview.MessagePreviewCreator.extractText(MessagePreviewCreator.java:44) 
      at com.fsck.k9.message.preview.MessagePreviewCreator.createPreview(MessagePreviewCreator.java:35) 
      at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1237) 
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1174) 
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1169) 
      at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275) 
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1169) 
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1096) 
      at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1545) 
      at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1213)
      at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:968)
      at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:99)
      at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:755) 
      at com.fsck.k9.controller.MessagingController.run(MessagingController.java:258) 
      at java.lang.Thread.run(Thread.java:818) 
03-11 12:13:38.366 32690-32719/com.fsck.k9.debug E/k9: synchronizeMailbox
com.fsck.k9.mail.MessagingException: Error appending message: RE: Testing Allocation Server Splitting FlexAPI messages
      at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1301)
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1174)
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1169)
      at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1169)
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1096)
      at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1545)
      at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1213)
      at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:968)
      at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:99)
      at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:755)
      at com.fsck.k9.controller.MessagingController.run(MessagingController.java:258)
      at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
      at java.io.StringReader.<init>(StringReader.java:47)
      at android.text.HtmlToSpannedConverter.convert(Html.java:449)
      at android.text.Html.fromHtml(Html.java:136)
      at com.fsck.k9.helper.HtmlConverter.htmlToText(HtmlConverter.java:155)
      at com.fsck.k9.message.preview.PreviewTextExtractor.convertFromHtmlIfNecessary(PreviewTextExtractor.java:31)
      at com.fsck.k9.message.preview.PreviewTextExtractor.extractPreview(PreviewTextExtractor.java:20)
      at com.fsck.k9.message.preview.MessagePreviewCreator.extractText(MessagePreviewCreator.java:44)
      at com.fsck.k9.message.preview.MessagePreviewCreator.createPreview(MessagePreviewCreator.java:35)
      at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1237)
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1174)
      at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1169)
      at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1169)
      at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1096)
      at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1545)
      at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1213)
      at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:968)
      at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:99)
      at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:755)
      at com.fsck.k9.controller.MessagingController.run(MessagingController.java:258)
      at java.lang.Thread.run(Thread.java:818) 
03-11 12:13:38.457 32690-32719/com.fsck.k9.debug E/k9: Failed synchronizing folder Work:AllocationsServer @ Fri Mar 11 12:13:38 GMT+00:00 2016
```
