### ISSUE TITLE
Crash on screen rotate with OpenPGP handled message

### ISSUE THREAD

**Issue by philipwhiuk** [thunderbird/thunderbird-android#1227]
### Expected behaviour

Message should be re-rendered in landscape.
### Actual behaviour

Application crashes with following exception.

```
03-29 08:40:55.041 12045-12045/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.fsck.k9.debug, PID: 12045
                                                                   java.util.NoSuchElementException
                                                                       at java.util.ArrayDeque.removeFirst(ArrayDeque.java:248)
                                                                       at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoFinished(MessageCryptoHelper.java:454)
                                                                       at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoSuccess(MessageCryptoHelper.java:438)
                                                                       at com.fsck.k9.ui.crypto.MessageCryptoHelper.handleCryptoOperationSuccess(MessageCryptoHelper.java:420)
                                                                       at com.fsck.k9.ui.crypto.MessageCryptoHelper.handleCryptoOperationResult(MessageCryptoHelper.java:379)
                                                                       at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoOperationReturned(MessageCryptoHelper.java:353)
                                                                       at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$400(MessageCryptoHelper.java:49)
                                                                       at com.fsck.k9.ui.crypto.MessageCryptoHelper$4.onReturn(MessageCryptoHelper.java:250)
                                                                       at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.onPostExecute(OpenPgpApi.java:298)
                                                                       at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.onPostExecute(OpenPgpApi.java:279)
                                                                       at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                       at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Email available on request.
### Steps to reproduce
1. Receive a message that has been signed
2. Open the message.
3. Rotate the phone to landscape
### Environment

K-9 Mail version: commit 74c6e76 (current master)
OpenKeychain version: 3.9.4
Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
I added some logging and this appears to be because decryption gets called twice because `onLoadFinished` gets called twice.



```
04-01 15:34:59.482 25301-25301/com.fsck.k9.debug V/k9: Decrypting / verifying parts
java.lang.Exception
    at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptOrVerifyMessagePartsIfNecessary(MessageCryptoHelper.java:80)
    at com.fsck.k9.ui.messageview.MessageViewFragment.onLoadMessageFromDatabaseFinished(MessageViewFragment.java:231)
    at com.fsck.k9.ui.messageview.MessageViewFragment.access$1000(MessageViewFragment.java:57)
    at com.fsck.k9.ui.messageview.MessageViewFragment$LocalMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:735)
    at com.fsck.k9.ui.messageview.MessageViewFragment$LocalMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:721)
    at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)
    at android.app.LoaderManagerImpl$LoaderInfo.reportStart(LoaderManager.java:322)
    at android.app.LoaderManagerImpl.doReportStart(LoaderManager.java:826)
    at android.app.Fragment.performStart(Fragment.java:2253)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1002)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
    at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1958)
    at android.app.FragmentController.dispatchStart(FragmentController.java:163)
    at android.app.Activity.performStart(Activity.java:6274)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
    at android.app.ActivityThread.-wrap15(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5422)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-01 15:34:59.494 25301-25301/com.fsck.k9.debug V/k9: Decrypting / verifying parts
java.lang.Exception
    at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptOrVerifyMessagePartsIfNecessary(MessageCryptoHelper.java:80)
    at com.fsck.k9.ui.messageview.MessageViewFragment.onLoadMessageFromDatabaseFinished(MessageViewFragment.java:231)
    at com.fsck.k9.ui.messageview.MessageViewFragment.access$1000(MessageViewFragment.java:57)
    at com.fsck.k9.ui.messageview.MessageViewFragment$LocalMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:735)
    at com.fsck.k9.ui.messageview.MessageViewFragment$LocalMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:721)
    at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)
    at android.app.LoaderManagerImpl$LoaderInfo.finishRetain(LoaderManager.java:313)
    at android.app.LoaderManagerImpl.finishRetain(LoaderManager.java:813)
    at android.app.FragmentHostCallback.reportLoaderStart(FragmentHostCallback.java:270)
    at android.app.FragmentController.reportLoaderStart(FragmentController.java:357)
    at android.app.Activity.performStart(Activity.java:6275)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
    at android.app.ActivityThread.-wrap15(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5422)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

S/O discussion on this: http://stackoverflow.com/questions/11293441/android-loadercallbacks-onloadfinished-called-twice

Apparently it's the lack of `getLoaderManager().destroyLoader(LOADER_ID);` call that causes this.

**Comment by philipwhiuk** [comment]
Adding the line to destroy it after loading seems to work.
