### ISSUE TITLE
Application crash: no free notification ID

### ISSUE THREAD

**Issue by philipwhiuk** [thunderbird/thunderbird-android#1245]
### Expected behaviour

Can view folder having retrieved unread mail.
### Actual behaviour

Application crash (K-9 has stopped)
### Steps to reproduce
1. Find a folder with mail server side that hasn't yet been synced
2. Pull-refresh the folder
3. Application crash reported

```
--------- beginning of crash
04-01 08:48:47.502 9926-9959/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: MessagingController
            Process: com.fsck.k9.debug, PID: 9926
            java.lang.AssertionError: getNewNotificationId() called with no free notification ID
                at com.fsck.k9.notification.NotificationData.getNewNotificationId(NotificationData.java:77)
                at com.fsck.k9.notification.NotificationData.addNotificationContent(NotificationData.java:46)
                at com.fsck.k9.notification.NewMailNotifications.addNewMailNotification(NewMailNotifications.java:56)
                at com.fsck.k9.notification.NotificationController.addNewMailNotification(NotificationController.java:95)
                at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1584)
                at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1218)
                at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:979)
                at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:764)
                at com.fsck.k9.controller.MessagingController.run(MessagingController.java:267)
                at java.lang.Thread.run(Thread.java:818)
```
### Environment

K-9 Mail version: 74c6e764338d312dab49bb6e5499ee82d2c86c83

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
This appears to be because we never clear or set to false elements of `notificationIdsInUse`

**Comment by cketti** [comment]
See #1662
