### ISSUE TITLE
NPE caused by failure to check mAccount is valid in AccountSettings

### ISSUE THREAD

**Issue by philipwhiuk** [thunderbird/thunderbird-android#1272]
### Expected behaviour

Show the account settings
### Actual behaviour

```
04-11 12:12:27.895 E/AndroidRuntime(29853): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.fsck.k9.Account.getUuid()' on a null object reference
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.fsck.k9.activity.setup.AccountSettings.actionSettings(AccountSettings.java:203)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.fsck.k9.activity.MessageList.onEditAccount(MessageList.java:760)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.fsck.k9.activity.MessageList.onOptionsItemSelected(MessageList.java:826)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at android.app.Activity.onMenuItemSelected(Activity.java:2914)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1151)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.android.internal.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:82)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:200)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at android.widget.AdapterView.performItemClick(AdapterView.java:310)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at android.widget.AbsListView$3.run(AbsListView.java:3903)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at android.os.Handler.handleCallback(Handler.java:739)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at android.os.Handler.dispatchMessage(Handler.java:95)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at android.os.Looper.loop(Looper.java:148)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at android.app.ActivityThread.main(ActivityThread.java:5422)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at java.lang.reflect.Method.invoke(Native Method)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-11 12:12:27.895 E/AndroidRuntime(29853):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
### Steps to reproduce

May require existing error scenario to occur. Log taken from #1271

Appears that they tapped on the menu item while in the message list
### Environment

K-9 Mail version: 6.108
Android version: unknown / rooted
Account type (IMAP, POP3, WebDAV/Exchange): ?
### Comment

Somehow they are managing to enter the MessageList without checking the state of `mAccount` for null, which we do in `onCreate` and `onResume`

**Comment by cketti** [comment]
The account settings code has been rewritten since then. This is most likely no longer an issue.
