### ISSUE TITLE
K9 crash on delete when full message was not downloaded

### ISSUE THREAD

**Issue by hochwasser** [thunderbird/thunderbird-android#1468]
### Expected behavior

When I press delete, even if the message was not full downloaded, the message get deleted and the program does not crash. Small messages got deleted without crash. Large messages (when there is the option to download it full) crashes k9.
### Actual behavior

The message get deleted on the server but K9 crashes.
### Steps to reproduce
1. open large email that is not full downloaded
2. press delete
3. confirm
4. k9 crashes

Stacktrace:

```
06-20 21:01:03.828 11593-11593/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.fsck.k9, PID: 11593
                                                   java.lang.IllegalStateException: Couldn't read row 829, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                       at android.database.CursorWindow.nativeGetLong(Native Method)
                                                       at android.database.CursorWindow.getLong(CursorWindow.java:511)
                                                       at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
                                                       at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
                                                       at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
                                                       at com.fsck.k9.provider.EmailProvider$SpecialColumnsCursor.getLong(EmailProvider.java:776)
                                                       at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
                                                       at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
                                                       at com.fsck.k9.helper.MergeCursor.getLong(MergeCursor.java:188)
                                                       at com.fsck.k9.helper.MergeCursorWithUniqueId.getPerCursorId(MergeCursorWithUniqueId.java:81)
                                                       at com.fsck.k9.helper.MergeCursorWithUniqueId.getLong(MergeCursorWithUniqueId.java:56)
                                                       at com.fsck.k9.fragment.MessageListFragment.computeBatchDirection(MessageListFragment.java:2317)
                                                       at com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:3467)
                                                       at com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:108)
                                                       at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)
                                                       at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:451)
                                                       at android.content.Loader.deliverResult(Loader.java:144)
                                                       at android.content.CursorLoader.deliverResult(CursorLoader.java:109)
                                                       at android.content.CursorLoader.deliverResult(CursorLoader.java:97)
                                                       at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:265)
                                                       at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
                                                       at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                       at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
### Environment

K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This should be fixed in recent beta versions (5.7xx).
