### ISSUE TITLE
Android 6.01: k9 5.111 does not show emails that arrived during doze

### ISSUE THREAD

**Issue by dikay0** [thunderbird/thunderbird-android#1623]
### Expected behaviour

the program should show all emails that arrived
### Actual behaviour

the program does not show emails that arrived overnight; a webmail client (or email clients on other devices) however shows them.
### Steps to reproduce
1. K9 is exempted from doze mode (as are two system apps, play services and a samsung app, that are exempted by default)
2. let sit overnight 
3. pick up phone in the morning, check emails - nothing (seemingly) has arrived. Afterwards, k9 performs normally, i.e. emails arriving later are shown. But those that arrived during the doze mode in the night are never shown; they are only seen by desktop email clients or using webmail on the smartphone.
### Environment

K-9 Mail version: 5.111. The problem does not exist with the current 5.010.

Android version: 6.01

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by dikay0** [comment]
Forgot to mention this is an unrooted Galaxy A5

**Comment by gdt** [comment]
I have a similar problem with 5.111 and CM13, but with K-9 left in the default optimized state.  In the morning (phone not plugged in overnight), emails that arrived overnight are not present.  Even when picking up the phone, unlocking, and going to K-9 they do not arrive. But, pushing the sync button causes them to load.   I have just changed to 'not optimized' to see if that helps.  I am pretty sure that with 5.010 I didn't have this problem.

I think there are probably two things going on.  One is whatever dikay0@ is reporting.  The other is that without disabling optimization, K-9 should still schedule wakeups to connect for push/poll occasionally, or at least connect for push and poll (how I have it set) once doze mode is exited and the app is opened.   I'm fine with much higher latency of arrival in doze mode, but it seems that new email ~never arrives after doze without a manual sync.

**Comment by philipwhiuk** [comment]
Please keep discussion of issues surrounding polling during Doze and resuming PUSH email after Doze to existing issues (of which there are many). I.e. if all the email arrives on a subsequent sync it's not this issue.

I want to keep this one concerning emails that are 'skipped' because they hit the mailbox during Doze and never get pulled in a subsequent manual sync. 

That's much more serious to me and I've not got a working theory on why it could happen.

@cketti the only thing I can even vaguely think this could be is UIDVALIDITY?

@dikay0 if you can reproduce this issue I'd love to see some device logs for this.

**Comment by dikay0** [comment]
**@gdt** trying to manually sync does not bring up the emails. I found no way to see them with K9 5.111 - neither by rebooting the phone, nor by killing K9 and restarting it.

**@philipwhiuk** this was reproduced every morning. I enabled the "debug log" feature but was not able to locate the log on the phone ... some googling seems to indicate that one needs to attach the phone to a PC and run "adb something". I might try this.

**Comment by ahmadaamer6** [comment]
@dikay0 Just look in your unified inbox and you will see a local email with the debug log.

**Comment by dikay0** [comment]
@ahmadaamer6 this is not mentioned at https://k9mail.github.io/documentation/debugging.html; does it really work like that? I don't have a unified inbox (want to keep my accounts separate) but I could enable it. But when is that "local email" sent? When I stop the debug logging? Or once a day? Or more often?

**Comment by dikay0** [comment]
this morning one email that arrived during the night was missing. I looked at the debug log (using adb on Linux) and identified the lines that show some kind of error for this message ("CCP4BB Digest - 20 Sep 2016 to 21 Sep 2016 (#2016-260)"). I cannot interpret these lines but I'm posting them here.
[log.short.txt](https://github.com/k9mail/k-9/files/486611/log.short.txt)

**Comment by philipwhiuk** [comment]
Thanks! We should be able to fix these :)

**Comment by dikay0** [comment]
@philipwhiuk : you didn't elaborate what constitutes the bug, but the impression I get when trying to understand the debug log is that the problem has nothing to do with doze, but rather that this specific email (and others of this kind - digests of mailing lists in my case) triggers some other kind of bug?
@ahmadaamer6 : indeed I found a new (local) folder K9mail-errors under the same account which had an email (created when the error occurred) with a debug log. It seems to me that it has somewhat less information than what I get with adb but the procedure and existence should really be mentioned/explained at https://k9mail.github.io/documentation/debugging.html ! Should I open an issue for this?
For the record, I paste the contents of the debug log email below:
 
Von: K9mail internal <kay.diederichs@xxx.yyy>
Gesendet: 22. September 2016 08:26:39 MESZ
Betreff: NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference

K9-Mail version: 5.111
Device make: samsung
Device model: SM-A510F
Android version: 6.0.1

com.fsck.k9.mail.MessagingException: Error appending message: CCP4BB Digest - 20 Sep 2016 to 21 Sep 2016 (#2016-260)
	at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1325)
	at com.fsck.k9.mailstore.LocalFolder$14.doDbWork(LocalFolder.java:1186)
	at com.fsck.k9.mailstore.LocalFolder$14.doDbWork(LocalFolder.java:1181)
	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
	at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1181)
	at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1108)
	at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1496)
	at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1203)
	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:953)
	at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
	at com.fsck.k9.mail.internet.MimeUtility.closeInputStreamWithoutDeletingTemporaryFiles(MimeUtility.java:1060)
	at com.fsck.k9.mail.internet.MessageExtractor.getTextFromTextPart(MessageExtractor.java:112)
	at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:55)
	at com.fsck.k9.crypto.MessageDecryptVerifier.isPartPgpInlineEncrypted(MessageDecryptVerifier.java:207)
	at com.fsck.k9.message.extractors.EncryptionDetector.containsInlinePgpEncryptedText(EncryptionDetector.java:34)
	at com.fsck.k9.message.extractors.EncryptionDetector.isEncrypted(EncryptionDetector.java:25)
	at com.fsck.k9.message.extractors.MessagePreviewCreator.createPreview(MessagePreviewCreator.java:31)
	at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1250)
	... 13 more

**Comment by philipwhiuk** [comment]
@dikay0 

There are two bugs here.

1. The e-mail you are receiving has content of a type currently unsupported. We've already got an issue for this - #733
2. During clean-up we're trying to close an input stream that has already been cleaned up.

I think if we fix the second you might see an email with a subject title but not be able to see the contents.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with the latest K-9 Mail version.
