### ISSUE TITLE
App crashes after tapping the compose email button

### ISSUE THREAD

**Issue by ahmadaamer6** [thunderbird/thunderbird-android#1627]
**I am having the same issue as the one listed here: https://github.com/k9mail/k-9/issues/1112**
### Expected behavior

After tapping the compose button a compose window should appear, so I can type an email to someone.
### Actual behavior

After tapping the compose button the app crashes and a messages pops up saying that K-9 Mail has crashed.
### Steps to reproduce
1. Open K-9 Mail
2. Tap the compose button (plus sign on top of a letter icon)
### Environment

K-9 Mail version: **5.111 (Current Alpha)**

Android version: **Droid Bionic (targa) 4.1.2**

Account type (IMAP, POP3, WebDAV/Exchange): **IMAP**

**Comment by philipwhiuk** [comment]
If you're having the same problem as someone else, there's no need to open another issue.

**Comment by mgorny** [comment]
I can reproduce the same issue with v5.203 on MotoE 2nd gen., Android 6.0.

Here's the crash log:
```
--------- beginning of system
--------- beginning of crash
03-13 05:11:54.667 E/AndroidRuntime(23663): FATAL EXCEPTION: main
03-13 05:11:54.667 E/AndroidRuntime(23663): Process: com.fsck.k9, PID: 23663
03-13 05:11:54.667 E/AndroidRuntime(23663): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at com.fsck.k9.mail.Address.equals(Address.java:169)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at com.fsck.k9.view.RecipientSelectView$Recipient.equals(RecipientSelectView.java:604)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at java.util.ArrayList.contains(ArrayList.java:339)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at com.tokenautocomplete.TokenCompleteTextView.insertSpan(TokenCompleteTextView.java:1060)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at com.tokenautocomplete.TokenCompleteTextView.access$700(TokenCompleteTextView.java:54)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at com.tokenautocomplete.TokenCompleteTextView$3.run(TokenCompleteTextView.java:924)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at android.os.Handler.handleCallback(Handler.java:746)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at android.os.Looper.loop(Looper.java:148)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at java.lang.reflect.Method.invoke(Native Method)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
03-13 05:11:54.667 E/AndroidRuntime(23663): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
03-13 06:42:57.416 E/AndroidRuntime( 1530): FATAL EXCEPTION: main
03-13 06:42:57.416 E/AndroidRuntime( 1530): Process: com.fsck.k9, PID: 1530
03-13 06:42:57.416 E/AndroidRuntime( 1530): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.fsck.k9/com.fsck.k9.activity.MessageCompose}; have you declared this activity in your AndroidManifest.xml?
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1885)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1579)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.app.Activity.startActivityForResult(Activity.java:3921)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.app.Activity.startActivityForResult(Activity.java:3881)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.app.Activity.startActivity(Activity.java:4208)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.app.Activity.startActivity(Activity.java:4176)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.fsck.k9.activity.compose.MessageActions.actionCompose(MessageActions.java:25)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.fsck.k9.activity.Accounts.onCompose(Accounts.java:629)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.fsck.k9.activity.Accounts.onOptionsItemSelected(Accounts.java:1236)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.app.Activity.onMenuItemSelected(Activity.java:2912)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1151)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:616)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:141)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.view.View.performClick(View.java:5201)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.view.View$PerformClick.run(View.java:21163)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.os.Handler.handleCallback(Handler.java:746)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.os.Looper.loop(Looper.java:148)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at java.lang.reflect.Method.invoke(Native Method)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
03-13 06:42:57.416 E/AndroidRuntime( 1530): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

(then more of the latter exception)

**Comment by mgorny** [comment]
(it's possible that the former was the result of trying an older version earlier today)

**Comment by philipwhiuk** [comment]
Where are you installing K-9 from - Google Play / F-Droid / somewhere else? It seems like the APK you are installing might not contain all the classes for some reason...

**Comment by mgorny** [comment]
Google Play, originally. I should note that it's a regression for me, i.e. it just stopped working at some point. Then I've tried installing a few old `.apk`s straight from GitHub, and I could reproduce the same result with all of them. I suspect it might be related to some system update or something like that. Anything I could do to help?

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with the latest K-9 Mail version.
