### ISSUE TITLE
Attempting to save an attachment causes K-9 to enter a download loop

### ISSUE THREAD

**Issue by philipwhiuk** [thunderbird/thunderbird-android#1629]
### Expected behavior

Tell us what should happen
### Actual behavior

A modal for Downloading attachment comes on screen, the background activity darkens, then the dialog closes, the screen goes white, then the dialog reappears, etc:

Log trace:

```
09-23 00:55:51.979 24747-24765/com.fsck.k9.debug I/k9:  Command 'loadAttachment' completed
09-23 00:55:52.000 24747-24765/com.fsck.k9.debug I/k9: Running command 'loadAttachment', seq = 109(foregroundpriority)
09-23 00:55:52.184 24747-24765/com.fsck.k9.debug I/k9:  Command 'loadAttachment' completed
09-23 00:55:52.202 24747-24765/com.fsck.k9.debug I/k9: Running command 'loadAttachment', seq = 110(foregroundpriority)
09-23 00:55:53.193 24747-24765/com.fsck.k9.debug I/k9:  Command 'loadAttachment' completed
09-23 00:55:53.223 24747-24765/com.fsck.k9.debug I/k9: Running command 'loadAttachment', seq = 111(foregroundpriority)
09-23 00:55:55.195 24747-24765/com.fsck.k9.debug I/k9:  Command 'loadAttachment' completed
09-23 00:55:55.214 24747-24765/com.fsck.k9.debug I/k9: Running command 'loadAttachment', seq = 112(foregroundpriority)
09-23 00:55:55.653 24747-24765/com.fsck.k9.debug I/k9:  Command 'loadAttachment' completed
09-23 00:55:55.684 24747-24765/com.fsck.k9.debug I/k9: Running command 'loadAttachment', seq = 113(foregroundpriority)
09-23 00:55:56.201 24747-24765/com.fsck.k9.debug I/k9:  Command 'loadAttachment' completed
....
```

Eventually the app crashed with:

```
09-23 00:58:12.126 24747-24747/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.fsck.k9.debug, PID: 24747
                                                   java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)
                                                       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)
                                                       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:707)
                                                       at android.app.BackStackRecord.commit(BackStackRecord.java:671)
                                                       at android.app.DialogFragment.dismissInternal(DialogFragment.java:301)
                                                       at android.app.DialogFragment.dismiss(DialogFragment.java:267)
                                                       at com.fsck.k9.ui.messageview.MessageViewFragment.removeDialog(MessageViewFragment.java:551)
                                                       at com.fsck.k9.ui.messageview.MessageViewFragment.access$200(MessageViewFragment.java:55)
                                                       at com.fsck.k9.ui.messageview.MessageViewFragment$3.run(MessageViewFragment.java:648)
```

When the application was opened again, the attachment was saved successfully.
### Steps to reproduce
1. Receive an email with an attachment
2. Try to save it
### Environment

K-9 Mail version: master

Android version: 7.0.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by ConorIA** [comment]
I can confirm this issue on Android 7.0 using K-9 5.111. It is not present on stable 5.010.

**Comment by philipwhiuk** [comment]
Got it to reliably crash on a specific image:

**Trace**

The following block is repeated endlessly.

```
10-07 23:24:55.766 30903-30975/com.fsck.k9.debug I/k9: Running command 'loadAttachment', seq = 20(foregroundpriority)
10-07 23:24:55.766 30903-30975/com.fsck.k9.debug V/k9: conn25438699>>> 49 NOOP
10-07 23:24:56.341 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#49# [OK, NOOP completed.]
10-07 23:24:56.343 30903-30975/com.fsck.k9.debug V/k9: conn25438699>>> 50 SELECT "INBOX"
10-07 23:24:56.515 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#null# [OK, [CLOSED], Previous mailbox closed.]
10-07 23:24:56.518 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#null# [FLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, NonJunk, Junk, $Forwarded, $has_cal, $NotJunk, $Junk, JunkRecorded, NotJunk, SEEN]]
10-07 23:24:56.520 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#null# [OK, [PERMANENTFLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, NonJunk, Junk, $Forwarded, $has_cal, $NotJunk, $Junk, JunkRecorded, NotJunk, SEEN, \*]], Flags permitted.]
10-07 23:24:56.520 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#null# [238, EXISTS]
10-07 23:24:56.523 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#null# [0, RECENT]
10-07 23:24:56.524 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#null# [OK, [UNSEEN, 26], First unseen.]
10-07 23:24:56.524 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#null# [OK, [UIDVALIDITY, 1303489241], UIDs valid]
10-07 23:24:56.524 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#null# [OK, [UIDNEXT, 89431], Predicted next UID]
10-07 23:24:56.525 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#null# [OK, [HIGHESTMODSEQ, 115145], Highest]
10-07 23:24:56.525 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#50# [OK, [READ-WRITE], Select completed (0.000 secs).]
10-07 23:24:56.525 30903-30975/com.fsck.k9.debug D/k9: Got untagged EXISTS with value 238 for Home:INBOX/MessagingController/conn25438699
10-07 23:24:56.526 30903-30975/com.fsck.k9.debug D/k9: Got UidNext = 89431 for Home:INBOX/MessagingController/conn25438699
10-07 23:24:56.528 30903-30975/com.fsck.k9.debug V/k9: conn25438699>>> 51 UID FETCH 89412 (UID BODY.PEEK[4])
10-07 23:24:56.548 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#null# [221, FETCH, [UID, 89412, BODY, [4], com.fsck.k9.mail.internet.BinaryTempFileBody@57f06b3]]
10-07 23:24:56.550 30903-30975/com.fsck.k9.debug V/k9: conn25438699<<<#51# [OK, Fetch completed.]
10-07 23:24:56.598 30903-30975/com.fsck.k9.debug D/k9: deleting temp file
10-07 23:24:56.612 30903-30975/com.fsck.k9.debug I/k9:  Command 'loadAttachment' completed
```
