### ISSUE TITLE
HTML messages not displaying

### ISSUE THREAD

**Issue by NTICompass** [thunderbird/thunderbird-android#1733]
### Expected behavior

HTML messages should be rendered, with an option to show external images
### Actual behavior

Email display is blank, with only a "download complete message" button... which does nothing
### Steps to reproduce
1. Open HTML email from inbox
2. Email is displayed as blank
3. Press "download complete message"
4. Email is still blank
### Environment

K-9 Mail version: 5.114

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): Gmail (via IMAP)
### Logcat:

```
10-18 22:53:35.104 D/k9      (28045): MessageView displaying message MessageReference{accountUuid='539ac8f9-8c8d-49be-9ead-7501fa654db4', folderName='INBOX', uid='36065', flag=null}
10-18 22:53:35.109 D/k9      (28045): Creating new local message loader
10-18 22:53:35.139 D/ConnectivityService(  820): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 119]
10-18 22:53:35.406 D/k9      (28045): Creating new decode message loader
10-18 22:53:35.436 V/k9      (28045): LockableDatabase: Transaction ended, took 89ms / com.fsck.k9.mailstore.LocalStore.doBatchSetSelection(LocalStore.java:904)
10-18 22:53:35.502 E/k9      (28045): Unable to getTextFromPart
10-18 22:53:35.502 E/k9      (28045): com.fsck.k9.mail.MessagingException: Provided invalid part: com.fsck.k9.mailstore.LocalBodyPart@86ec7f7
10-18 22:53:35.502 E/k9      (28045):   at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:60)
10-18 22:53:35.502 E/k9      (28045):   at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:42)
10-18 22:53:35.502 E/k9      (28045):   at com.fsck.k9.mailstore.MessageViewInfoExtractor.buildHtml(MessageViewInfoExtractor.java:224)
10-18 22:53:35.502 E/k9      (28045):   at com.fsck.k9.mailstore.MessageViewInfoExtractor.extractTextFromViewables(MessageViewInfoExtractor.java:186)
10-18 22:53:35.502 E/k9      (28045):   at com.fsck.k9.mailstore.MessageViewInfoExtractor.extractViewableAndAttachments(MessageViewInfoExtractor.java:115)
10-18 22:53:35.502 E/k9      (28045):   at com.fsck.k9.mailstore.MessageViewInfoExtractor.extractMessageForView(MessageViewInfoExtractor.java:85)
10-18 22:53:35.502 E/k9      (28045):   at com.fsck.k9.ui.message.LocalMessageExtractorLoader.loadInBackground(LocalMessageExtractorLoader.java:55)
10-18 22:53:35.502 E/k9      (28045):   at com.fsck.k9.ui.message.LocalMessageExtractorLoader.loadInBackground(LocalMessageExtractorLoader.java:18)
10-18 22:53:35.502 E/k9      (28045):   at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
10-18 22:53:35.502 E/k9      (28045):   at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
10-18 22:53:35.502 E/k9      (28045):   at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
10-18 22:53:35.502 E/k9      (28045):   at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-18 22:53:35.502 E/k9      (28045):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-18 22:53:35.502 E/k9      (28045):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-18 22:53:35.502 E/k9      (28045):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-18 22:53:35.502 E/k9      (28045):   at java.lang.Thread.run(Thread.java:818)
10-18 22:53:35.567 I/Xposed  (28045): getWebViewPackageName
10-18 22:53:35.568 I/WebViewFactory(28045): Loading com.google.android.webview version 53.0.2785.124 (code 278512400)
10-18 22:53:35.700 I/art     (28045): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
10-18 22:53:35.701 I/art     (28045): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
10-18 22:53:35.704 I/art     (28045): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
10-18 22:53:35.705 I/art     (28045): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
10-18 22:53:35.746 I/cr_LibraryLoader(28045): Time to load native libraries: 10 ms (timestamps 6710-6720)
10-18 22:53:35.748 I/cr_LibraryLoader(28045): Expected native library version number "53.0.2785.124", actual native library version number "53.0.2785.124"
10-18 22:53:35.797 V/WebViewChromiumFactoryProvider(28045): Binding Chromium to main looper Looper (main, tid 1) {7f6f200}
10-18 22:53:35.797 I/cr_LibraryLoader(28045): Expected native library version number "53.0.2785.124", actual native library version number "53.0.2785.124"
10-18 22:53:35.817 I/chromium(28045): [INFO:library_loader_hooks.cc(151)] Chromium logging enabled: level = 0, default verbosity = 0
10-18 22:53:35.867 I/cr_BrowserStartup(28045): Initializing chromium process, singleProcess=true
10-18 22:53:36.124 W/cr_media(28045): Requires BLUETOOTH permission
10-18 22:53:36.204 D/ConnectivityService(  820): listenForNetwork for Listen from uid/pid:10093/28045 for NetworkRequest [ id=157, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
10-18 22:53:36.233 W/cr_AwContents(28045): onDetachedFromWindow called when already detached. Ignoring
10-18 22:53:36.274 E/SELinux (  232): avc:  denied  { find } for service=batterymanager scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:battery_service:s0 tclass=service_manager
10-18 22:53:36.286 I/cr_Ime  (28045): ImeThread is not enabled.
10-18 22:53:36.289 D/k9      (28045): No external images.
10-18 22:53:36.300 I/Choreographer(28045): Skipped 44 frames!  The application may be doing too much work on its main thread.
```
### Original email

Link: https://gist.github.com/anonymous/caa7b4a3ed4d9090882c6e4f30c6e668

**Comment by cketti** [comment]
Works for me. Try uninstalling and reinstalling.

Closing this issue because you're using the Xposed framework. Chasing bugs on such a device is more often than not a waste of time. If it's a valid bug in K-9 Mail someone else will open a new issue.

**Comment by NTICompass** [comment]
Ok, that's fine.  All xposed is doing is letting me use the "system webview" from the play store on my custom rom, but that may be an issue.
I reported this because it worked fine in 5.010, but not 5.113, so I thought maybe it was related to the pgp/mime updates.
