### ISSUE TITLE
K-9 mail crashes when trying to download an attachment

### ISSUE THREAD

**Issue by marmistrz** [thunderbird/thunderbird-android#1826]
I searched for a message containing a train ticket. I entered it and tried to save it. Then the app crashed.
The mail account used here was the same as in #1794 

### Environment
K-9 Mail version: 5.115
Android version: CM13

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

```
12-01 12:57:01.186 11371 11422 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
12-01 12:57:01.186 11371 11422 E AndroidRuntime: Process: com.fsck.k9, PID: 11371
12-01 12:57:01.186 11371 11422 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
12-01 12:57:01.186 11371 11422 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: Caused by: java.lang.IllegalStateException: No attachment data available
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalStore.getRawAttachmentInputStream(LocalStore.java:725)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalStore.access$100(LocalStore.java:66)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalStore$15.doDbWork(LocalStore.java:700)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalStore$15.doDbWork(LocalStore.java:684)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalStore.getAttachmentInputStream(LocalStore.java:684)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.provider.AttachmentProvider.getAttachmentInputStream(AttachmentProvider.java:186)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.provider.AttachmentProvider.openAttachment(AttachmentProvider.java:167)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.provider.AttachmentProvider.openFile(AttachmentProvider.java:78)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentProvider.openAssetFile(ContentProvider.java:1374)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1554)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1620)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:419)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1107)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:944)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:664)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.AttachmentController.writeAttachmentToStorage(AttachmentController.java:149)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.AttachmentController.saveAttachmentWithUniqueFileName(AttachmentController.java:141)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.AttachmentController.access$900(AttachmentController.java:42)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.AttachmentController$SaveAttachmentAsyncTask.doInBackground(AttachmentController.java:348)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.AttachmentController$SaveAttachmentAsyncTask.doInBackground(AttachmentController.java:337)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-01 12:57:01.186 11371 11422 E AndroidRuntime: 	... 3 more
12-01 12:57:01.190  1350  1883 W ActivityManager:   Force finishing activity com.fsck.k9/.activity.Search
```

**Comment by Valodim** [comment]
Got this one fixed, our attachment provider structure really wasn't prepared to deal with multipart/* parts for attachments. Thanks for your report!
