### ISSUE TITLE
Crash: NPE in Address.hashCode()

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#1874]
Via Play Developer Console
App version: 5.200

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at com.fsck.k9.mail.Address.hashCode(Address.java:176)
	at java.util.Collections.secondaryHash(Collections.java:3405)
	at java.util.LinkedHashMap.get(LinkedHashMap.java:250)
	at android.support.v4.util.LruCache.get(LruCache.java:84)
	at com.fsck.k9.activity.misc.ContactPictureLoader.getBitmapFromCache(ContactPictureLoader.java:213)
	at com.fsck.k9.activity.misc.ContactPictureLoader.loadContactPicture(ContactPictureLoader.java:133)
	at com.fsck.k9.activity.compose.RecipientAdapter.setContactPhotoOrPlaceholder(RecipientAdapter.java:137)
	at com.fsck.k9.view.RecipientSelectView.bindObjectView(RecipientSelectView.java:128)
	at com.fsck.k9.view.RecipientSelectView.getViewForObject(RecipientSelectView.java:112)
	at com.fsck.k9.view.RecipientSelectView.buildSpanForObject(RecipientSelectView.java:437)
	at com.fsck.k9.view.RecipientSelectView.buildSpanForObject(RecipientSelectView.java:47)
	at com.tokenautocomplete.TokenCompleteTextView.insertSpan(TokenCompleteTextView.java:1031)
	at com.tokenautocomplete.TokenCompleteTextView.access$700(TokenCompleteTextView.java:54)
	at com.tokenautocomplete.TokenCompleteTextView$3.run(TokenCompleteTextView.java:924)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5930)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

**Comment by zhangxiaofan918** [comment]
another question,do you know how to show forward icon in message list all the time?

**Comment by philipwhiuk** [comment]
`Address` assumes (somewhat validly) that `mAddress` will not be null. But it's never actually checked. `Address`s constructors should probably throw if null is passed in as the address.

**Comment by cketti** [comment]
We can fix that in a proper email address overhaul. For now supporting `Address` instances without email address is something we intentionally support. See  https://github.com/k9mail/k-9/blob/b2ed230b322277f6e366fc3f1510043ccba45836/k9mail-library/src/test/java/com/fsck/k9/mail/AddressTest.java#L15-L26
