### ISSUE TITLE
Crash: NPE in MessageList.decodeExtras()

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#1875]
Via Play Developer Console
App version: 5.200

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
	at com.fsck.k9.activity.MessageList.decodeExtras(MessageList.java:485)
	at com.fsck.k9.activity.MessageList.onNewIntent(MessageList.java:258)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1212)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1224)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2545)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2557)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2566)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1416)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by philipwhiuk** [comment]
```
        // now we know if we are in single account mode and need a subtitle
        mActionBarSubTitle.setVisibility((!mSingleFolderMode) ? View.GONE : View.VISIBLE);
```

Maybe in "single accountMode" `mActionBarSubTitle` isn't even created?

**Comment by philipwhiuk** [comment]
This is another case of `finish();` not cleaning up properly. In onCreate we call `finish(); return;` before we create the sub title. Cleaning up in the same way as #1907 should work.
