### ISSUE TITLE
Crash: OOM during migration

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#1879]
Via Play Developer Console
App version: 5.200

```
java.lang.OutOfMemoryError: Failed to allocate a 2060 byte allocation with 1974 free bytes and 1974B until OOM
	at org.apache.james.mime4j.stream.MimeEntity.advanceToBoundary(MimeEntity.java:387)
	at org.apache.james.mime4j.stream.MimeEntity.advance(MimeEntity.java:331)
	at org.apache.james.mime4j.stream.MimeTokenStream.next(MimeTokenStream.java:360)
	at org.apache.james.mime4j.parser.MimeStreamParser.parse(MimeStreamParser.java:176)
	at com.fsck.k9.mail.message.MessageHeaderParser.parse(MessageHeaderParser.java:24)
	at com.fsck.k9.mailstore.LocalMessage.populateFromGetMessageCursor(LocalMessage.java:127)
	at com.fsck.k9.mailstore.LocalStore$13.doDbWork(LocalStore.java:638)
	at com.fsck.k9.mailstore.LocalStore$13.doDbWork(LocalStore.java:615)
	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
	at com.fsck.k9.mailstore.LocalStore.getMessages(LocalStore.java:615)
	at com.fsck.k9.mailstore.LocalFolder$10.doDbWork(LocalFolder.java:880)
	at com.fsck.k9.mailstore.LocalFolder$10.doDbWork(LocalFolder.java:875)
	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
	at com.fsck.k9.mailstore.LocalFolder.getMessages(LocalFolder.java:875)
	at com.fsck.k9.mailstore.migrations.MigrationTo55.createFtsSearchTable(MigrationTo55.java:36)
	at com.fsck.k9.mailstore.migrations.Migrations.upgradeDatabase(Migrations.java:66)
	at com.fsck.k9.mailstore.StoreSchemaDefinition.upgradeDatabase(StoreSchemaDefinition.java:60)
	at com.fsck.k9.mailstore.StoreSchemaDefinition.doDbUpgrade(StoreSchemaDefinition.java:36)
	at com.fsck.k9.mailstore.LockableDatabase.openOrCreateDataspace(LockableDatabase.java:381)
	at com.fsck.k9.mailstore.LockableDatabase.open(LockableDatabase.java:354)
	at com.fsck.k9.mailstore.LocalStore.<init>(LocalStore.java:210)
	at com.fsck.k9.mailstore.LocalStore.getInstance(LocalStore.java:235)
	at com.fsck.k9.Account.getLocalStore(Account.java:1278)
	at com.fsck.k9.controller.MessagingController.setupPushing(MessagingController.java:4322)
	at com.fsck.k9.service.MailService.setupPushers(MailService.java:349)
	at com.fsck.k9.service.MailService.reschedulePushers(MailService.java:338)
	at com.fsck.k9.service.MailService.access$100(MailService.java:24)
	at com.fsck.k9.service.MailService$1.run(MailService.java:194)
	at com.fsck.k9.service.CoreService$1.run(CoreService.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by philipwhiuk** [comment]
We create a list of all the messages then free the space when we migrate each.

There's a comment which implies thought has been put into the approach:

'// The LocalMessage objects are heavy once they have been loaded, so we free them asap'

But that only helps if it's actually possible to fit all the messages into memory.

We need to re-approach this migration so that we aren't loading all the messages from a folder at once. Perhaps batching

If it takes longer to migrate when we do it batched then we might need to look at displaying some UI while the app's DB migration occurs.

**Comment by Valodim** [comment]
Only the message metadata is loaded, the message content is not kept around for long, that's what the `remove` is for. But that seems to be too much already.

Attempted fix: only keep message uids around. Still needs testing, gonna do that in a second.
