### ISSUE TITLE
Badly formatted MIME prevents email from syncing

### ISSUE THREAD

**Issue by vsound99** [thunderbird/thunderbird-android#1959]
### Expected behavior
New e-mail should show in Inbox

### Actual behavior
Get an "IllegalArgumentException" error

### Steps to reproduce
1. Check Mail
2.
3.

### Environment
K-9 Mail version: 5.201

Android version:  6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

This happens on all of my accounts after the new K-9 Mail update.

**Comment by philipwhiuk** [comment]
If you enable debugging in the app is there are corresponding 'email' in the k9mail-errors folder for the account.

Can you provide the content of that 'email'.

**Comment by vsound99** [comment]
K9-Mail version: 5.201
Device make: samsung
Device model: SM-N910P
Android version: 6.0.1

java.lang.IllegalArgumentException: The value of 'raw' needs to start with the supplied field name followed by a colon
        at com.fsck.k9.mail.internet.MimeHeader$Field.newRawField(MimeHeader.java:174)
        at com.fsck.k9.mail.internet.MimeHeader.addRawHeader(MimeHeader.java:41)
        at com.fsck.k9.mail.internet.MimeMessage.addRawHeader(MimeMessage.java:390)
        at com.fsck.k9.mail.internet.MimeMessage$MimeMessageBuilder.field(MimeMessage.java:581)
        at org.apache.james.mime4j.parser.MimeStreamParser.parse(MimeStreamParser.java:153)
        at com.fsck.k9.mail.internet.MimeMessage.parse(MimeMessage.java:107)
        at com.fsck.k9.mail.internet.MimeMessage.parse(MimeMessage.java:77)
        at com.fsck.k9.mail.store.pop3.Pop3Store$Pop3Folder.fetchBody(Pop3Store.java:951)
        at com.fsck.k9.mail.store.pop3.Pop3Store$Pop3Folder.fetch(Pop3Store.java:816)
        at com.fsck.k9.controller.MessagingController.downloadSmallMessages(MessagingController.java:1393)
        at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1196)
        at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:953)
        at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
        at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
        at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
        at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
        at java.lang.Thread.run(Thread.java:818)

 

 

Joe Vaccaro

**Comment by philipwhiuk** [comment]
Thanks! Looks like there's something wrong with one specific message's header. Could you provide the source of the (first?) message that isn't being displayed in K-9?

**Comment by vsound99** [comment]
What e-mail message are you referring to? 



Joe Vaccaro
V-Sound Productions
(919) 367-7217
 <mailto:joevaccaro@vsoundproductions.com> joevaccaro@vsoundproductions.com
 <http://www.vsoundproductions.com/> www.vsoundproductions.com

**Comment by philipwhiuk** [comment]
One of the emails you have been sent but not received in K-9 has an invalid header. I suspect it's the earliest one that hasn't arrived.

**Comment by vsound99** [comment]
I deleted some emails through my webmail on my pc and then checked my mail on my phone in k9 mail. Working fine now. Thanks. 


-------- Original Message --------

**Comment by philipwhiuk** [comment]
I wonder if it would be smarter to just log and drop bad single fields rather than block sync. No it's not standards-compliant but breaking someone's email because one spammer is bad is not great.

**Comment by cketti** [comment]
I'd rather mark the message as "unable to parse" and skip it. We should have enough meta data to still show it in the message list so users can delete it.

**Comment by steveday72** [comment]
I'm also having the same problem frequently.

I have signed up to GitHub just to report this frequent annoying issue. I'm sure the messages are coming for a single spammers. But I'm getting one every other day - which prevents me from syncing my email until I log into the webmail app to track down the offending email and delete it manually.

Two emails are attached which caused the error. They both verified as being MIME compliant via the online tool at mimevalidator.net


[k9-problem-email-1.txt](https://github.com/k9mail/k-9/files/712709/k9-problem-email-1.txt)
[k9-problem-email-2.txt](https://github.com/k9mail/k-9/files/712710/k9-problem-email-2.txt)

**Comment by philipwhiuk** [comment]
@steveday72 Neither of those are the email source :(. They are just links to emails behind a login.

**Comment by steveday72** [comment]
I've never used GitHub before, but managed to find where I could pull the latest build (5.203) and install it. I used my webmail site to copy the problem emails back into the inbox. The new installation downloaded/synced them without a problem. The syncing process seemed a little faster too (watching the message numbers compared to before).

Thank you for fixing it!

Philipwhiuk - I used the GitHub message composer (the same one I'm using to reply here) to attach the files from my tablet. It uploaded them and worked when I clicked on them.

**Comment by philipwhiuk** [comment]
All I get is a file with `https://mail4.hostica.com/horde/imp/view.php?popup_view=1&mailbox=INBOX.Problem-Mails&index=2&actionID=view_source&id=0&mimecache=90ffdf912a4cb70f741b0d9c5b27d184` :(

**Comment by steveday72** [comment]
Fixed them. Sorry.

I assumed that "Sharing" a web page from Chrome->Total Commander would share the content and not just the URL.

**Comment by Valodim** [comment]
This issue is the same as the one fixed in #1976, it will be fixed when the next bugfix release is out. This is also already released in our [alpha channel](https://play.google.com/apps/testing/com.fsck.k9).
