### ISSUE TITLE
POP3 mail synchronization errors

### ISSUE THREAD

**Issue by snyderco** [thunderbird/thunderbird-android#1998]
### Expected behavior
Prior to the last 2 updates, K-9 fetched pop3 email with no problem.

### Actual behavior
Now I receive an error.  See bug report below:
K9-Mail version: 5.202
Device make: samsung
Device model: SM-G900P
Android version: 6.0.1

com.fsck.k9.mail.MessagingException: Unable to execute POP3 command
	at com.fsck.k9.mail.store.pop3.Pop3Store$Pop3Folder.executeSimpleCommand(Pop3Store.java:1157)
	at com.fsck.k9.mail.store.pop3.Pop3Store$Pop3Folder.executeSimpleCommand(Pop3Store.java:1127)
	at com.fsck.k9.mail.store.pop3.Pop3Store$Pop3Folder.fetchEnvelope(Pop3Store.java:881)
	at com.fsck.k9.mail.store.pop3.Pop3Store$Pop3Folder.fetch(Pop3Store.java:804)
	at com.fsck.k9.controller.MessagingController.fetchUnsyncedMessages(MessagingController.java:1319)
	at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1164)
	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:953)
	at com.fsck.k9.controller.MessagingController$36.run(MessagingController.java:4010)
	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: End of stream reached while trying to read line.
	at com.fsck.k9.mail.store.pop3.Pop3Store$Pop3Folder.readLine(Pop3Store.java:1030)
	at com.fsck.k9.mail.store.pop3.Pop3Store$Pop3Folder.executeSimpleCommand(Pop3Store.java:1147)
	... 11 more

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by snyderco** [comment]
Also:
K9-Mail version: 5.202
Device make: samsung
Device model: SM-G900P
Android version: 6.0.1

com.fsck.k9.mail.MessagingException: Folder does not exist
	at com.fsck.k9.mail.store.pop3.Pop3Store$Pop3Folder.open(Pop3Store.java:318)
	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:845)
	at com.fsck.k9.controller.MessagingController$36.run(MessagingController.java:4010)
	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
	at java.lang.Thread.run(Thread.java:818)

**Comment by philipwhiuk** [comment]
Unfortunately I think we'll need a full ADB debug log to figure what's going on here.

**Comment by snyderco** [comment]
I m not sure what that is.  If you can tell me what that is and how to access it, I may be able to provide it.
Thanks.

**Comment by philipwhiuk** [comment]
See: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by snyderco** [comment]
[k9-log.txt](https://github.com/k9mail/k-9/files/692599/k9-log.txt)

I have attached the ADB log file.  Can you please verify for me that my login name and password are not in the file?  I did a search, but I am new to this.
Thanks

**Comment by philipwhiuk** [comment]
There's no login name or password. But there's no actual K-9 activity in there at all :( The only mention of K-9 is in package listings. Can you try to run the log while syncing your email and upload that?

**Comment by snyderco** [comment]
How about this one?
[k9-log.txt](https://github.com/k9mail/k-9/files/692639/k9-log.txt)

**Comment by philipwhiuk** [comment]
Yep there's definitely some stuff in there to look at. Thanks - I'll take a look.

**Comment by snyderco** [comment]
Any further progress on this issue?

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with the latest K-9 Mail version.
