### ISSUE TITLE
Crash: NPE in MessageTitleView.showSubjectInMessageHeader()

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#2010]
Via Play Developer Console
Version: 5.202

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.fsck.k9.view.MessageHeader.showSubjectLine()' on a null object reference
	at com.fsck.k9.view.MessageTitleView.showSubjectInMessageHeader(MessageTitleView.java:67)
	at com.fsck.k9.activity.MessageList.displayMessageSubject(MessageList.java:1439)
	at com.fsck.k9.ui.messageview.MessageViewFragment.displayMessageSubject(MessageViewFragment.java:478)
	at com.fsck.k9.ui.messageview.MessageViewFragment.displayHeaderForLoadingMessage(MessageViewFragment.java:249)
	at com.fsck.k9.ui.messageview.MessageViewFragment.access$400(MessageViewFragment.java:55)
	at com.fsck.k9.ui.messageview.MessageViewFragment$5.onMessageDataLoadFinished(MessageViewFragment.java:718)
	at com.fsck.k9.activity.MessageLoaderHelper.onLoadMessageFromDatabaseFinished(MessageLoaderHelper.java:196)
	at com.fsck.k9.activity.MessageLoaderHelper.access$500(MessageLoaderHelper.java:69)
	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:244)
	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:224)
	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:488)
	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:456)
	at android.content.Loader.deliverResult(Loader.java:144)
	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:44)
	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:16)
	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:265)
	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5624)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

**Comment by philipwhiuk** [comment]
So this is probably caused by the code in #1955 

The problem, I think is that the `MessageTitleView` hasn't been told the header at this point.

We have the following structure:

MessageViewFragment
-mMessageView: MessageTopView
-mFragmentListener: MessageList
- mActionBarSubject: MessageTitleView
-- mHeader: MessageHeader

One option is to pass the header to the MessageTitleView in MessageViewFragment just before we call showSubjectInMessageHeader.

`mFragmentListener.messageHeaderViewAvailable(mMessageView.getMessageHeaderView());`

I have a 2-line commit for this. It's all a bit ugly really though and the original fix was also ugly: https://github.com/philipwhiuk/k-9/commit/aaf271f2246c388aecb92e7a1984e4b3dd603ac6

I think we need to rethink this forest of components a bit.

**Comment by TheBlueMatt** [comment]
This is easily reproduceable for me my selecting an email and then immediately pressing the back button...seems there is a race if you get to the prior screen before the email ever got a chance to load.
