### ISSUE TITLE
IndexOutOfBoundsException on opening multipart/signed object with stripped signature

### ISSUE THREAD

**Issue by Hawk777** [thunderbird/thunderbird-android#2225]
I sent a multipart/signed message to a mailing list. The mailing list decided to strip out the MIME part containing the signature. On opening the message in K9, I get a crash with the following backtrace:

```
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.fsck.k9.mail.Multipart.getBodyPart(Multipart.java:24)
	at com.fsck.k9.crypto.MessageDecryptVerifier.getSignatureData(MessageDecryptVerifier.java:155)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.callAsyncDetachedVerify(MessageCryptoHelper.java:352)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptVerify(MessageCryptoHelper.java:260)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptOrVerifyPart(MessageCryptoHelper.java:238)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.startDecryptingOrVerifyingPart(MessageCryptoHelper.java:204)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptOrVerifyNextPart(MessageCryptoHelper.java:197)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$200(MessageCryptoHelper.java:58)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper$1.onBound(MessageCryptoHelper.java:219)
	at org.openintents.openpgp.util.OpenPgpServiceConnection$1.onServiceConnected(OpenPgpServiceConnection.java:81)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1224)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1241)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

The message should obviously not be reported as signed, but it shouldn’t crash the program either.

The MIME structure of the final message is as follows. The content-type of the message as a whole is multipart/mixed. This outer MIME layer has two parts, which I will call parts 1 and 2. Part 1 is of content-type multipart/signed. Part 1’s MIME content has one part, which I will call part 1.1. Part 1.1. is of content-type text/plain and contains my original message. Part 2 is of content-type text/plain and contains a small signature tacked on by the mailing list. All the boundary strings are properly formatted as far as I can tell.

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Hawk777** [comment]
In 5.800 this appears to no longer happen.
