### ISSUE TITLE
Crash in 5.205: Bug in ParcelableUtil.unmarshall()?

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#2282]
Crash reported via Google Play.

User messages:
* crash when opening from 1x1 widget
* using inbox icon to start k9 results in crash
* force closes on start from widget

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9/com.fsck.k9.activity.MessageList}: java.lang.NullPointerException: Attempt to get length of null array
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
	at android.app.ActivityThread.access$1100(ActivityThread.java:221)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at com.fsck.k9.helper.ParcelableUtil.unmarshall(ParcelableUtil.java:27)
	at com.fsck.k9.helper.ParcelableUtil.unmarshall(ParcelableUtil.java:19)
	at com.fsck.k9.activity.MessageList.decodeExtras(MessageList.java:437)
	at com.fsck.k9.activity.MessageList.onCreate(MessageList.java:225)
	at android.app.Activity.performCreate(Activity.java:6876)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
	... 9 more
```

**Comment by cketti** [comment]
The widgets/shortcuts might have persisted Intents with extras in the old format. If that's the case we should probably show a message telling users to re-add the widget/shortcut.

**Comment by github-user-1** [comment]
I had the same issue - removing and re-adding the widget solved the problem. I only got aware of this option here when I wanted to open a ticket. So a hint to users is required I think!
