### ISSUE TITLE
IMAP Synchronization breaks when server responds with BYE after timeout.

### ISSUE THREAD

**Issue by Larsen-O** [thunderbird/thunderbird-android#2665]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Synchronizing my Newsletter-Folder

### Actual behavior
Error: IOException: readStringUnti

Sometimes the App stops so that I have to stop
[k9-log4.txt](https://github.com/k9mail/k-9/files/1203039/k9-log4.txt)

it and restart.
The other folders are able to synchronize.

Log-File attached.

### Steps to reproduce
1. See appended Logfile.
2.
3.

### Environment
K-9 Mail version: 5.207

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange):

IMAP

**Comment by philipwhiuk** [comment]
We're receiving `BYE` in response to a search for undeleted messages as part of the sync.

The problem here is:

1. We can't automatically know why we timed out.


```
8-06 13:13:46.807 V/k9      (32643): conn70320695>>> 5 SEARCH 2633:3132 NOT DELETED
08-06 13:13:46.808 V/k9      (32643): conn70320695<<<#null# [BYE, timeout]
08-06 13:13:46.813 E/k9      (32643): synchronizeMailbox
08-06 13:13:46.813 E/k9      (32643): java.io.IOException: readStringUntil(): end of stream reached
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStringUntil(ImapResponseParser.java:447)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapResponseParser.parseTaggedResponse(ImapResponseParser.java:287)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readTaggedResponse(ImapResponseParser.java:75)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:44)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:30)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:88)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:634)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:620)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapFolder.existsNonDeletedMessageInRange(ImapFolder.java:574)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.mail.store.imap.ImapFolder.areMoreMessagesAvailable(ImapFolder.java:560)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.controller.MessagingController.updateMoreMessages(MessagingController.java:1033)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:945)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
08-06 13:13:46.813 E/k9      (32643): 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
08-06 13:13:46.813 E/k9      (32643): 	at java.lang.Thread.run(Thread.java:762)
```

Maybe instead of `checkOpen()` we should do `internalOpen()` at the start of `areMoreMessagesAvailable()` to guarantee we have a connection.

**Comment by philipwhiuk** [comment]
The tests I added don't fix this - it was just work done while looking at this.
