### ISSUE TITLE
NPE while trying to compose email from MessageList

### ISSUE THREAD

**Issue by lingling-fan** [thunderbird/thunderbird-android#2756]
package name: com.fsck.k9
    version: 5.205
    target sdk version: android-18
    java.lang.NullPointerException
        at com.fsck.k9.activity.compose.MessageActions.actionCompose(MessageActions.java:19)
        at com.fsck.k9.activity.MessageList.onCompose(MessageList.java:1265)
        at com.fsck.k9.fragment.MessageListFragment.onCompose(MessageListFragment.java:1016)
        at com.fsck.k9.activity.MessageList.onOptionsItemSelected(MessageList.java:800)
        at android.app.Activity.onMenuItemSelected(Activity.java:2566)
        at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:986)
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:742)
         at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:881)
        at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:547)
        at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:115)
        at android.view.View.performClick(View.java:4240)
        at android.view.View.onKeyUp(View.java:7928)
        at android.widget.TextView.onKeyUp(TextView.java:5552)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2647)
        at android.view.View.dispatchKeyEvent(View.java:7343)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1933)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1408)
        at android.app.Activity.dispatchKeyEvent(Activity.java:2384)
        at com.fsck.k9.activity.MessageList.dispatchKeyEvent(MessageList.java:567)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1860)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3791)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3774)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3516)
 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3666)
 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:1982)
 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1698)
 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1689)
 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1959)
 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
 	at android.os.MessageQueue.nativePollOnce(Native Method)
 	at android.os.MessageQueue.next(MessageQueue.java:132)
 	at android.os.Looper.loop(Looper.java:124)

**Comment by philipwhiuk** [comment]
https://github.com/k9mail/k-9/blob/5.205/k9mail/src/main/java/com/fsck/k9/activity/compose/MessageActions.java#L19

Composition while viewing with message list with no default account?

https://github.com/k9mail/k-9/blob/5.205/k9mail/src/main/java/com/fsck/k9/fragment/MessageListFragment.java#L1010-L1020
