### ISSUE TITLE
IndexOutOfBounds with Multipart/Signed with only 1 part

### ISSUE THREAD

**Issue by ximex** [thunderbird/thunderbird-android#2758]
### Expected behavior
Should see the Email

### Actual behavior
App crashes

### Steps to reproduce
Open a specific Email (I only have one Email where this happens)
This Email has no attachment

### Environment
K-9 Mail version: 5.208
Android version: 7.1.2 (LineageOS)
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Log:
```
09-11 17:32:50.135 D/k9      (31893): MessageView displaying message MessageReference{accountUuid='b213f70e-f05f-4d42-b37c-6ccb377537d0', folderName='INBOX', uid='701', flag=null}
09-11 17:32:50.135 D/k9      (31893): Creating new local message loader
09-11 17:32:50.477 E/AndroidRuntime(31893): FATAL EXCEPTION: main
09-11 17:32:50.477 E/AndroidRuntime(31893): Process: com.fsck.k9, PID: 31893
09-11 17:32:50.477 E/AndroidRuntime(31893): java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at java.util.ArrayList.get(ArrayList.java:411)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.fsck.k9.mail.Multipart.getBodyPart(Multipart.java:24)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.fsck.k9.crypto.MessageDecryptVerifier.getSignatureData(MessageDecryptVerifier.java:202)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.callAsyncDetachedVerify(MessageCryptoHelper.java:352)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptVerify(MessageCryptoHelper.java:260)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptOrVerifyPart(MessageCryptoHelper.java:238)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.startDecryptingOrVerifyingPart(MessageCryptoHelper.java:204)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptOrVerifyNextPart(MessageCryptoHelper.java:197)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$200(MessageCryptoHelper.java:58)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper$1.onBound(MessageCryptoHelper.java:219)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at org.openintents.openpgp.util.OpenPgpServiceConnection$1.onServiceConnected(OpenPgpServiceConnection.java:81)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at android.os.Handler.handleCallback(Handler.java:751)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at android.os.Looper.loop(Looper.java:154)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at java.lang.reflect.Method.invoke(Native Method)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-11 17:32:50.477 E/AndroidRuntime(31893): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by philipwhiuk** [comment]
This looks like an invalid email format - multipart/signed, with only 1 part.

Can you provide the structure of the email (i.e. just the headers and not the actual content)?

I reckon maybe the right thing to do is check the size of the multi-part and if it's not 2, log and return null.

@Valodim - thoughts?

**Comment by Valodim** [comment]
*sigh yeah this one's on me. it was even mentioned in a review, I had thought the check was performed earlier but apparently it wasn't. I'll fix it.

Thanks for the report :+1:

**Comment by ximex** [comment]
@Valodim do you need the email header infos?

**Comment by ximex** [comment]
It's from a mailing list

**Comment by Valodim** [comment]
Couldn't hurt but, mailing lists will always do this kind of stuff. I made a PR to fix this problem on our side :)
