### ISSUE TITLE
Message count -1 for folder ...

### ISSUE THREAD

**Issue by ximex** [thunderbird/thunderbird-android#2765]
I often get this error in the "K9mail-errors" folder.

K9-Mail version: 5.208
Device make: LGE
Device model: Nexus 4
Android version: 7.1.2

```
java.lang.Exception: Message count -1 for folder Entwürfe
 at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:913)
 at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
 at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
 at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
 at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
 at java.lang.Thread.run(Thread.java:761)
```

**Comment by philipwhiuk** [comment]
I thought I'd fixed most of these, but I've seen a case where this can happen having just looked.

**Comment by Etua** [comment]
I experienced it on my OPO, K-9 and Android version are the same. I hope that will be fixed by that pull request.
