### ISSUE TITLE
End of stream reached while trying to read IDLE request response

### ISSUE THREAD

**Issue by ximex** [thunderbird/thunderbird-android#2766]
I often get this error in the "K9mail-errors" folder.

K9-Mail version: 5.208
Device make: LGE
Device model: Nexus 4
Android version: 7.1.2

```
java.io.IOException: readStringUntil(): end of stream reached
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStringUntil(ImapResponseParser.java:447)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.parseTaggedResponse(ImapResponseParser.java:287)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readTaggedResponse(ImapResponseParser.java:75)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:44)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:30)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:88)
	at com.fsck.k9.mail.store.imap.ImapConnection.readStatusResponse(ImapConnection.java:643)
	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.sendIdle(ImapFolderPusher.java:310)
	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.run(ImapFolderPusher.java:188)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by gpe5280** [comment]
FWIW, I was receiving the same error. However, checking the postfix logs on the mail server showed an error with dovecot. Specifically, the `mail_max_userip_connections` setting for the imap protocol needed to be increased (defaults to 10.) After setting that value to 20 and restarting dovecot, the error was resolved. It has been about 12 hours since making this change and so far the issue hasn't returned.
