### ISSUE TITLE
Parsing email address list with invalid base64 encoded word crashes the app

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#2846]
Test case:
```java
Address.parse("=?utf-8?b?invalid#?= <oops@example.com>");
```

Exception:
```
java.lang.Error: java.io.IOException: Unexpected base64 byte

	at org.apache.james.mime4j.codec.DecoderUtil.decodeBase64(DecoderUtil.java:89)
	at org.apache.james.mime4j.codec.DecoderUtil.decodeB(DecoderUtil.java:106)
	at org.apache.james.mime4j.codec.DecoderUtil.tryDecodeEncodedWord(DecoderUtil.java:233)
	at org.apache.james.mime4j.codec.DecoderUtil.decodeEncodedWords(DecoderUtil.java:187)
	at org.apache.james.mime4j.codec.DecoderUtil.decodeEncodedWords(DecoderUtil.java:143)
	at org.apache.james.mime4j.field.address.Builder.buildAddress(Builder.java:71)
	at org.apache.james.mime4j.field.address.Builder.buildAddressList(Builder.java:51)
	at org.apache.james.mime4j.field.address.DefaultAddressParser.parseAddressList(DefaultAddressParser.java:69)
	at org.apache.james.mime4j.field.address.DefaultAddressParser.parseAddressList(DefaultAddressParser.java:73)
	at com.fsck.k9.mail.Address.parse(Address.java:145)
        [...]
Caused by: java.io.IOException: Unexpected base64 byte
	at org.apache.james.mime4j.codec.Base64InputStream.read0(Base64InputStream.java:193)
	at org.apache.james.mime4j.codec.Base64InputStream.read(Base64InputStream.java:87)
	at org.apache.james.mime4j.codec.DecoderUtil.decodeBase64(DecoderUtil.java:80)
        ... 39 more
```

I'm not sure what the best way to handle this is. Probably using the personal part as is. However, the options in MIME4J are somewhat limited. It's either crashing with an `Error` or ignoring invalid characters when decoding the base64 payload. Since we don't like crashes we should probably start out with the latter option.

**Comment by PammyS** [comment]
@cketti  I will be happy to take this! please assign it to me

**Comment by cketti** [comment]
@PammyS: Issues can only be assigned to project members. But the fact that you're attempting to fix this issue is hereby noted :)

**Comment by jyn514** [comment]
@cketti to clarify: When you say ignore invalid characters, do you want to treat the whole thing like an ASCII string, or selectively remove characters that aren't base64? If we do the second, we might end up with garbage.

**Comment by cketti** [comment]
The base64 decoders in MIME4J have a STRICT mode that is currently used, hence the crash. Using SILENT mode instead will just skip over invalid characters when decoding base64-encoded data.

**Comment by jyn514** [comment]
Huh, this got harder than I thought. When I use LenientAddressParser.Default to parse, this particular case works, but the other test cases fail. I'm looking further into it.

**Comment by cketti** [comment]
What about this?

```java
AddressBuilder.DEFAULT.parseAddressList(addressList, DecodeMonitor.SILENT);
```

**Comment by jyn514** [comment]
That works! Thank you so much :D
