### ISSUE TITLE
ClassCastException when syncing (folderImapList cannot be cast to java.lang.String)

### ISSUE THREAD

**Issue by caugner** [thunderbird/thunderbird-android#2966]
### Expected behavior

I try to sync one specific account/folder. 

### Actual behavior

It doesn't sync and displays "ClassCastException" under the the name of the folder. 

### Steps to reproduce
1. Open inbox. 
2. Swipe down (which refreshes).
3. Go to folder overview.

### Environment
K-9 Mail version: 5.208

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

After enabling extended error logging I get this :

```
K9-Mail version: 5.208
Device make: Fairphone
Device model: FP2
Android version: 7.1.2

java.lang.ClassCastException: com.fsck.k9.mail.store.imap.ImapList cannot be cast to java.lang.String
 at com.fsck.k9.mail.store.imap.ImapList.getString(ImapList.java:36)
 at com.fsck.k9.mail.store.imap.ImapFolder.parseBodyStructure(ImapFolder.java:1037)
 at com.fsck.k9.mail.store.imap.ImapFolder.handleFetchResponse(ImapFolder.java:902)
 at com.fsck.k9.mail.store.imap.ImapFolder.fetch(ImapFolder.java:754)
 at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1468)
 at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1201)
 at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:951)
 at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
 at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
 at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
 at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
 at java.lang.Thread.run(Thread.java:761)
```

**Comment by caugner** [comment]
When I reduce the number of synchronised messages to 10, it works, so it looks like there is an invalid message. I will try to figure out which one it is in order to reproduce it with a test.

**Comment by cketti** [comment]
If you can access your phone via `adb`, enable debug logging and the log should contain the server response that triggers the error. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by philipwhiuk** [comment]
I wonder if the IMAP server is not correctly obeying the spec and skipping a missing subType. Anyway I've written a test to validate the existing behaviour against the RFC.
