### ISSUE TITLE
App crashes when I click on contact logo

### ISSUE THREAD

**Issue by thefrenchlawyer** [thunderbird/thunderbird-android#3129]
Hi,
I've not found a recent issue related to my issue.

Thanks for your answer

### Expected behavior
It should be create a new message with the clicked contact, as recipient.

### Actual behavior
Since the update, the app crashes when I click on contact logo square.

### Steps to reproduce
1. Open the app
2. Click on the logo square of any email
3. The app will crash

### Environment
K-9 Mail version: 5.403

Android version: 5.1 with Flyme 6.2.0.0A

Account type (IMAP, POP3, WebDAV/Exchange): IMAP with Gmail

**Comment by philipwhiuk** [comment]
Can you provide a debug log. It seems likely that this is related to Flyme and this is going to be difficult to reproduce and fix without one as a result.

**Comment by thefrenchlawyer** [comment]
Thanks for your answer.
[k9-log.txt](https://github.com/k9mail/k-9/files/1662179/k9-log.txt)

**Comment by philipwhiuk** [comment]
Thanks.

Tapping the badge is supposed to open the contacts app. You don't have one and we handle that badly.

So it's not your ROMs fault exactly, but it probably only happens on a custom ROM because not having the contacts app is pretty rare.

```
01-25 01:44:28.847 E/AndroidRuntime(18920): FATAL EXCEPTION: main

01-25 01:44:28.847 E/AndroidRuntime(18920): Process: com.fsck.k9, PID: 18920

01-25 01:44:28.847 E/AndroidRuntime(18920): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.android.contacts.action.SHOW_OR_CREATE_CONTACT dat=mailto:xxxxxxxxx@xxxxxxx.xxxxxx.xx (has extras) }

01-25 01:44:28.847 E/AndroidRuntime(18920): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1862)

01-25 01:44:28.847 E/AndroidRuntime(18920): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1582)

01-25 01:44:28.847 E/AndroidRuntime(18920): 	at android.app.Activity.startActivityForResult(Activity.java:3830)

01-25 01:44:28.847 E/AndroidRuntime(18920): 	at android.app.Activity.startActivityForResult(Activity.java:3787)

01-25 01:44:28.847 E/AndroidRuntime(18920): 	at android.app.Activity.startActivity(Activity.java:4139)

01-25 01:44:28.847 E/AndroidRuntime(18920): 	at android.app.Activity.startActivity(Activity.java:4069)

01-25 01:44:28.847 E/AndroidRuntime(18920): 	at com.fsck.k9.ui.ContactBadge$QueryHandler.onQueryComplete(ContactBadge.java:213)
```

**Comment by cketti** [comment]
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.android.contacts.action.SHOW_OR_CREATE_CONTACT dat=mailto:xxxxxxxxxxxxx@xxxxxx.xxx (has extras) }
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1862)
 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1582)
 	at android.app.Activity.startActivityForResult(Activity.java:3830)
 	at android.app.Activity.startActivityForResult(Activity.java:3787)
 	at android.app.Activity.startActivity(Activity.java:4139)
 	at android.app.Activity.startActivity(Activity.java:4069)
 	at com.fsck.k9.ui.ContactBadge$QueryHandler.onQueryComplete(ContactBadge.java:213)
 	at android.content.AsyncQueryHandler.handleMessage(AsyncQueryHandler.java:344)
 	at android.os.Handler.dispatchMessage(Handler.java:111)
 	at android.os.Looper.loop(Looper.java:194)
 	at android.app.ActivityThread.main(ActivityThread.java:5877)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

There's no contacts app with the required functionality installed. However, we can avoid the crash and simply do nothing in that case.

**Comment by cketti** [comment]
Note to implementers: Wrap the call to `startActivity()` in try/catch like we here: https://github.com/k9mail/k-9/blob/7c3b90b356ffe045c27b2ab5ceb0a4db3381a7b9/k9mail/src/main/java/com/fsck/k9/ui/messageview/MessageContainerView.java#L334-L340

**Comment by thefrenchlawyer** [comment]
Thanks for your answers.
Indeed, the ROM hasn't an individual contact app (it's included in phone app). So, I can't do nothing with that bug..
