### ISSUE TITLE
K9 crashed immediately by trying to decrypt a mail

### ISSUE THREAD

**Issue by webratte** [thunderbird/thunderbird-android#3215]
### Expected behavior
Mails should be decrypted

### Actual behavior
K9 crashed immediately by trying to decrypt

### Steps to reproduce
1. Open a encrypted (in my case not signed) mail
2. Enter the key password
3. The screen will be black for a second and nothing else happens

### Environment
K-9 Mail version: 5.500

Android version: 7.0 on a Huawei nova
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

I have enabled debug logging. Where can I found the logg file?

**Comment by webratte** [comment]
I forgott to mention.
I have also tryed deinstall - restart device - reinstall k9 without success.

**Comment by Valodim** [comment]
Well, shit.

```
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.openintents.openpgp.OpenPgpMetadata
at android.os.Parcel.readParcelableCreator(Parcel.java:2536)
at android.os.Parcel.readParcelable(Parcel.java:2462)
at android.os.Parcel.readValue(Parcel.java:2365)
at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
at android.os.BaseBundle.unparcel(BaseBundle.java:271)
at android.os.BaseBundle.getInt(BaseBundle.java:876)
at android.content.Intent.getIntExtra(Intent.java:6194)
at com.fsck.k9.ui.crypto.MessageCryptoHelper.handleCryptoOperationResult(MessageCryptoHelper.java:514)
at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoOperationReturned(MessageCryptoHelper.java:507)
at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$700(MessageCryptoHelper.java:58)
at com.fsck.k9.ui.crypto.MessageCryptoHelper$3.onReturn(MessageCryptoHelper.java:346)
at com.fsck.k9.ui.crypto.MessageCryptoHelper$3.onReturn(MessageCryptoHelper.java:335)
at org.openintents.openpgp.util.OpenPgpApi$OpenPgpSourceSinkAsyncTask.onPostExecute(OpenPgpApi.java:360)
at org.openintents.openpgp.util.OpenPgpApi$OpenPgpSourceSinkAsyncTask.onPostExecute(OpenPgpApi.java:339)
at android.os.AsyncTask.finish(AsyncTask.java:667)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6186)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

I don't think this is related to anything I did, seems more like a proguard issue.

**Comment by cketti** [comment]
Thanks for the report. v5.501 should fix the error and is available for download from GitHub and will be available via the Google Play alpha channel soon.

@Valodim was right. Proguard stripped the class because it was never directly referenced in code.

**Comment by webratte** [comment]
Thank you for fixing it so fast. 👍

I'm on beta channel.
Will it be there also available very soon?

**Comment by cketti** [comment]
For some reason Google Play is calling its alpha channel "beta channel" in the app. We're not using the beta channel :) So, yes. It'll be available via Google Play soon.

**Comment by webratte** [comment]
OK, thank you very much 😀
