### ISSUE TITLE
The app encountered an error while creating the account (IMAP) and crashed when clicking on the "write email" feature

### ISSUE THREAD

**Issue by ahyar92** [thunderbird/thunderbird-android#3401]
##### Expected behavior
Supposedly, the user can not enter the "Inbox" page without setting up the server and connecting it. Also, the write email feature should have no errors.

##### First problem
When I set up a new account by choosing an account type (IMAP), and after being on the server settings page, I accidentally exit the app, suddenly when I open the app again I'm already on the page "Inbox". Though I do not connect the server.

##### Second problem
And when I try to click the write email feature, suddenly the application crashes and exit by itself.

##### First problem
1. Install and open the app
2. Next go to the "Set up a new account"
3. Next fill in "Email address and Password"
4. Next click "Manual setup"
5. Next, select the account type "IMAP"
6. Once in the "Incoming server settings" page, please exit the application.
7. Next please log back into the application, then you will find the error as I experienced (*you will suddenly be at "Inbox"*)

##### Second problem
1. If you are already in the "Inbox" page, please click on the "Write email" feature. Then the application will crash and exit by itself. And when you try to log back in, the app returns to the page when it first installs.

----
- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version: 5.403

#### Recording Of The Bug 
https://www.youtube.com/watch?v=oaBseBOvwJY

#### Logcat
```
05-19 23:20:52.905 13739 13739 E AndroidRuntime: FATAL EXCEPTION: main
05-19 23:20:52.905 13739 13739 E AndroidRuntime: Process: com.fsck.k9, PID: 13739
05-19 23:20:52.905 13739 13739 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.fsck.k9/com.fsck.k9.activity.MessageCompose}; have you declared this activity in your AndroidManifest.xml?
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1801)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3978)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3939)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4262)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4230)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.fsck.k9.activity.compose.MessageActions.actionCompose(MessageActions.java:25)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.fsck.k9.activity.MessageList.onCompose(MessageList.java:1277)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.fsck.k9.fragment.MessageListFragment.onCompose(MessageListFragment.java:775)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.fsck.k9.activity.MessageList.onOptionsItemSelected(MessageList.java:812)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.app.Activity.onMenuItemSelected(Activity.java:2963)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1151)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:616)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:141)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.view.View.performClick(View.java:5207)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21177)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:742)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5527)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
05-19 23:20:52.905 13739 13739 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
