### ISSUE TITLE
connecting to server with invalid cert fails with no feedback whatsoever on current master

### ISSUE THREAD

**Issue by Valodim** [thunderbird/thunderbird-android#3459]
I think there used to be a notification about this problem, which allowed accepting the cert

```
    MessagingController  E  com.fsck.k9.mail.MessagingException: Unable to get folder list.                                                                               
                         E      at com.fsck.k9.mail.store.imap.ImapStore.getPersonalNamespaces(ImapStore.java:158)                                                        
                         E      at com.fsck.k9.controller.MessagingController.refreshRemoteSynchronous(MessagingController.java:438)                                      
                         E      at com.fsck.k9.controller.MessagingController$4.run(MessagingController.java:427)                                                         
                         E      at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:205)                                               
                         E      at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:118)                                                    
                         E      at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:174)                                                         
                         E      at java.lang.Thread.run(Thread.java:764)                                                                                                  
                         E  Caused by: com.fsck.k9.mail.CertificateValidationException: java.security.cert.CertPathValidatorException: Trust anchor for certification path 
                            not found.
                         E      at com.fsck.k9.mail.store.imap.ImapConnection.handleSslException(ImapConnection.java:168)                                                 
                         E      at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:153)                                                               
                         E      at com.fsck.k9.mail.store.imap.ImapConnection.sendCommand(ImapConnection.java:811)                                                        
                         E      at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:754)                                               
                         E      at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:743)                                               
                         E      at com.fsck.k9.mail.store.imap.ImapStore.listFolders(ImapStore.java:169)                                                                  
                         E      at com.fsck.k9.mail.store.imap.ImapStore.getPersonalNamespaces(ImapStore.java:145)                                                        
                         E      ... 6 more                                                                                                                                
                         E  Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. 
```

**Comment by poldi171254** [comment]
Can somebody please provide the steps to re-create this behaviour/problem?

**Comment by cketti** [comment]
Set up an IMAP server with a valid TLS certificate at the time you set up the account in K-9 Mail. Then change the certificate on the server to one that doesn't pass validation.
Refresh a folder in K-9 Mail. The folder sync will fail without any user-visible feedback.

**Comment by poldi171254** [comment]
I think a possible solution is similar to my proposal for #4202.
The issue is logged, but the user is not informed

**Comment by robsmith11** [comment]
I would think any errors that are not just failed to connect because of network issues should be displayed as an Android notification.

Maybe it would also be good to show the last successful sync time for a mail directory in the main UI.

**Comment by poldi171254** [comment]
Have checked this with 5.734-SNAPSHOT and looks like it's working as expected
![works](https://user-images.githubusercontent.com/43848359/118740730-f11d5e80-b88f-11eb-9f9a-d94f6d89fd9e.png)

**Comment by cketti** [comment]
Thanks!
