### ISSUE TITLE
k9 crashes with "intervalMs is out of range of [900000, 9223372036854775807] (too low)"

### ISSUE THREAD

**Issue by morckx** [thunderbird/thunderbird-android#3803]
### Expected behavior
K9 should not crash when folder poll intervals below 15 minutes are configured.

### Actual behavior
K9 crashes immediately with:

```
/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.fsck.k9.debug, PID: 7942
                  java.lang.IllegalArgumentException: intervalMs is out of range of [900000, 9223372036854775807] (too low)
                      at com.evernote.android.job.util.JobPreconditions.checkArgumentInRange(JobPreconditions.java:269)
                      at com.evernote.android.job.JobRequest$Builder.setPeriodic(JobRequest.java:1044)
                      at com.evernote.android.job.JobRequest$Builder.setPeriodic(JobRequest.java:1022)
                      at com.fsck.k9.job.MailSyncJobManager.scheduleJob(MailSyncJobManager.kt:29)
                      at com.fsck.k9.job.K9JobManager.scheduleMailSync(K9JobManager.kt:32)
                      at com.fsck.k9.ui.settings.account.AccountSettingsDataStore.reschedulePoll(AccountSettingsDataStore.kt:218)
                      at com.fsck.k9.ui.settings.account.AccountSettingsDataStore.putString(AccountSettingsDataStore.kt:163)
                      at android.support.v7.preference.Preference.persistString(Preference.java:1575)
                      at android.support.v7.preference.ListPreference.setValue(ListPreference.java:156)
                      at android.support.v7.preference.ListPreferenceDialogFragmentCompat.onDialogClosed(ListPreferenceDialogFragmentCompat.java:129)
                      at android.support.v7.preference.PreferenceDialogFragmentCompat.onDismiss(PreferenceDialogFragmentCompat.java:264)
                      at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1393)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:201)
                      at android.app.ActivityThread.main(ActivityThread.java:6806)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

```

### Steps to reproduce
1. Open account settings
2. Set folder poll frequency to 10 minutes

### Environment
K-9 Mail version: 4a342435e38fce5dc4209db12293c730c9092199

Android version: 9.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
As a short term fix we should prevent changing the interval below 15 minutes on Nougat per https://github.com/evernote/android-job/wiki/FAQ

**Comment by Valodim** [comment]
Ugh. I feel like we'll regularly get tickets "allow smaller polling interval than 15 minutes". But there's little we can do, I guess.

**Comment by philipwhiuk** [comment]
Yeah, we'll need to make it obvious in the UI that it's a OS restriction.

**Comment by wiktor-k** [comment]
From my casual reading of the FAQ it seems the library choose to *never* support intervals lower than 15 mins to provide a consistent experience on all systems. Fair enough, I like the "short term fix" (as crashing is worse than people not liking an option :) ).

**Comment by philipwhiuk** [comment]
> Yeah, we'll need to make it obvious in the UI that it's a OS restriction.

I still think this needs to be done.

**Comment by wiktor-k** [comment]
> I still think this needs to be done.

Do you have a suggestion on how this could be displayed? K-9 has a large user base of technical users that would understand the distinction but normal users would probably consider technical jargon such as "Intervals below 15m are not supported due to design decision of android-job not to support them because they're not supported on Nougat and above" a little bit dry...

I'm all for a mention in wiki / FAQ about this issue though!

**Comment by philipwhiuk** [comment]
A little `[?] ` that shows a "Due to battery-related performance optimisations on later versions of Android it's not possible to sync more often than every 15 minutes" message
