### ISSUE TITLE
Crash when importing settings due to localization placeholders

### ISSUE THREAD

**Issue by wiktor-k** [thunderbird/thunderbird-android#3880]
### Expected behavior
Importing settings generated by Play Store K-9 throws.

### Actual behavior
Import should be successful.

### Steps to reproduce
1. Export settings in old K-9
2. Use non-default locale (non English)
3. Install or reset `master` K-9 and use import button there

### Environment
K-9 Mail version: `master`

Android version:8.0

Account type (IMAP, POP3, WebDAV/Exchange):none, yet

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

```
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Formatter.java:2522)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2814)
	at android.content.res.Resources.getString(Resources.java:472)
	at android.content.Context.getString(Context.java:572)
	at com.fsck.k9.activity.Accounts$AccountsImportedDialog.generateMessage(Accounts.java:1387)
	at com.fsck.k9.activity.Accounts$SimpleDialog.show(Accounts.java:1311)
	at com.fsck.k9.activity.Accounts.showAccountsImportedDialog(Accounts.java:1359)
	at com.fsck.k9.activity.Accounts.access$2600(Accounts.java:99)
	at com.fsck.k9.activity.Accounts$ImportAsyncTask.onPostExecute(Accounts.java:1890)
	at com.fsck.k9.activity.Accounts$ImportAsyncTask.onPostExecute(Accounts.java:1824)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

This is probably due to [this change](https://github.com/k9mail/k-9/commit/58717266c03d4a8290f9297b3eabe84f427d6f4d#diff-b257e70c653b5807e96c18a96b09abe5L1014) modifying number of placeholders in default values file but not in localized files.

**Comment by cketti** [comment]
This should be fixed by the new settings import UI.
