### ISSUE TITLE
Crash when opening PGP/MIME signed email

### ISSUE THREAD

**Issue by patti2** [thunderbird/thunderbird-android#3900]
### Expected behavior
The email should be opened and all attachments should be listed.

### Actual behavior
The app crashes upon opening the email.

### Steps to reproduce
1. Receive an email with multipart/signed type (PGP, Enigmail) and attachments
2. Click on it in the folder

### Environment
K-9 Mail version: 5.208

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
[k9-log.txt](https://github.com/k9mail/k-9/files/2827760/k9-log.txt)

**Comment by wiktor-k** [comment]
Hello, would it be possible to send that e-mail to one of maintainers for investigation?

Did you check version 5.600 (latest in Play Store) or from `master` branch?

**Comment by Massedil** [comment]
I don't know if it is exactly the same issue, but I think it is kind of related. Let me know if I have to open a new issue.

---

I have nothing configured for PGP on K-9 now.

How to reproduce :

1. Install and configure [Enigmail for Thunderbird](https://addons.thunderbird.net/en-US/thunderbird/addon/enigmail/).

2. Compose a new message.

3. Save it to Draft.

4. Synchronize and try to open this encrypted draft on K-9.

K-9 crashes :

```
03-21 12:42:17.014 D/AndroidRuntime(22456): Shutting down VM
03-21 12:42:17.015 E/AndroidRuntime(22456): FATAL EXCEPTION: main
03-21 12:42:17.015 E/AndroidRuntime(22456): Process: com.fsck.k9, PID: 22456
03-21 12:42:17.015 E/AndroidRuntime(22456): java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.activity.compose.AttachmentPresenter.loadNonInlineAttachments(AttachmentPresenter.java:173)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.activity.MessageCompose.processDraftMessage(MessageCompose.java:1335)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.activity.MessageCompose.processSourceMessage(MessageCompose.java:1214)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.activity.MessageCompose.loadLocalMessageForDisplay(MessageCompose.java:1590)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.activity.MessageCompose$10.onMessageViewInfoLoadFinished(MessageCompose.java:1610)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.activity.MessageLoaderHelper.onDecodeMessageFinished(MessageLoaderHelper.java:384)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.activity.MessageLoaderHelper.access$1000(MessageLoaderHelper.java:73)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.activity.MessageLoaderHelper$3.onLoadFinished(MessageLoaderHelper.java:411)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.activity.MessageLoaderHelper$3.onLoadFinished(MessageLoaderHelper.java:397)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:497)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:465)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.content.Loader.deliverResult(Loader.java:157)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.ui.message.LocalMessageExtractorLoader.deliverResult(LocalMessageExtractorLoader.java:47)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.fsck.k9.ui.message.LocalMessageExtractorLoader.deliverResult(LocalMessageExtractorLoader.java:17)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:272)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:96)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.os.Looper.loop(Looper.java:193)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at java.lang.reflect.Method.invoke(Native Method)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-21 12:42:17.015 E/AndroidRuntime(22456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-21 12:42:18.923 I/Process (22456): Sending signal. PID: 22456 SIG: 9
```

Let me know if I can help you more to reproduce the crash.

K-9 : 5.600 f-droid
LineageOS 16.0

**Comment by patti2** [comment]
@Massedil Best to send one of the drafts to the maintainers.

I'll send them my requested mail too, missed the first reply

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
