### ISSUE TITLE
App stops when cutting the data of "To" field

### ISSUE THREAD

**Issue by anonimou0** [thunderbird/thunderbird-android#3951]
### Expected behavior
When cutting the data of "To" field, nothing should happen on K-9 mail.

### Actual behavior
App breaks when cutting the data of "To" field.

### Steps to reproduce
1. Have some account pre-configured
2. Create a new mail (Letter image with a "+" sign) on the initial page (when app opens)
3. Add something on "To" field
4. Select it and use android "CUT" function
5. K-9 mail stops working

### Environment
K-9 Mail version: 5.600

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP, but shouldn't matter here.

[k9-log.txt](https://github.com/k9mail/k-9/files/2944082/k9-log.txt)

**Comment by starbuck3000** [comment]
Confirmed in 5.6000 on Android 9 (5th Aug 2019).

**Comment by cketti** [comment]
This is a bug in TokenAutoComplete. Potential fix: https://github.com/splitwise/TokenAutoComplete/pull/408

**Comment by TheMinefighter** [comment]
Same issue here

**Comment by rugk** [comment]
Also crashes when cutting from the To field.

Logcat:

```
FATAL EXCEPTION: main
Process: com.fsck.k9, PID: 5936
java.lang.IndexOutOfBoundsException: charAt: 31 >= length 31
	at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:125)
	at android.text.CharSequenceCharacterIterator.current(CharSequenceCharacterIterator.java:58)
	at android.text.CharSequenceCharacterIterator.setIndex(CharSequenceCharacterIterator.java:83)
	at android.icu.text.RuleBasedBreakIterator.CISetIndex32(RuleBasedBreakIterator.java:1006)
	at android.icu.text.RuleBasedBreakIterator.isBoundary(RuleBasedBreakIterator.java:508)
	at android.text.method.WordIterator.isBoundary(WordIterator.java:102)
	at android.widget.Editor$SelectionHandleView.positionAtCursorOffset(Editor.java:6044)
	at android.widget.Editor$HandleView.invalidate(Editor.java:4881)
	at android.widget.Editor$SelectionModifierCursorController.invalidateHandles(Editor.java:6903)
	at android.widget.Editor.invalidateHandlesAndActionMode(Editor.java:2241)
	at android.widget.TextView.setShadowLayer(TextView.java:5023)
	at com.tokenautocomplete.TokenCompleteTextView.api16Invalidate(TokenCompleteTextView.java:562)
	at com.tokenautocomplete.TokenCompleteTextView.invalidate(TokenCompleteTextView.java:571)
	at android.widget.TextView.updateAfterEdit(TextView.java:10865)
	at android.widget.TextView.handleTextChanged(TextView.java:10890)
	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:13807)
	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1268)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:231)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:38)
	at android.widget.TextView.deleteText_internal(TextView.java:13313)
	at android.widget.TextView.onTextContextMenuItem(TextView.java:12572)
	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4454)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2739)
	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:122)
	at com.android.internal.view.FloatingActionMode$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:2)
	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:430)
	at android.view.View.performClick(View.java:7441)
	at android.view.View.performClickInternal(View.java:7418)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28677)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

## system

Device: Pixel 4
OS: Android 12, CalyxOS 3.2.0
source: F-Droid
version: 5.903
