### ISSUE TITLE
Has crashed a few times while writing an email.

### ISSUE THREAD

**Issue by Rbagman** [thunderbird/thunderbird-android#4027]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

I don't see any crashes while writing an email issues open or closed.

### Expected behavior
Tell us what should happen

I should have been able do complete the email'

### Actual behavior
Tell us what happens instead

K9 crashed.

### Steps to reproduce

1. It happens intermittently.
2.
3.

### Environment
K-9 Mail version: 5.600

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:125)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:89)
	at com.bumptech.glide.Glide.with(Glide.java:620)
	at com.fsck.k9.activity.misc.ContactPictureLoader.loadFallbackPicture(ContactPictureLoader.java:128)
	at com.fsck.k9.activity.misc.ContactPictureLoader.loadContactPicture(ContactPictureLoader.java:171)
	at com.fsck.k9.activity.misc.ContactPictureLoader.loadContactPicture(ContactPictureLoader.java:122)
	at com.fsck.k9.activity.compose.RecipientAdapter.setContactPhotoOrPlaceholder(RecipientAdapter.java:156)
	at com.fsck.k9.view.RecipientSelectView.bindObjectView(RecipientSelectView.java:131)
	at com.fsck.k9.view.RecipientSelectView.redrawAllTokens(RecipientSelectView.java:292)
	at com.fsck.k9.view.RecipientSelectView.setShowCryptoEnabled(RecipientSelectView.java:281)
	at com.fsck.k9.activity.compose.RecipientMvpView.setRecipientTokensShowCryptoEnabled(RecipientMvpView.java:154)
	at com.fsck.k9.activity.compose.RecipientPresenter.redrawCachedCryptoStatusIcon(RecipientPresenter.java:439)
	at com.fsck.k9.activity.compose.RecipientPresenter.access$400(RecipientPresenter.java:56)
	at com.fsck.k9.activity.compose.RecipientPresenter$1.onPostExecute(RecipientPresenter.java:429)
	at com.fsck.k9.activity.compose.RecipientPresenter$1.onPostExecute(RecipientPresenter.java:410)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by kewisch** [comment]
Is this still an issue? We've improved the crash rate substantially more recently, and a lot of code has changed.
