### ISSUE TITLE
Unable to send unencrypted after importing settings with no OpenPGP App installed

### ISSUE THREAD

**Issue by silmaril42** [thunderbird/thunderbird-android#4058]
### Expected behavior
I should be able to send an unencrypted email.

### Actual behavior
Email cannot be sent. Red lock symbol is shown, due to PGP provider unavailable.

### Steps to reproduce
1. Export K9 settings from a phone with OpenPGP provider installed and integrated into K9.
2. Import those settings on a phone with no OpenPGP provider installed.
3. Try to send an email --> not possible.

### Workaround
1. Go to global settings
2. Tap on "OpenPGP App" --> Nothing is selected here
3. Explicitly select "no selection"

Now K9 is really configured not to use OpenPGP and sending (unencrypted) emails works again.

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type: IMAP

This seems similar / related to #1153 and the other issues mentioned there.

**Comment by GNUDimarik** [comment]
@silmaril42 hello.
what's is Global Settings?

**Comment by GNUDimarik** [comment]
App crashes.

`09-22 22:46:21.560 14505 14505 E AndroidRuntime: FATAL EXCEPTION: main
09-22 22:46:21.560 14505 14505 E AndroidRuntime: Process: com.fsck.k9.debug, PID: 14505
09-22 22:46:21.560 14505 14505 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.fsck.k9.debug/com.fsck.k9.activity.MessageCompose}; have you declared this activity in your AndroidManifest.xml?
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2012)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4587)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4545)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4906)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4874)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at com.fsck.k9.activity.compose.MessageActions.actionCompose(MessageActions.java:31)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at com.fsck.k9.activity.MessageList.onCompose(MessageList.java:1318)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.onCompose(MessageListFragment.java:613)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at com.fsck.k9.activity.MessageList.onOptionsItemSelected(MessageList.java:949)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.app.Activity.onMenuItemSelected(Activity.java:3544)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.view.View.performClick(View.java:6597)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:6574)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.view.View.access$3100(View.java:778)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:25889)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6746)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-22 22:46:21.560 14505 14505 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-22 22:46:21.581  1235  5559 W ActivityManager:   Force finishing activity com.fsck.k9.debug/com.fsck.k9.activity.MessageList`

@silmaril42 did you mean crash or just email doesn't send?
