### ISSUE TITLE
mail failed to send with message: NumberFormatException: For input string: "Request"

### ISSUE THREAD

**Issue by marscher** [thunderbird/thunderbird-android#4082]
The description is same as in #3332, but here with a stacktrace, which should provide at least some sort of insight:

Version 5.600
```
--------- beginning of main
06-13 12:51:59.452 23392 23392 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
06-13 12:51:59.591 23392 24195 E libEGL  : validate_display:99 error 3008 (EGL_BAD_DISPLAY)
06-13 12:52:08.945 23392 23392 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
06-13 12:52:08.945 23392 23392 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
06-13 12:52:22.654 23392 23408 E MessagingController: Failed to send message
06-13 12:52:22.654 23392 23408 E MessagingController: com.fsck.k9.mail.MessagingException: Unable to send message
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessageTo(SmtpTransport.java:482)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.java:428)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:2630)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.controller.MessagingController$21.run(MessagingController.java:2514)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:206)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:122)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:175)
06-13 12:52:22.654 23392 23408 E MessagingController:   at java.lang.Thread.run(Thread.java:761)
06-13 12:52:22.654 23392 23408 E MessagingController: Caused by: java.lang.NumberFormatException: For input string: "Request"
06-13 12:52:22.654 23392 23408 E MessagingController:   at java.lang.Integer.parseInt(Integer.java:521)
06-13 12:52:22.654 23392 23408 E MessagingController:   at java.lang.Integer.parseInt(Integer.java:556)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.mail.transport.smtp.StatusCodeClass.parse(StatusCodeClass.java:14)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.mail.transport.smtp.SmtpTransport.buildEnhancedNegativeSmtpReplyException(SmtpTransport.java:626)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.mail.transport.smtp.SmtpTransport.responseLineToCommandResponse(SmtpTransport.java:711)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.mail.transport.smtp.SmtpTransport.readPipelinedResponse(SmtpTransport.java:671)
06-13 12:52:22.654 23392 23408 E MessagingController:   at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessageTo(SmtpTransport.java:460)
06-13 12:52:22.654 23392 23408 E MessagingController:   ... 7 more
06-13 12:52:51.199 23392 23392 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = ViewRoot{b9a1be4 com.fsck.k9/com.fsck.k9.activity.MessageList,ident = 20}, this = DecorView@1c82806[MessageList]
06-13 12:52:51.214 23392 24096 D Surface : Surface::disconnect(this=0x929c2400,api=1)
06-13 12:52:51.220 23392 24096 D GraphicBuffer: unregister, handle(0x93cd47c0) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
06-13 12:52:51.222 23392 24096 D GraphicBuffer: unregister, handle(0xa7291b00) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
06-13 12:52:51.222 23392 24096 D GraphicBuffer: unregister, handle(0x8b12d380) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
06-13 12:52:51.222 23392 24096 D Surface : Surface::disconnect(this=0x929c2400,api=1)
read: unexpected EOF!

```

**Comment by cketti** [comment]
Can you please enable debug logging so the SMTP commands and responses are written to the log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by marscher** [comment]
I have created this log with debug enabled, but without printing credentials. I guess I have to enable that in order to obtain the required information?

**Comment by cketti** [comment]
No, "log sensitive information" doesn't need to be enabled. Enabling debug logging should be enough to log the SMTP commands/responses. Try looking at the unfiltered logcat output.

**Comment by phil-69** [comment]
In case it helps :
I had this problem with my yahoo account into k9 mail, whereas I had no problem with other mail accounts in k9.

Echec lors de l'envoi de certains courriels: NumberFormatException: for input string: "request"

I remarked that I had set my identity = name@yahoo.com instead of name@yahoo.fr

This was ok for authentification (!!) and ok for getting emails (Imap - !!), but not for sending (smtp)

Thus I set my correct identity = name@yahoo.fr
And now it's all ok

**Comment by jagman653** [comment]
After running F-droid K-9 for a week or so without problem I started getting the NumberFormatException error for my sbcglobal.net outgoing email. Is this a K-9  or yahoo problem?

**Comment by cketti** [comment]
@jagman653: Please open a new issue and provide as much information as possible about the error. See https://github.com/k9mail/k-9/wiki/LoggingErrors
