### ISSUE TITLE
java.lang.NullPointerException com.fsck.k9.mail.Message.isSet(com.fsck.k9.mail.Flag)

### ISSUE THREAD

**Issue by 532910** [thunderbird/thunderbird-android#4335]
```
E ImapSync: synchronizeMailbox
E ImapSync: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.fsck.k9.mail.Message.isSet(com.fsck.k9.mail.Flag)' on a null object reference
E ImapSync:     at com.fsck.k9.controller.MessagingController$ControllerSyncListener.syncFlagChanged(MessagingController.java:3068)
E ImapSync:     at com.fsck.k9.backend.imap.ImapSync.refreshLocalMessageFlags(ImapSync.java:670)
E ImapSync:     at com.fsck.k9.backend.imap.ImapSync.downloadMessages(ImapSync.java:393)
E ImapSync:     at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.java:210)
E ImapSync:     at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.java:52)
E ImapSync:     at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.java:118)
E ImapSync:     at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:721)
E ImapSync:     at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:699)
E ImapSync:     at com.fsck.k9.controller.MessagingController$10.run(MessagingController.java:684)
E ImapSync:     at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:220)
E ImapSync:     at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:113)
E ImapSync:     at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
E ImapSync:     at java.lang.Thread.run(Thread.java:764)
E ImapSync: Failed synchronizing folder of:it @ Wed Dec 04 06:54:55 GMT+03:00 2019
```
K-9 Mail version: 5.700 from F-Droid. Android 9 (LineagOS 16.0 + microG)
Account type IMAP

**Comment by cketti** [comment]
Please provide as much information as possible so we don't have to guess how to reproduce the error. The issue template is a good starting point and shouldn't be ignored.

**Comment by 532910** [comment]
[k9.log](https://github.com/k9mail/k-9/files/3920008/k9.log)

**Comment by 532910** [comment]
It happens every time it pull-up in some folders that are shown as empty (but really have letters).

**Comment by 532910** [comment]
Is there any update? It's completely broken for me.

**Comment by cketti** [comment]
Please create a new issue if this still a problem with a recent beta version (5.7xx).
