### ISSUE TITLE
A NullPointerException caused by intent handling

### ISSUE THREAD

**Issue by hanada31** [thunderbird/thunderbird-android#4343]
I noticed a crash in logs in the latest released version 5.7.0.1.
Activity: com.fsck.k9.activity.Search

### Exception trace:
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9/com.fsck.k9.activity.Search}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.Set.iterator()' on a null object reference
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
 at android.app.ActivityThread.-wrap11(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6944)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.Set.iterator()' on a null object reference
 at com.fsck.k9.search.LocalSearch.getFolderNames(LocalSearch.java:254)
 at com.fsck.k9.activity.MessageList.decodeExtras(MessageList.java:478)
 at com.fsck.k9.activity.MessageList.onCreate(MessageList.java:224)
 at android.app.Activity.performCreate(Activity.java:7183)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
 ... 9 more

### Test Case
action: android.intent.action.VIEW
extra: byteArray->search_bytes->new Byte[1]
extra: boolean->no_threading->false

**Comment by cketti** [comment]
Are you manually starting the activity with an Intent you created on your own?

**Comment by hanada31** [comment]
Actually，I designed a tool to test Android apps by constructing proper launching environments, which aims to automatically report the intent-related crashes.

**Comment by cketti** [comment]
Well, these are very low priority issues. Regular users won't encounter such crashes. If you want to help, consider creating a pull request to fix such issues.
