### ISSUE TITLE
Main UI constantly crash after updated to 5.704

### ISSUE THREAD

**Issue by zcattacz** [thunderbird/thunderbird-android#4539]
The notification and background sync still works, I can see folder check notices. But the UI won't open , always "unfortunately *** has stopped". 
I am using F-Droid build 5.704.
Just updated to 5.705, this issue persists.

If I try to downgrade , I always get the "failed to  install" error after the package installer screen. Looks like I am stuck.

The crash log says:

`
2020-02-16 05:09:31
PD1415D_A_1.22.1
versionName = 5.705 versionCode = 27005
android.content.res.Resources$NotFoundException	String resource ID #0x2040003
Resources.java	338
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9/com.fsck.k9.activity.MessageList}: android.content.res.Resources$NotFoundException: String resource ID #0x2040003 
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
	at android.app.ActivityThread.access$900(ActivityThread.java:188)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1521)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5714)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.content.res.Resources.getText(Resources.java:338)
	at android.content.res.VivoResources.getText(VivoResources.java:123)
	at android.content.res.Resources.getString(Resources.java:436)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:694)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:618)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:674)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:823)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:662)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:597)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:319)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:104)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:271)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:131)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:118)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:115)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:268)
	at android.webkit.WebView.<init>(WebView.java:591)
	at android.webkit.WebView.<init>(WebView.java:526)
	at android.webkit.WebView.<init>(WebView.java:509)
	at android.webkit.WebView.<init>(WebView.java:496)
	at android.webkit.WebView.<init>(WebView.java:486)
	at de.cketti.library.changelog.ChangeLog.getDialog(ChangeLog.java:285)
	at de.cketti.library.changelog.ChangeLog.getLogDialog(ChangeLog.java:263)
	at com.fsck.k9.activity.MessageList.onCreate(MessageList.java:268)
	at android.app.Activity.performCreate(Activity.java:6176)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532)
	... 10 more

`

**Comment by cketti** [comment]
This seems to be a bug in the WebView component on your device. Try updating it via Google Play.

**Comment by zcattacz** [comment]
The device is Android 5.1 based without Google Play. I have been updating K-9 all along with F-Droid. Non of them crash until 5.704. And no system patching was performed.
I tried FairMail, it works, just fine, also LibreMail, I mean, this didn't happen with other apps.
Thus I am thinking, if you can give it another perspective e.g as an compatibility issue ?
Not all device have/can install updates for system compoents like WebView...

**Comment by cketti** [comment]
It's a bug in old WebView versions that is triggered by the dark mode support in AppCompat 1.1.0. AppCompat 1.2.0-alpha02 seems to work fine.

**Comment by zcattacz** [comment]
Thanks, fixed, confirmed.
