### ISSUE TITLE
Crashed when deleting multiple emails from unified inbox

### ISSUE THREAD

**Issue by DavidWiesner** [thunderbird/thunderbird-android#4789]
### Expected behavior
When deleting multiple selected mails in the unified inbox, the app should not crashed.

### Actual behavior
When selecting multiple emails (no matter all selected emails are from the same account or not) in the unified inbox and click the delete button, the app almost always crashed with an IllegalStateException
`java.lang.IllegalStateException: Couldn't read row 1008, col 5 from Cursor Window. Make sure the Cursor is initialized correctly before accessing data from it.` 

### Steps to reproduce
1. Go to unified inbox
2. Select multiple emails
3. Click delete button

### Environment
K-9 Mail version: 5.715

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): mixed imap and pop3

Full Stacktrace:

```
java.lang.IllegalStateException: Couldn't read row 1008, col 5 from Cursor Window. 
Make sure the Cursor is initialized correctly before accessing data from it. 

at android.database.CursorWindow.nativeGetString(NativeMethod)
at androiddatabase.CursorWindow.getString(CursorWindow.java:469)
at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
at android.database.CursorWrapper.getString(CursorWrapper.java:141)
at android.database.CursorWrapper.getString(CursorWrapper.java:141)
at com.fsck.k9.provider.EmailProvider$SpecialColumnsCursor.getString(EmailProvider.java:709)
at android.database.CursorWrapper.getString(CursorWrapperer.java:141)
at android.database.CursorWrapper.getString(CursorWrapper.java:141)
at com.fsck.k9.helper.MergeCursor.getString(MergeCursor.java:205)
at com.fsck.kg.ui.messagelist.MessageListExtractor.extractMessageListItem(MessageListExtractor.kt:27)
at com.fsck.k9.ui.messagelist.MessageListExtractor.accessSextractMessageListItem(MessageListExtractor.kt:11)
at com.fsck.k9.ui.messagelist.MessagelListExtractor$extractMessageList$1.invoke(MessageListExtractor.kt:16)
at com.fsck.k9.ui.messagelist.MessagelListExtractor$extractMessageList$1.invoke(MessageListExtractor.kt:11)
at com.fsck.k9.helper.CursorExtensionskt.map(Cursorsions.kt:8)
at com.fsck.k9.ui.messagelist.MessagelListExtractor.extractMessageList(MessageListExtractor.kt:16)
at com.fsck.k9.ui.messagelist.MessageListLoader.getMessageageList(MessageListLoader.kt:54)
at com.fsck.k9.ui.messagelist.MessageListLiveData$loadMessageListAsync$1$1.invokeSuspend(MessageListLiveData.kt:33)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineSscheduler.kt:738)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by cketti** [comment]
Crashes similar to this have been happening for a long time. However, I have no idea what is causing this. Help in tracking this down would be very much appreciated.

**Comment by GNUDimarik** [comment]
I could not reproduce it on current master.
@DavidWiesner are you still can?
