### ISSUE TITLE
wrong message when password is incorrect

### ISSUE THREAD

**Issue by rezazarchi** [thunderbird/thunderbird-android#5028]
**Describe the bug**
hi.
when we enter incorrect password, k9 shows incorrect message when check incoming server configurations: 
"Cannot connect to server"
but its ok in outgoing server check:
"Username or password incorrect"

**To Reproduce**
1. Open application
2. enter login information with incorrect password
3. check incoming server
4. check outgoing server

**Expected behavior**
show incorrect password

**Screenshots**
![error on incoming check](https://i.imgur.com/ggKuhml.png)

![error on outgoing check](https://i.imgur.com/DuNL5pm.png)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.723-SNAPSHOT (debug)
 - Android version: 7
 - Device: Android emulator
 - Account type: IMAP

**Additional context**
...

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

```
2020-10-27 11:21:02.277 3948-4026/com.fsck.k9.debug E/ImapConnection: Failed to login, closing connection for conn257205850
2020-10-27 11:21:02.278 3948-4026/com.fsck.k9.debug E/AccountSetupCheckSettings$CheckAccountTask: Error while testing settings
    com.fsck.k9.mail.MessagingException: Unable to connect
        at com.fsck.k9.mail.store.imap.ImapStore.checkSettings(ImapStore.java:276)
        at com.fsck.k9.backend.imap.ImapBackend.checkIncomingServerSettings(ImapBackend.kt:145)
        at com.fsck.k9.controller.MessagingController.checkIncomingServerSettings(MessagingController.java:1715)
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkIncoming(AccountSetupCheckSettings.java:504)
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkServerSettings(AccountSetupCheckSettings.java:479)
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground(AccountSetupCheckSettings.java:435)
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground(AccountSetupCheckSettings.java:413)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.io.IOException: readStringUntil(): end of stream reached. Read: "" while waiting for ' '
        at com.fsck.k9.mail.store.imap.ImapResponseParser.readStringUntil(ImapResponseParser.java:445)
        at com.fsck.k9.mail.store.imap.ImapResponseParser.parseTaggedResponse(ImapResponseParser.java:284)
        at com.fsck.k9.mail.store.imap.ImapResponseParser.readTaggedResponse(ImapResponseParser.java:73)
        at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:42)
        at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:28)
        at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:86)
        at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:752)
        at com.fsck.k9.mail.store.imap.ImapConnection.login(ImapConnection.java:520)
        at com.fsck.k9.mail.store.imap.ImapConnection.saslAuthPlainWithLoginFallback(ImapConnection.java:480)
        at com.fsck.k9.mail.store.imap.ImapConnection.authenticate(ImapConnection.java:362)
        at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:141)
        at com.fsck.k9.mail.store.imap.ImapStore.checkSettings(ImapStore.java:273)
        at com.fsck.k9.backend.imap.ImapBackend.checkIncomingServerSettings(ImapBackend.kt:145) 
        at com.fsck.k9.controller.MessagingController.checkIncomingServerSettings(MessagingController.java:1715) 
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkIncoming(AccountSetupCheckSettings.java:504) 
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkServerSettings(AccountSetupCheckSettings.java:479) 
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground(AccountSetupCheckSettings.java:435) 
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground(AccountSetupCheckSettings.java:413) 
        at android.os.AsyncTask$2.call(AsyncTask.java:304) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
2020-10-27 11:21:02.406 3948-3967/com.fsck.k9.debug D/EGL_emulation: eglMakeCurrent: 0xa10852a0: ver 2 0 (tinfo 0xa1083240)
```

```
2020-10-27 11:22:05.730 3948-4051/com.fsck.k9.debug E/AccountSetupCheckSettings$CheckAccountTask: Error while testing settings
    com.fsck.k9.mail.AuthenticationFailedException: AUTH PLAIN failed (Error: authentication failed: authentication failure)
        at com.fsck.k9.mail.transport.smtp.SmtpTransport.saslAuthPlain(SmtpTransport.java:701)
        at com.fsck.k9.mail.transport.smtp.SmtpTransport.open(SmtpTransport.java:209)
        at com.fsck.k9.mail.transport.smtp.SmtpTransport.checkSettings(SmtpTransport.java:799)
        at com.fsck.k9.backend.imap.ImapBackend.checkOutgoingServerSettings(ImapBackend.kt:153)
        at com.fsck.k9.controller.MessagingController.checkOutgoingServerSettings(MessagingController.java:1719)
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkOutgoing(AccountSetupCheckSettings.java:494)
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkServerSettings(AccountSetupCheckSettings.java:483)
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground(AccountSetupCheckSettings.java:435)
        at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground(AccountSetupCheckSettings.java:413)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2020-10-27 11:22:05.834 3948-3967/com.fsck.k9.debug D/EGL_emulation: eglMakeCurrent: 0xa10852a0: ver 2 0 (tinfo 0xa1083240)

```

**Comment by cketti** [comment]
Looks like the error response of the server can't be parsed properly. Can you provide the server's response?

**Comment by kewisch** [comment]
Closing this issue as there has not been a response for a few years. Please comment if there is still an issue.
