### ISSUE TITLE
crash when edit email setup details

### ISSUE THREAD

**Issue by rezazarchi** [thunderbird/thunderbird-android#5029]
**Describe the bug**
when email username or password is wrong, we click on edit details. then edit email password and click on next and suddenly app crashes

**To Reproduce**
1. open application
2. enter wrong email address or password
3. error dialog shows and we click on edit details
4. fix email address and password and click on next
5. app crash

**Expected behavior**
it should go to next step without any problem

**Screenshots**
...

**Environment (please complete the following information):**
- K-9 Mail version: 5.723-SNAPSHOT (debug)
- Android version: 7
- Device: Android emulator
- Account type: IMAP

**Additional context**
...

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

```
2020-10-27 14:24:33.556 4705-4705/com.fsck.k9.debug D/AndroidRuntime: Shutting down VM
2020-10-27 14:24:33.557 4705-4705/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fsck.k9.debug, PID: 4705
    java.lang.IllegalStateException: Outbox folder was already set up
        at com.fsck.k9.mailstore.SpecialLocalFoldersCreator.createSpecialLocalFolders(SpecialLocalFoldersCreator.kt:13)
        at com.fsck.k9.activity.setup.AccountSetupBasics.finishAutoSetup(AccountSetupBasics.java:267)
        at com.fsck.k9.activity.setup.AccountSetupBasics.onNext(AccountSetupBasics.java:313)
        at com.fsck.k9.activity.setup.AccountSetupBasics.onClick(AccountSetupBasics.java:384)
        at android.view.View.performClick(View.java:5610)
        at android.view.View$PerformClick.run(View.java:22265)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by rezazarchi** [comment]
it seems that crash happends because of [this check](https://github.com/k9mail/k-9/blob/80b46277ff670c1af89602f80455faa23017e372/app/core/src/main/java/com/fsck/k9/mailstore/SpecialLocalFoldersCreator.kt#L13) that throws IllegalStateException without any handling. it should be handle or finding another solution for this line.

It may also be better to call [createSpecialLocalFolders](https://github.com/k9mail/k-9/blob/80b46277ff670c1af89602f80455faa23017e372/app/core/src/main/java/com/fsck/k9/mailstore/SpecialLocalFoldersCreator.kt#L12) method after check incoming/outgoing
