### ISSUE TITLE
NPE when trying to change folder settings of outbox folder

### ISSUE THREAD

**Issue by plan3d** [thunderbird/thunderbird-android#5249]
**Describe the bug**
I tried to change my folder settings for outbox folder but app crashes.

**To Reproduce**
1. Tab on sandwich icon to open side menu
2. Tab on 'Manage folders'
3. Tab on 'Outbox' (2nd list item)
4. App crashes

**Expected behavior**
App should show folder settings

**Environment (please complete the following information):**
 - K-9 Mail version: actual main (1a68adc8)
 - Android version: 10

**Logs**
FATAL EXCEPTION: main
    Process: com.fsck.k9.debug, PID: 9972
    java.lang.NullPointerException: cursor.getString(7) must not be null
        at com.fsck.k9.storage.messages.CursorFolderAccessor.getSyncClass(RetrieveFolderOperations.kt:151)
        at com.fsck.k9.mailstore.FolderRepository$getFolderDetails$1.map(FolderRepository.kt:62)
        at com.fsck.k9.mailstore.FolderRepository$getFolderDetails$1.map(FolderRepository.kt:8)
        at com.fsck.k9.storage.messages.RetrieveFolderOperations$getFolder$1.doDbWork(RetrieveFolderOperations.kt:44)
        at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:273)
        at com.fsck.k9.storage.messages.RetrieveFolderOperations.getFolder(RetrieveFolderOperations.kt:32)
        at com.fsck.k9.storage.messages.RetrieveFolderOperations.getFolder(RetrieveFolderOperations.kt:16)
        at com.fsck.k9.storage.messages.K9MessageStore.getFolder(K9MessageStore.kt:94)
        at com.fsck.k9.mailstore.FolderRepository.getFolderDetails(FolderRepository.kt:52)
        at com.fsck.k9.ui.managefolders.FolderSettingsViewModel$loadFolderDetails$2.invokeSuspend(FolderSettingsViewModel.kt:74)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by plan3d** [comment]
I'll create pull request with a fix

**Comment by cketti** [comment]
The Outbox is a folder that is only available locally. We should probably hide all "folder class" settings except for "folder display class" for such folders.
