### ISSUE TITLE
issue with "Add from Contact" when permission not granted

### ISSUE THREAD

**Issue by rezazarchi** [thunderbird/thunderbird-android#5343]
I have some issues when i don't give contact permission to application and Add from Contacts.

**Describe the bug**
On Android 11 toast showed with this message: **No email address could be found for this contact.**
On Android 7 & 9 contact added successfully but when i click on that in To field, application get crashed.

**To Reproduce**

1. Don't give contact permission
2. Go to "Compose''
2. Click on 'more options then Add from Contacts'
3. Select a contact
4.1. On Android 11 toast showed with this message: **No email address could be found for this contact.**
4.2. On Android 7 & 9 contact added successfully but when i click on that name or email in To field, application get crashed.

**Expected behavior**
maybe should not show "Add from Contacts" when there is no contact permission or handle these situations and show related error message to the user.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.735-SNAPSHOT
 - Android version: 7,9,11
 - Device: Emulator
 - Account type: IMAP

**ScreenShot**
Android 7
https://user-images.githubusercontent.com/8654398/122031636-21e7a980-cde4-11eb-872e-bd550c076d13.mp4

**Logs**
error log on Android 7
```
2021-06-15 14:06:09.330 3649-3724/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #4
    Process: com.fsck.k9.debug, PID: 3649
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/contacts/lookup/0r1-4B315B29/1 from pid=3649, uid=10082 requires android.permission.READ_CONTACTS, or grantUriPermission()
        at android.os.Parcel.readException(Parcel.java:1683)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
        at android.content.ContentResolver.query(ContentResolver.java:530)
        at android.content.ContentResolver.query(ContentResolver.java:472)
        at android.provider.ContactsContract$Contacts.lookupContact(ContactsContract.java:1623)
        at com.fsck.k9.activity.compose.RecipientLoader.fillContactDataFromLookupKey(RecipientLoader.java:284)
        at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:201)
        at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:37)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by cketti** [comment]
There seem to be a couple of bugs.
- We should remove the "Add from Contacts" option when we don't have permission to access the contacts.
- `RecipientLoader` shouldn't try to access the contacts if we don't have the necessary permission.
- I'm not sure why the "permission rationale" dialog is displayed in your video, but afterwards the system dialog to grant the contacts permission isn't shown.
