### ISSUE TITLE
Crash on "empty trash"

### ISSUE THREAD

**Issue by stephankn** [thunderbird/thunderbird-android#5457]
**Describe the bug**
Application crashes once I try to empty trash on imap folder

**To Reproduce**
1. Go to 'deleted items' folder
2. Click on '...'
3. Click on 'empty trash'
4. application crash

**Expected behavior**
expect no crash

**Environment**
 - K-9 Mail version: 5.800
 - Android version: 9
 - Device: ZTE Axon 9
 - Account type: IMAP

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
```
2021-07-27 14:41:25.832 2549-30323/? E/memtrack: Couldn't load memtrack module
2021-07-27 14:41:25.832 2549-30323/? W/android.os.Debug: failed to get memory consumption info: -1
2021-07-27 14:41:26.330 2161-2161/? D/VendorServiceStateTracker: handleMessage: Event: 12
2021-07-27 14:41:26.333 2161-2161/? D/VendorServiceStateTracker: handleMessage: Event: 100
2021-07-27 14:41:26.333 2161-2161/? D/VendorServiceStateTracker: [0] Event EVENT_VENDOR_SIGNAL_STRENGTH_UPDATE Received
2021-07-27 14:41:26.333 2161-2161/? D/VendorServiceStateTracker: mLteEarfcn =-1, lteBand =-1
2021-07-27 14:41:26.336 1997-2362/? D/class com.zte.adapt.systemui.MobileSignalControllerAdapt: Signal changed! Google 4 operator 5
2021-07-27 14:41:26.385 2161-2161/? D/VendorServiceStateTracker: handleMessage: Event: 43
2021-07-27 14:41:26.512 29060-29147/? D/OpenGLRenderer: endAllActiveAnimators on 0x7003984a00 (RippleDrawable) with handle 0x70038e2ae0
2021-07-27 14:41:26.538 1997-1997/? D/LightBarControllerAdapt: forbitLightMode:false
2021-07-27 14:41:26.538 1997-1997/? D/LightBarControllerAdapt: forbitLightMode:false
2021-07-27 14:41:26.652 29060-29101/? W/CursorWindow: Window is full: requested allocation 517 bytes, free space 7 bytes, window size 2097152 bytes
2021-07-27 14:41:26.689 715-1773/? W/SurfaceFlinger: Attempting to set client state on removed layer: com.fsck.k9/com.fsck.k9.activity.MessageList#1
2021-07-27 14:41:26.689 715-1773/? W/SurfaceFlinger: Attempting to destroy on removed layer: com.fsck.k9/com.fsck.k9.activity.MessageList#1
2021-07-27 14:41:26.691 715-795/? W/SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=c07cf8a com.fsck.k9/com.fsck.k9.activity.MessageList)/@0xf3d3a18 - animation-leash#0
2021-07-27 14:41:26.691 715-795/? W/SurfaceFlinger: Attempting to destroy on removed layer: Surface(name=c07cf8a com.fsck.k9/com.fsck.k9.activity.MessageList)/@0xf3d3a18 - animation-leash#0
2021-07-27 14:41:26.705 715-1773/? W/SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=18212#0
2021-07-27 14:41:26.769 10512-10512/? D/SWPD: PD: R->W
2021-07-27 14:41:26.816 29060-29524/? W/CursorWindow: Window is full: requested allocation 517 bytes, free space 7 bytes, window size 2097152 bytes
2021-07-27 14:41:26.863 2549-2549/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.clearcut.bootcount.service.START cmp=com.google.android.gms/.chimera.PersistentBoundBrokerService }
2021-07-27 14:41:27.006 29060-29101/? E/CursorWindow: Failed to read row 919, column 0 from a CursorWindow which has 918 rows, 19 columns.
    
    --------- beginning of crash
2021-07-27 14:41:27.007 29060-29060/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fsck.k9, PID: 29060
    java.lang.IllegalStateException: Couldn't read row 919, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetLong(Native Method)
        at android.database.CursorWindow.getLong(CursorWindow.java:538)
        at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
        at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
        at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
        at com.fsck.k9.provider.EmailProvider$SpecialColumnsCursor.getLong(EmailProvider.java:689)
        at com.fsck.k9.cache.EmailProviderCacheCursor.<init>(EmailProviderCacheCursor.java:47)
        at com.fsck.k9.provider.EmailProvider.query(EmailProvider.java:248)
        at android.content.ContentProvider.query(ContentProvider.java:1083)
        at android.content.ContentProvider.query(ContentProvider.java:1175)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
        at android.content.ContentResolver.query(ContentResolver.java:804)
        at android.content.ContentResolver.query(ContentResolver.java:753)
        at android.content.ContentResolver.query(ContentResolver.java:711)
        at com.fsck.k9.ui.messagelist.MessageListLoader.loadMessageListForAccount(MessageListLoader.kt:125)
        at com.fsck.k9.ui.messagelist.MessageListLoader.getMessageList(MessageListLoader.kt:45)
        at com.fsck.k9.ui.messagelist.MessageListLiveData$loadMessageListAsync$1$1.invokeSuspend(MessageListLiveData.kt:33)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
    
    
    --------- beginning of system
2021-07-27 14:41:27.012 1458-4281/? W/ActivityManager:   Force finishing activity com.fsck.k9/.activity.MessageList
2021-07-27 14:41:27.016 1458-4281/? D/ActivityTrigger: ActivityTrigger activityPauseTrigger 
2021-07-27 14:41:27.022 29060-29060/? I/Process: Sending signal. PID: 29060 SIG: 9
```

**Comment by carlosm2** [comment]
to the record:

I've just did 

**Reproduce**

Go to 'deleted items' folder
Click on '...'
Click on 'empty trash'
Removed trash

**Environment**

    K-9 Mail version: 5.800
    Android version: 10
    Device: Samsung SM-A207M
    Account type: IMAP

**Comment by stephankn** [comment]
@carlosm2 to be clear: It also crashed for you with that reproduction?

Some more input:
I found a work-around. Instead of selecting the entry to empty trash, I selected all Messages inside the trash folder and clicked on delete. This worked.

On my error case I had a larger amount of deleted mails in the trash. Over 3.000. When I retried with about 20, it worked with the "empty trash" command.

So I guess this is an issue with the window coming from the content provider being out of sync with the data, so the cursor points to not existing items.
https://github.com/k9mail/k-9/blob/756ffc78564f051f34edc56b65784f393b72de1b/app/core/src/main/java/com/fsck/k9/provider/EmailProvider.java#L207

It was the first "empty trash" after the update to 5.800. Could it be that the database was not converted properly?

**Comment by cketti** [comment]
> So I guess this is an issue with the window coming from the content provider being out of sync with the data, so the cursor points to not existing items.

That could be it. I believe the cursor window is limited in size and only the first one is filled when the query call to the database returns. So when more than one is needed to fetch all results there's the possibility of a race condition (initial query includes messages that are later deleted before data about them could be read from the cursor).
