### ISSUE TITLE
Inbox fetch fails with a "search queries with NOT or OR clauses are not yet implemented" error

### ISSUE THREAD

**Issue by arunsathiya** [thunderbird/thunderbird-android#5507]
I would like to preface my message by noting that I am not sure if this is a K-9 Mail issue, or an issue at the email host's end. It's particularly worth noting the same configuration works okay on a different IMAP app ([Nine Mail](https://www.9folders.com/en/index.html)), so feels more of a K-9 Mail situation. If it isn't, feel free to let me know and I can close this issue.

**Describe the bug**

I have an unique setup where I use my [ProtonMail](https://protonmail.com) account using a third-party bridge software [Hydroxide](https://github.com/emersion/hydroxide) on my Raspberry Pi. Since that bridge and my Android device are on the same [Tailscale](https://github.com/tailscale/tailscale) network, I am able to configure my Raspberry Pi node address as the IMAP server. 

**To Reproduce**

- Setup Hydroxide on a Raspberry Pi, install Tailscale on that Raspberry Pi and on Android.
- Now that the Raspberry Pi and Android are on the same network, add the Raspberry Pi's Tailscale node address as the IMAP server for the account.
- On the inbox view, pull down to fetch emails.

**Expected behavior**

New inbox emails appear.

**What happens at the moment**

None of the inbox emails appear. A `Load up to 25 more` button appears in that place.

**Screenshots**

![Screenshot_20210802-231858](https://user-images.githubusercontent.com/18581859/127903107-b26d196b-2def-44f4-b909-f04621dfb2e5.jpg)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.801
 - Android version: 10
 - Device: OnePlus 5
 - Account type: IMAP

**Additional context**

If it's useful at all: I have blogged about [Hydroxide setup for ProtonMail on the Tailscale network](https://arun.be/2021/07/29/hydroxide-headless-bridge-for-protonmail-on-tailscale/). If sharing a blog post link is against the repository's guidelines, I am happy for this link to be removed.

**Logs**

```
08-02 23:11:44.214  7467  8629 I MessagingController: Running command 'synchronizeMailbox', seq = 450 (background priority)
08-02 23:11:44.215  7467  8629 D MessagingController: Last folder list refresh @ Mon Aug 02 23:01:34 GMT+05:30 2021. Not refreshing now.
08-02 23:11:44.220  7467  8629 I ImapSync: Synchronizing folder Arun:INBOX
08-02 23:11:44.220  7467  8629 V ImapSync: SYNC: About to get local folder INBOX
08-02 23:11:44.222  7467  8629 V ImapSync: SYNC: About to get remote folder INBOX
08-02 23:11:44.222  7467  8629 V ImapSync: SYNC: About to open remote folder INBOX
08-02 23:11:44.222  7467  8629 V RealImapConnection: conn208898946>>> 674 NOOP
08-02 23:11:44.451  7467  8629 V ImapResponseParser: conn208898946<<<#674# [OK, NOOP completed]
08-02 23:11:44.452  7467  8629 V RealImapConnection: conn208898946>>> 675 EXAMINE "INBOX"
08-02 23:11:44.457  7467  8629 V ImapResponseParser: conn208898946<<<#null# [FLAGS, [\Seen, \Deleted, \Draft, REDACTED, REDACTED, \Flagged]]
08-02 23:11:44.458  7467  8629 V ImapResponseParser: conn208898946<<<#null# [OK, [PERMANENTFLAGS, [\Seen, \Deleted, \Draft, REDACTED, REDACTED, \Flagged]], Flags permitted.]
08-02 23:11:44.459  7467  8629 V ImapResponseParser: conn208898946<<<#null# [3499, EXISTS]
08-02 23:11:44.459  7467  8629 V ImapResponseParser: conn208898946<<<#null# [0, RECENT]
08-02 23:11:44.460  7467  8629 V ImapResponseParser: conn208898946<<<#null# [OK, [UIDNEXT, 3500], Predicted next UID]
08-02 23:11:44.460  7467  8629 V ImapResponseParser: conn208898946<<<#null# [OK, [UIDVALIDITY, 1], UIDs valid]
08-02 23:11:44.460  7467  8629 V ImapResponseParser: conn208898946<<<#675# [OK, [READ-ONLY], EXAMINE completed]
08-02 23:11:44.461  7467  8629 D RealImapFolder: Got untagged EXISTS with value 3499 for Arun:INBOX/MessagingController/conn208898946
08-02 23:11:44.461  7467  8629 D RealImapFolder: Got UidNext = 3500 for Arun:INBOX/MessagingController/conn208898946
08-02 23:11:44.465  7467  8629 V ImapSync: SYNC: Remote message count for folder INBOX is 3499
08-02 23:11:44.466  7467  8629 V ImapSync: SYNC: About to get messages 3250 through 3499 for folder INBOX
08-02 23:11:44.467  7467  8629 V RealImapConnection: conn208898946>>> 676 UID SEARCH 3250:3499 NOT DELETED
08-02 23:11:44.471  7467  8629 V ImapResponseParser: conn208898946<<<#676# [NO, search queries with NOT or OR clauses are not yet implemented]
08-02 23:11:44.472  7467  8629 E ImapSync: synchronizeMailbox
08-02 23:11:44.472  7467  8629 E ImapSync: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: UID SEARCH 3250:3499 NOT DELETED; response: #676# [NO, search queries with NOT or OR clauses are not yet implemented]
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:118)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.java:783)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.java:769)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.getMessages(RealImapFolder.kt:410)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.getMessages(RealImapFolder.kt:383)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:138)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:55)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:671)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:628)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.controller.MessagingController.lambda$synchronizeMailbox$3(MessagingController.java:594)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.controller.MessagingController.lambda$synchronizeMailbox$3$MessagingController(Unknown Source:0)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.controller.-$$Lambda$MessagingController$YbzydiinGGp7zlb7T59BvUu_Fvw.run(Unknown Source:8)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:218)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:108)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:159)
08-02 23:11:44.472  7467  8629 E ImapSync: 	at java.lang.Thread.run(Thread.java:919)
08-02 23:11:44.495  7467  8629 E ImapSync: Failed synchronizing folder Arun:INBOX @ Mon Aug 02 23:11:44 GMT+05:30 2021
08-02 23:11:44.495  7467  8629 I MessagingController:  Command 'synchronizeMailbox' completed
```

**Comment by cketti** [comment]
The error message "search queries with NOT or OR clauses are not yet implemented" is generated by the IMAP server. So it's missing functionality in the server software.
We can't easily change the way K-9 Mail is synchronizing messages. So we're not going to work around this issue. You'll have to wait for the functionality to be added to the bridge.

**Comment by arunsathiya** [comment]
Thanks for letting me know. It's good to know that the issue is workable (especially because another IMAP client works okay). I'll continue using K-9 Mail for non-ProtonMail accounts.

**Comment by arunsathiya** [comment]
Also, this seems to be reported already. Dupe: https://github.com/emersion/hydroxide/issues/149
