### ISSUE TITLE
Crash on startup after updating to 5.804

### ISSUE THREAD

**Issue by fschrempf** [thunderbird/thunderbird-android#5600]
**Describe the bug**
After updating to 5.804 through F-Droid the app crashes on startup. Trying to downgrade to 5.803 or 5.802 via F-Droid also fails (but that is probably a different issue). 

**To Reproduce**
1. Install the update to 5.804 via F-Droid
2. Start the app

**Expected behavior**
App should not crash.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.804
 - Android version: 7.0
 - Device: Lenovo K6 (k33a48)
 - Account type: IMAP

**Additional context**

**Logs**
[I don't know how to enable logs as I currently can't start the app at all]

**Comment by cketti** [comment]
> [I don't know how to enable logs as I currently can't start the app at all]

See https://github.com/k9mail/k-9/wiki/LoggingErrors

"If K-9 is crashing or you otherwise can't get to the settings screen, don't worry about about enabling debug logs."

**Comment by fschrempf** [comment]
@cketti Thanks, I read this note, but it wasn't really clear to me if "don't worry" means, there is no possibility to get the logs in this case anyway. Or if I should just continue with the guide and skip this step and there will still be some crash log that is retrievable via adb.

I had a closer look now and simply checked what is printed in the adb log when the app crashes and maybe this is something you can work with:

<details><summary>Exceptions from crash log</summary>

```
08-22 17:44:49.724 27023 27036 W SharedPreferencesImpl: Attempt to read preferences file /data/user/0/com.fsck.k9/shared_prefs/database_version_cache.xml without permission
08-22 17:44:49.717   523   523 W Binder:481_1: type=1400 audit(0.0:10080): avc: denied { search } for name="2069" dev="proc" ino=25210 scontext=u:r:surfaceflinger:s0 tcontext=u:r:mm-pp-daemon:s0 tclass=dir permissive=0
08-22 17:44:49.742 27023 27023 E SQLiteLog: (14) cannot open file at line 32460 of [69906880ce]
08-22 17:44:49.742 27023 27023 E SQLiteLog: (14) os_unix.c:32460: (13) open(/data/user/0/com.fsck.k9/databases/preferences_storage) - 
08-22 17:44:49.744 27023 27023 E SQLiteDatabase: Failed to open database '/data/user/0/com.fsck.k9/databases/preferences_storage'.
08-22 17:44:49.744 27023 27023 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:680)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:665)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:283)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.preferences.K9StoragePersister.openDB(K9StoragePersister.java:34)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.preferences.K9StoragePersister.loadValues(K9StoragePersister.java:145)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.Preferences.<init>(Preferences.kt:51)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.Preferences.<init>(Preferences.kt:33)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.KoinModuleKt$mainModule$1$2.invoke(KoinModule.kt:21)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.KoinModuleKt$mainModule$1$2.invoke(KoinModule.kt)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:39)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:47)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:236)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.scope.Scope.get(Scope.kt:204)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.preferences.KoinModuleKt$preferencesModule$1$4.invoke(KoinModule.kt:138)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.preferences.KoinModuleKt$preferencesModule$1$4.invoke(KoinModule.kt)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:39)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:47)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:236)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at org.koin.core.scope.Scope.get(Scope.kt:204)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.K9$$special$$inlined$inject$1.invoke(DI.kt:138)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.K9.getGeneralSettingsManager(K9.kt)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.K9.init(K9.kt:299)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.fsck.k9.App.onCreate(App.kt:38)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.app.ActivityThread.-wrap2(ActivityThread.java)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.os.Handler.dispatchMessage(Handler.java:102)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.os.Looper.loop(Looper.java:154)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at android.app.ActivityThread.main(ActivityThread.java:6077)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at java.lang.reflect.Method.invoke(Native Method)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
08-22 17:44:49.744 27023 27023 E SQLiteDatabase:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
08-22 17:44:49.737  1087  1087 W Binder:481_3: type=1400 audit(0.0:10081): avc: denied { search } for name="2069" dev="proc" ino=25210 scontext=u:r:surfaceflinger:s0 tcontext=u:r:mm-pp-daemon:s0 tclass=dir permissive=0
08-22 17:44:49.750 27023 27023 D AndroidRuntime: Shutting down VM
08-22 17:44:49.751 27023 27023 E AndroidRuntime: FATAL EXCEPTION: main
08-22 17:44:49.751 27023 27023 E AndroidRuntime: Process: com.fsck.k9, PID: 27023
08-22 17:44:49.751 27023 27023 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.fsck.k9.App: org.koin.core.error.InstanceCreationException: Could not create instance for [Single:'com.fsck.k9.preferences.RealGeneralSettingsManager',binds:com.fsck.k9.preferences.GeneralSettingsManager]
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5364)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.app.ActivityThread.-wrap2(ActivityThread.java)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6077)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
08-22 17:44:49.751 27023 27023 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Single:'com.fsck.k9.preferences.RealGeneralSettingsManager',binds:com.fsck.k9.preferences.GeneralSettingsManager]
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:62)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:39)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:47)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:236)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.scope.Scope.get(Scope.kt:204)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.K9$$special$$inlined$inject$1.invoke(DI.kt:138)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.K9.getGeneralSettingsManager(K9.kt)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.K9.init(K9.kt:299)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.App.onCreate(App.kt:38)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        ... 8 more
08-22 17:44:49.751 27023 27023 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Single:'com.fsck.k9.Preferences']
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:62)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:39)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:47)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:236)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.scope.Scope.get(Scope.kt:204)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.preferences.KoinModuleKt$preferencesModule$1$4.invoke(KoinModule.kt:138)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.preferences.KoinModuleKt$preferencesModule$1$4.invoke(KoinModule.kt)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        ... 20 more
08-22 17:44:49.751 27023 27023 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:680)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:665)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:283)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.preferences.K9StoragePersister.openDB(K9StoragePersister.java:34)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.preferences.K9StoragePersister.loadValues(K9StoragePersister.java:145)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.Preferences.<init>(Preferences.kt:51)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.Preferences.<init>(Preferences.kt:33)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.KoinModuleKt$mainModule$1$2.invoke(KoinModule.kt:21)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at com.fsck.k9.KoinModuleKt$mainModule$1$2.invoke(KoinModule.kt)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
08-22 17:44:49.751 27023 27023 E AndroidRuntime:        ... 28 more
```

</details>

**Comment by cketti** [comment]
Your installation seems to be broken. The main database can't be opened/created. Try uninstalling the app, then reinstalling.

**Comment by fschrempf** [comment]
> Your installation seems to be broken. The main database can't be opened/created. Try uninstalling the app, then reinstalling.

Ok, I have no idea how this could happen. Reinstalling the app works, but it seems that all my settings are gone. I guess I will try to setup everything again and see how it goes.

**Comment by cketti** [comment]
Sounds like this issue can be closed. Feel free to open another one if you encounter any other bugs.
