### ISSUE TITLE
Crash on "Show headers" every time (main branch)

### ISSUE THREAD

**Issue by parkerfath** [thunderbird/thunderbird-android#5871]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

JMAP DEV - main 8d6142e63abe10f48eb973c2cca321a59f881476

### Where did you get the app from?

Other

### Android version

11

### Device model

Samsung Galaxy S 10

### Steps to reproduce

1. Open any message
2. Tap "kebab" menu in top right 
3. Tap "Show headers"

### Expected behavior

Should see the headers of the message.

### Actual behavior

Crash, see logs below

### Logs

```
2022-01-18 21:33:24.873 27493-27493/com.fsck.k9.jmap.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fsck.k9.jmap.debug, PID: 27493
    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.fsck.k9.jmap.debug/com.fsck.k9.ui.messagesource.MessageSourceActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2078)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
        at android.app.Activity.startActivityForResult(Activity.java:5377)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:647)
        at android.app.Activity.startActivityForResult(Activity.java:5335)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:628)
        at android.app.Activity.startActivity(Activity.java:5721)
        at android.app.Activity.startActivity(Activity.java:5674)
        at com.fsck.k9.activity.MessageList.onOptionsItemSelected(MessageList.kt:1006)
```

**Comment by parkerfath** [comment]
FWIW I might take a look into fixing this one tomorrow, but just wanted to report it through the normal channel in case someone else was working on it, or in case it was something I was doing wrong.

**Comment by cketti** [comment]
Don't bother. The JMAP app is probably broken in many more ways. 

It has become clear that the approach I took to support building multiple apps needs to be adjusted quite a bit. I'll remove the JMAP app so new developers don't accidentally run it from Android Studio and wonder why things are so broken.
