### ISSUE TITLE
Double tapping on a mail crashes K-9 Mail

### ISSUE THREAD

**Issue by kolaente** [thunderbird/thunderbird-android#5953]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

F-Droid

### Android version

Android 11, oxygenOS 11.1.2.2

### Steps to reproduce

1. Open the app
2. Double tap quickly on a mail in your inbox (this has to happen quite fast because it will slide the inbox with the mails away on the first tap)

Maybe related to https://github.com/k9mail/k-9/issues/3144

### Expected behavior

Mail opens.

### Actual behavior

K-9 Mail crashes.

### Logs

https://gist.github.com/kolaente/b32a84d7cf1ad5ac01c56658b9d7ff05 (reporting this from my phone so I'm not able to upload a file directly)

**Comment by cketti** [comment]
Copied the stack trace to keep the relevant information in the issue tracker.
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:168)
	at android.widget.ListView.dispatchDraw(ListView.java:3526)
	at android.view.View.draw(View.java:22538)
	at android.widget.AbsListView.draw(AbsListView.java:4432)
	at android.view.View.updateDisplayListIfDirty(View.java:21389)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
	at android.view.View.updateDisplayListIfDirty(View.java:21349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
	at android.view.View.updateDisplayListIfDirty(View.java:21349)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:21380)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:21380)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:21380)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:21380)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:21380)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:21380)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:21380)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.draw(View.java:22538)
	at com.android.internal.policy.DecorView.draw(DecorView.java:848)
	at android.view.View.updateDisplayListIfDirty(View.java:21389)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4448)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4175)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3422)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2206)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8763)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
	at android.view.Choreographer.doFrame(Choreographer.java:1049)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
```

**Comment by cketti** [comment]
This should no longer be an issue in K-9 Mail 6.400.

**Comment by kolaente** [comment]
Can confirm as fixed
