### ISSUE TITLE
Impossible to import settings

### ISSUE THREAD

**Issue by plegrand1** [thunderbird/thunderbird-android#5988]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.913

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Xiaomi MI9

### Steps to reproduce

Parameters
Import parameters

### Expected behavior

Make it possible to import parameters

### Actual behavior

Hello,
i'm using K-9 mail 5.913 on Xiaomi MI9 (Android 11 - MIUI 12.5.1) and on a fresh reinstall i've got an error to import settings (all settings)
I've got this error message : "Echec de lecture du fichier de paramètres" (Failed to read parameter file)

### Logs

```
 Error reading settings file
 com.fsck.k9.preferences.SettingsImportExportException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT lue key="pushMod...@727:45 in java.io.InputStreamReader@e5a72f1) 
 	at com.fsck.k9.preferences.SettingsImporter.parseSettings(SettingsImporter.java:685)
 	at com.fsck.k9.preferences.SettingsImporter.getImportStreamContents(SettingsImporter.java:129)
 	at com.fsck.k9.ui.settings.import.SettingsImportViewModel.readSettings(SettingsImportViewModel.kt:357)
 	at com.fsck.k9.ui.settings.import.SettingsImportViewModel.access$readSettings(SettingsImportViewModel.kt:28)
 	at com.fsck.k9.ui.settings.import.SettingsImportViewModel$startReadSettingsFile$1$1$1.invokeSuspend(SettingsImportViewModel.kt:238)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT lue key="pushMod...@727:45 in java.io.InputStreamReader@e5a72f1) 
 	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:440)
 	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:321)
 	at com.fsck.k9.preferences.SettingsImporter.parseSettings(SettingsImporter.java:676)
 	... 12 more
```

**Comment by plegrand1** [comment]
I add here the part of my file concerned by the error (@727:45 )
I insist on the fact that I did not edit this file and that it is the result of the action "Export parameters"

```
726  </accounts>
727</k9settings>lue key="pushMode">SECOND_CLASS</value>
728        </folder>

```

**Comment by plegrand1** [comment]
Since a new reinstallation, the generated xml file seems to be correct, 
I didn't dare to try a new import for fear of having to redo all my configuration.
It's a bit incomprehensible.

**Comment by cketti** [comment]
Thanks for reporting this.

Looks like this happens when overwriting a file and writing less data than there was before.

**Comment by plegrand1** [comment]
I'm not sure to understand.
It is not an existing export file but a new backup file on which I have the problem.

**Comment by cketti** [comment]
Your settings file doesn't contain valid XML. That's why it can't be imported. That K-9 Mail can't import broken files is not a bug. However, the app should not create broken files.

I was able to generate such a broken file by doing the following:

1. Set up an account in K-9 Mail
2. Go to *Settings → Export settings* and export everything (general settings + account)
3. Go back to the *Settings* screen, then to *Export settings* again
4. Deselect the account so that only *General settings* is selected
5. Press the *Export* button
6. In the system dialog to select a location for the settings, select the file you have exported the settings to in step 2
7. Confirm that you want to overwrite the file
8. You should end up with a file that is smaller than the original file (because now it should only contain general settings instead of general settings and the account settings). But that's not the case. Only the beginning of the file is overwritten. The rest of the file wasn't touched and contains data from the export in step 2.

**Comment by cketti** [comment]
You should be able to manually fix your settings file by removing everything after the first occurrence of `</k9settings>`. That should allow you to import those settings without an error.

**Comment by plegrand1** [comment]
you are right,
I redid the manipulation and indeed the export takes place correctly as soon as I create a new file.
I didn't remember that the last time I exported, I was overwriting an existing file.
