### ISSUE TITLE
Crash when confirm delete dialog after rotate

### ISSUE THREAD

**Issue by rezazarchi** [thunderbird/thunderbird-android#6004]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.915

### Where did you get the app from?

Other

### Android version

8.1.0

### Device model

Android Emulator

### Steps to reproduce

1. Go to settings
2. Go to General Settings
3. Go to Interactions
4. Enable Delete Confirm action
5. Come back to the messages list
6. select a message
7. click on the Delete icon
8. rotate the device
9. Click on Yes

### Expected behavior

Delete should happen successfully

### Actual behavior

Crash!

### Logs

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fsck.k9.debug, PID: 7717
    java.lang.NullPointerException
        at com.fsck.k9.fragment.MessageListFragment.doPositiveClick(MessageListFragment.kt:1163)
        at com.fsck.k9.fragment.ConfirmationDialogFragment.onClick(ConfirmationDialogFragment.java:80)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by rezazarchi** [comment]
This issue also exists for Spam confirmation dialog
