### ISSUE TITLE
Regression: Cannot send message: `SocketException: Connection reset`

### ISSUE THREAD

**Issue by ByteHamster** [thunderbird/thunderbird-android#6048]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

main branch (d93f690c0e016e324c44abe36f8cf8fa32a39114)

### Where did you get the app from?

Other

### Android version

Android 11 (LineageOS)

### Device model

OnePlus 3T

### Steps to reproduce

1. Compose E-Mail
2. Press "send" button

(see logs section for `git bisect`)

### Expected behavior

E-Mail is sent.

### Actual behavior

I get a notification saying `SocketException: Connection reset` and the message stays in the outbox.

### Output from `git bisect`:

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 2f258d6886f5c7d4d1130e0a3248f8757ef116e8
> 56da545493cd53bc89b5ddec4c2086ab53284710
> We cannot bisect more!

### Logcat:

```
MessagingController: Running command 'sendPendingMessages', seq = 3 (background priority)
LocalMessage: No headers available for this message!
LocalMessage: No headers available for this message!
MessagingController: Scanning Outbox folder for messages to send
MessagingController: Send count for message K9LOCAL:1cca1e67-5b6d-4310-86d9-5c828adb4f75 is 0
LockableDatabase: LockableDatabase: Transaction ended, took 25 ms / com.fsck.k9.mailstore.LocalMessage.setFlag(LocalMessage.java:260)
MessagingController: Sending message with UID K9LOCAL:1cca1e67-5b6d-4310-86d9-5c828adb4f75
SmtpTransport: SMTP >>> QUIT
SmtpTransport: SMTP <<< 220 redacted.com ESMTP Postfix (Debian/GNU)
SmtpTransport: SMTP >>> EHLO [127.0.0.1]
CompatibilityChangeReporter: Compat change id reported: 150939131; UID 10512; state: ENABLED
SmtpTransport: SMTP <<< 250-redacted.com
SmtpTransport: SMTP <<< 250-PIPELINING
SmtpTransport: SMTP <<< 250-SIZE 52428800
SmtpTransport: SMTP <<< 250-ETRN
SmtpTransport: SMTP <<< 250-STARTTLS
SmtpTransport: SMTP <<< 250-ENHANCEDSTATUSCODES
SmtpTransport: SMTP <<< 250-8BITMIME
SmtpTransport: SMTP <<< 250-DSN
SmtpTransport: SMTP <<< 250 CHUNKING
SmtpTransport: SMTP >>> STARTTLS
SmtpTransport: SMTP <<< 220 2.0.0 Ready to start TLS
DefaultTrustedSocketFactory: Could not call SSLSocket#setHostname(String) method 
DefaultTrustedSocketFactory: java.lang.NoSuchMethodException: com.android.org.conscrypt.Java8EngineSocket.setHostname [class java.lang.String]
DefaultTrustedSocketFactory: 	at java.lang.Class.getMethod(Class.java:2072)
DefaultTrustedSocketFactory: 	at java.lang.Class.getMethod(Class.java:1693)
DefaultTrustedSocketFactory: 	at com.fsck.k9.mail.ssl.DefaultTrustedSocketFactory.setHostnameViaReflection(DefaultTrustedSocketFactory.java:158)
DefaultTrustedSocketFactory: 	at com.fsck.k9.mail.ssl.DefaultTrustedSocketFactory.setSniHost(DefaultTrustedSocketFactory.java:152)
DefaultTrustedSocketFactory: 	at com.fsck.k9.mail.ssl.DefaultTrustedSocketFactory.createSocket(DefaultTrustedSocketFactory.java:133)
DefaultTrustedSocketFactory: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open(SmtpTransport.kt:131)
DefaultTrustedSocketFactory: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.kt:349)
DefaultTrustedSocketFactory: 	at com.fsck.k9.backend.imap.ImapBackend.sendMessage(ImapBackend.kt:153)
DefaultTrustedSocketFactory: 	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:1559)
DefaultTrustedSocketFactory: 	at com.fsck.k9.controller.MessagingController$7.run(MessagingController.java:1449)
DefaultTrustedSocketFactory: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:222)
DefaultTrustedSocketFactory: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:108)
DefaultTrustedSocketFactory: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
DefaultTrustedSocketFactory: 	at java.lang.Thread.run(Thread.java:923)
SmtpTransport: SMTP >>> EHLO [127.0.0.1]
SmtpTransport: SMTP >>> QUIT
MessagingController: Failed to send message
MessagingController: com.fsck.k9.mail.MessagingException: Unable to open connection to SMTP server.
MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open(SmtpTransport.kt:251)
MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.kt:349)
MessagingController: 	at com.fsck.k9.backend.imap.ImapBackend.sendMessage(ImapBackend.kt:153)
MessagingController: 	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:1559)
MessagingController: 	at com.fsck.k9.controller.MessagingController$7.run(MessagingController.java:1449)
MessagingController: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:222)
MessagingController: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:108)
MessagingController: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
MessagingController: 	at java.lang.Thread.run(Thread.java:923)
MessagingController: Caused by: java.net.SocketException: Connection reset
MessagingController: 	at java.net.SocketInputStream.read(SocketInputStream.java:215)
MessagingController: 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
MessagingController: 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
MessagingController: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:267)
MessagingController: 	at com.fsck.k9.mail.filter.PeekableInputStream.read(PeekableInputStream.java:27)
MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.readByte(SmtpResponseParser.kt:266)
MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.readChar(SmtpResponseParser.kt:274)
MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.readDigit(SmtpResponseParser.kt:254)
MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.readReplyCode1(SmtpResponseParser.kt:234)
MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.readReplyCode(SmtpResponseParser.kt:230)
MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.readHelloResponse(SmtpResponseParser.kt:36)
MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendHello(SmtpTransport.kt:306)
MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open(SmtpTransport.kt:142)
MessagingController: 	... 8 more
LockableDatabase: LockableDatabase: Transaction ended, took 11 ms / com.fsck.k9.mailstore.LocalMessage.setFlag(LocalMessage.java:260)
LockableDatabase: LockableDatabase: Transaction ended, took 14 ms / com.fsck.k9.mailstore.LocalFolder.destroyMessage(LocalFolder.java:1002)
LockableDatabase: LockableDatabase: Transaction ended, took 13 ms / com.fsck.k9.mailstore.LocalFolder.destroyMessage(LocalFolder.java:1002)
MessagingController:  Command 'sendPendingMessages' completed
```

**Comment by cketti** [comment]
Thanks for doing the bisect :heart:
