### ISSUE TITLE
Crashes when opening mail due to autocrypt

### ISSUE THREAD

**Issue by rugk** [thunderbird/thunderbird-android#6071]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.000

### Where did you get the app from?

F-Droid

### Android version

Android 12, CalyxOS 3.5.1  

### Device model

Pixel 4 (flame)  

### Steps to reproduce

I open a mail with an OpenPGP key attached (and an attached OpenPGP signature)

### Expected behavior

Not crash.

### Actual behavior

Crashes.

Always reproduxible.

### Logs

```
FATAL EXCEPTION: main
Process: com.fsck.k9, PID: 15293
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.fsck.k9.autocrypt.AutocryptOperations.addAutocryptPeerUpdateToIntentIfPresent(AutocryptOperations.java:46)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.processAutocryptHeaderForCurrentPart(MessageCryptoHelper.java:311)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.nextStep(MessageCryptoHelper.java:224)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$300(MessageCryptoHelper.java:58)
	at com.fsck.k9.ui.crypto.MessageCryptoHelper$1.onBound(MessageCryptoHelper.java:242)
	at org.openintents.openpgp.util.OpenPgpServiceConnection$1.onServiceConnected(OpenPgpServiceConnection.java:81)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Catched with scoop

More log:
```
crash
05-16 21:54:42.366  7506  7506 E AndroidRuntime: FATAL EXCEPTION: main
05-16 21:54:42.366  7506  7506 E AndroidRuntime: Process: com.fsck.k9, PID: 7506
05-16 21:54:42.366  7506  7506 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at com.fsck.k9.autocrypt.AutocryptOperations.addAutocryptPeerUpdateToIntentIfPresent(AutocryptOperations.java:46)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.processAutocryptHeaderForCurrentPart(MessageCryptoHelper.java:311)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.nextStep(MessageCryptoHelper.java:224)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$300(MessageCryptoHelper.java:58)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper$1.onBound(MessageCryptoHelper.java:242)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at org.openintents.openpgp.util.OpenPgpServiceConnection$1.onServiceConnected(OpenPgpServiceConnection.java:81)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-16 21:54:42.366  7506  7506 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: FATAL EXCEPTION: main
05-16 21:54:54.820 15084 15084 E AndroidRuntime: Process: com.fsck.k9, PID: 15084
05-16 21:54:54.820 15084 15084 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at com.fsck.k9.autocrypt.AutocryptOperations.addAutocryptPeerUpdateToIntentIfPresent(AutocryptOperations.java:46)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.processAutocryptHeaderForCurrentPart(MessageCryptoHelper.java:311)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.nextStep(MessageCryptoHelper.java:224)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$300(MessageCryptoHelper.java:58)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper$1.onBound(MessageCryptoHelper.java:242)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at org.openintents.openpgp.util.OpenPgpServiceConnection$1.onServiceConnected(OpenPgpServiceConnection.java:81)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-16 21:54:54.820 15084 15084 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
--------- beginning of main
05-16 21:55:18.001 15293 15293 D CompatibilityChangeReporter: Compat change id reported: 150939131; UID 10187; state: ENABLED
05-16 21:55:18.001 15293 15362 D CompatibilityChangeReporter: Compat change id reported: 150939131; UID 10187; state: ENABLED
05-16 21:55:19.551 15293 15293 D AndroidRuntime: Shutting down VM
05-16 21:55:19.551 15293 15293 E AndroidRuntime: FATAL EXCEPTION: main
05-16 21:55:19.551 15293 15293 E AndroidRuntime: Process: com.fsck.k9, PID: 15293
05-16 21:55:19.551 15293 15293 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at com.fsck.k9.autocrypt.AutocryptOperations.addAutocryptPeerUpdateToIntentIfPresent(AutocryptOperations.java:46)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.processAutocryptHeaderForCurrentPart(MessageCryptoHelper.java:311)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.nextStep(MessageCryptoHelper.java:224)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$300(MessageCryptoHelper.java:58)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper$1.onBound(MessageCryptoHelper.java:242)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at org.openintents.openpgp.util.OpenPgpServiceConnection$1.onServiceConnected(OpenPgpServiceConnection.java:81)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-16 21:55:19.551 15293 15293 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-16 21:55:19.567 15293 15293 I Process : Sending signal. PID: 15293 SIG: 9
05-16 21:55:20.618 15381 15381 E com.fsck.k9: Not starting debugger since process cannot load the jdwp agent.
05-16 21:55:20.620 15381 15381 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
05-16 21:55:20.626 15381 15381 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10187; state: ENABLED
05-16 21:55:20.638 15381 15381 V GraphicsEnvironment: ANGLE Developer option for 'com.fsck.k9' set to: 'default'
05-16 21:55:20.638 15381 15381 V GraphicsEnvironment: ANGLE GameManagerService for com.fsck.k9: false
05-16 21:55:20.638 15381 15381 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
05-16 21:55:20.639 15381 15381 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
05-16 21:55:20.639 15381 15381 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
05-16 21:55:20.667 15381 15381 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10187; state: ENABLED
05-16 21:55:20.699 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
05-16 21:55:20.700 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
05-16 21:55:20.700 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setHostname(Ljava/lang/String;)V (max-target-q, reflection, denied)
05-16 21:55:21.602 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
05-16 21:55:21.602 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
05-16 21:55:21.602 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setHostname(Ljava/lang/String;)V (max-target-q, reflection, denied)
05-16 21:55:22.011 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
05-16 21:55:22.011 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
05-16 21:55:22.011 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setHostname(Ljava/lang/String;)V (max-target-q, reflection, denied)
05-16 21:55:22.401 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
05-16 21:55:22.401 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
05-16 21:55:22.401 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setHostname(Ljava/lang/String;)V (max-target-q, reflection, denied)
05-16 21:55:22.811 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
05-16 21:55:22.811 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
05-16 21:55:22.811 15381 15398 W com.fsck.k9: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setHostname(Ljava/lang/String;)V (max-target-q, reflection, denied)
05-16 21:55:23.818 15381 15381 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10187; state: ENABLED
05-16 21:55:23.858 15381 15450 I AdrenoGLES-0: QUALCOMM build                   : 85da404, I46ff5fc46f
05-16 21:55:23.858 15381 15450 I AdrenoGLES-0: Build Date                       : 11/30/20
05-16 21:55:23.858 15381 15450 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.01
05-16 21:55:23.858 15381 15450 I AdrenoGLES-0: Local Branch                     : promo490_3_Google
05-16 21:55:23.858 15381 15450 I AdrenoGLES-0: Remote Branch                    : 
05-16 21:55:23.858 15381 15450 I AdrenoGLES-0: Remote Branch                    : 
05-16 21:55:23.858 15381 15450 I AdrenoGLES-0: Reconstruct Branch               : 
05-16 21:55:23.858 15381 15450 I AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
05-16 21:55:23.858 15381 15450 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
05-16 21:55:23.858 15381 15450 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
05-16 21:55:23.861 15381 15450 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
05-16 21:55:23.862 15381 15450 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
05-16 21:55:23.862 15381 15450 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
05-16 21:55:23.868 15381 15450 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
05-16 21:55:23.871 15381 15458 I Gralloc4: Adding additional valid usage bits: 0x0
05-16 21:57:59.907 15381 15450 D OpenGLRenderer: endAllActiveAnimators on 0xb400007639c30720 (ConstraintLayout) with handle 0xb400007549c79f30
05-16 21:58:02.195 15381 15450 D OpenGLRenderer: endAllActiveAnimators on 0xb400007639cb4d10 (FrameLayout) with handle 0xb400007549c73d80
05-16 21:58:45.421 15381 15450 D OpenGLRenderer: endAllActiveAnimators on 0xb400007639cab290 (RippleDrawable) with handle 0xb400007549c80080
05-16 21:58:47.273 15381 15381 D CompatibilityChangeReporter: Compat change id reported: 150939131; UID 10187; state: ENABLED
05-16 21:59:44.795 15381 15381 W Choreographer: Frame time is 0.009726 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
05-16 22:00:39.245 15381 15450 D OpenGLRenderer: endAllActiveAnimators on 0xb400007639dbb250 (FrameLayout) with handle 0xb400007549cb32c0
05-16 22:00:42.786 15381 15840 I K9StorageEditor: Committing preference changes
05-16 22:00:42.790 15381 15840 I K9StorageEditor: Preferences commit took 4 ms
05-16 22:00:45.176 15381 15450 D OpenGLRenderer: endAllActiveAnimators on 0xb400007639de9030 (RippleDrawable) with handle 0xb400007549cb32c0
05-16 22:00:45.563 15381 15398 I MessagingController: Running command 'clearNotifications', seq = 22 (foreground priority)
05-16 22:00:45.563 15381 15398 I MessagingController:  Command 'clearNotifications' completed
05-16 22:00:47.505 15381 15381 D MessageViewFragment: MessageView displaying message MessageReference(accountUuid=1146743b-86ca-4fec-ad55-2bfd72c2ec3b, folderId=21, uid=1826)
05-16 22:00:47.506 15381 15381 D MessageLoaderHelper: Creating new local message loader
05-16 22:00:47.616 15381 15381 E Address : MimeException in Address.parse()
05-16 22:00:47.616 15381 15381 E Address : org.apache.james.mime4j.field.address.ParseException: org.apache.james.mime4j.field.address.TokenMgrError: Lexical error at line 1, column 12.  Encountered: "\ufffd" (65533), after : ""
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList(AddressListParser.java:41)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.DefaultAddressParser.parseAddressList(DefaultAddressParser.java:69)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.mail.Address.parse(Address.java:139)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.mail.internet.MimeMessage.getFrom(MimeMessage.java:292)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.view.MessageHeader.populate(MessageHeader.java:225)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.ui.messageview.MessageTopView.setHeaders(MessageTopView.java:211)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment.displayHeaderForLoadingMessage(MessageViewFragment.java:275)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment.access$500(MessageViewFragment.java:62)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.ui.messageview.MessageViewFragment$6.onMessageDataLoadFinished(MessageViewFragment.java:768)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper.onLoadMessageFromDatabaseFinished(MessageLoaderHelper.java:222)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper.access$600(MessageLoaderHelper.java:76)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:283)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.activity.MessageLoaderHelper$1.onLoadFinished(MessageLoaderHelper.java:258)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.loader.content.Loader.deliverResult(Loader.java:132)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:46)
05-16 22:00:47.616 15381 15381 E Address : 	at com.fsck.k9.ui.message.LocalMessageLoader.deliverResult(LocalMessageLoader.java:16)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
05-16 22:00:47.616 15381 15381 E Address : 	at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
05-16 22:00:47.616 15381 15381 E Address : 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-16 22:00:47.616 15381 15381 E Address : 	at android.os.Looper.loopOnce(Looper.java:201)
05-16 22:00:47.616 15381 15381 E Address : 	at android.os.Looper.loop(Looper.java:288)
05-16 22:00:47.616 15381 15381 E Address : 	at android.app.ActivityThread.main(ActivityThread.java:7870)
05-16 22:00:47.616 15381 15381 E Address : 	at java.lang.reflect.Method.invoke(Native Method)
05-16 22:00:47.616 15381 15381 E Address : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-16 22:00:47.616 15381 15381 E Address : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-16 22:00:47.616 15381 15381 E Address : Caused by: org.apache.james.mime4j.field.address.TokenMgrError: Lexical error at line 1, column 12.  Encountered: "\ufffd" (65533), after : ""
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParserTokenManager.getNextToken(AddressListParserTokenManager.java:879)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.jj_scan_token(AddressListParser.java:857)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.jj_3R_11(AddressListParser.java:656)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.jj_3R_9(AddressListParser.java:719)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.jj_3R_8(AddressListParser.java:674)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.jj_3_1(AddressListParser.java:681)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.jj_2_1(AddressListParser.java:641)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.address(AddressListParser.java:167)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.address_list(AddressListParser.java:110)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList0(AddressListParser.java:85)
05-16 22:00:47.616 15381 15381 E Address : 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList(AddressListParser.java:38)
05-16 22:00:47.616 15381 15381 E Address : 	... 33 more
05-16 22:00:47.641 15381 15381 D AndroidRuntime: Shutting down VM
05-16 22:00:47.641 15381 15381 E AndroidRuntime: FATAL EXCEPTION: main
05-16 22:00:47.641 15381 15381 E AndroidRuntime: Process: com.fsck.k9, PID: 15381
05-16 22:00:47.641 15381 15381 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at com.fsck.k9.autocrypt.AutocryptOperations.addAutocryptPeerUpdateToIntentIfPresent(AutocryptOperations.java:46)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.processAutocryptHeaderForCurrentPart(MessageCryptoHelper.java:311)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.nextStep(MessageCryptoHelper.java:224)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$300(MessageCryptoHelper.java:58)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at com.fsck.k9.ui.crypto.MessageCryptoHelper$1.onBound(MessageCryptoHelper.java:242)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at org.openintents.openpgp.util.OpenPgpServiceConnection$1.onServiceConnected(OpenPgpServiceConnection.java:81)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-16 22:00:47.641 15381 15381 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-16 22:00:47.659 15381 15381 I Process : Sending signal. PID: 15381 SIG: 9
05-16 22:00:48.712 16776 16776 E com.fsck.k9: Not starting debugger since process cannot load the jdwp agent.
05-16 22:00:48.713 16776 16776 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
05-16 22:00:48.719 16776 16776 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10187; state: ENABLED
05-16 22:00:48.743 16776 16776 V GraphicsEnvironment: ANGLE Developer option for 'com.fsck.k9' set to: 'default'
05-16 22:00:48.744 16776 16776 V GraphicsEnvironment: ANGLE GameManagerService for com.fsck.k9: false
05-16 22:00:48.744 16776 16776 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
05-16 22:00:48.744 16776 16776 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
05-16 22:00:48.745 16776 16776 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
05-16 22:00:48.778 16776 16776 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10187; state: ENABLED
05-16 22:00:48.785 16776 16776 V K9JobManager: scheduling all jobs
05-16 22:00:48.785 16776 16776 V K9JobManager: canceling mail sync job
05-16 22:00:48.785 16776 16776 V MailSyncWorkerManager: Scheduling mail sync worker for 1146743b-86ca-4fec-ad55-2bfd72c2ec3b
05-16 22:00:48.785 16776 16776 V MailSyncWorkerManager:   sync interval: 360 minutes
05-16 22:00:48.793 16776 16776 V MailSyncWorkerManager:   last sync time: Mo. Mai 16 19:43:00 MESZ 2022
05-16 22:00:48.793 16776 16776 V MailSyncWorkerManager:   initial delay: 13332176 ms
05-16 22:00:48.795 16776 16776 V MessageProvider: Registering content resolver notifier
```

**Comment by cketti** [comment]
Is the message missing a `From` header field?

**Comment by rugk** [comment]
I have no idea anymore. It's more than a month since I have created this issue and I don't know if I'd even find that mail anymore. Could be that it has some invalid headers, sure, you should always expect that…
