### ISSUE TITLE
Sync error when encountering UTF-8 data in BODYSTRUCTURE response

### ISSUE THREAD

**Issue by Kcchouette** [thunderbird/thunderbird-android#6291]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.301

### Where did you get the app from?

Google Play

### Android version

11

### Device model

Mi A3

### Steps to reproduce

Synchronize the "INBOX" folder

### Expected behavior

Synchronize the "INBOX" folder with success

### Actual behavior

Does not synchronize the folder, failed silently, traceback in logs

### Logs

```
09-10 09:26:33.894 22121 22144 D ImapSync: SYNC: Synced unsynced messages for folder INBOX
09-10 09:26:33.895 22121 22144 D ImapSync: SYNC: Have 12 large messages and 0 small messages out of 12 unsynced messages
09-10 09:26:33.895 22121 22144 D ImapSync: SYNC: Fetching 0 small messages for folder INBOX
09-10 09:26:33.895 22121 22144 D ImapSync: SYNC: Done fetching small messages for folder INBOX
09-10 09:26:33.895 22121 22144 D ImapSync: SYNC: Fetching large messages for folder INBOX
09-10 09:26:33.896 22121 22144 V RealImapConnection: conn151459594>>> 13 UID FETCH 1896,1898,1900,1902,1905,1906,1907,1908,1909,1911,1913,1915 (UID BODYSTRUCTURE)
09-10 09:26:33.910 22121 22144 V RealImapConnection: conn151459594<<<#null# [1535, FETCH, [UID, 1896, BODYSTRUCTURE, [[[TEXT, PLAIN, [CHARSET, utf-8], NIL, NIL, QUOTED-PRINTABLE, 11050, 148, NIL, NIL, NIL, NIL], [TEXT, HTML, [CHARSET, utf-8], NIL, NIL, QUOTED-PRINTABLE, 21720, 384, NIL, NIL, NIL, NIL], ALTERNATIVE, [BOUNDARY, <REMOVE>], NIL, NIL, NIL], [APPLICATION, PDF, [NAME, Ing��nieur ��tude et d��veloppement.pdf], NIL, NIL, BASE64, 114774, NIL, [ATTACHMENT, [FILENAME, Ing��nieur ��tude et d��veloppement.pdf]], NIL, NIL], MIXED, [BOUNDARY, <REMOVE>], NIL, NIL, NIL]]]
09-10 09:26:33.911 22121 22144 E ImapSync: synchronizeMailbox
09-10 09:26:33.911 22121 22144 E ImapSync: java.lang.IllegalArgumentException: Unsupported character: �
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.mail.internet.MimeParameterEncoder.quoted(MimeParameterEncoder.kt:161)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.parseBodyStructure(RealImapFolder.kt:894)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.parseBodyStructure(RealImapFolder.kt:830)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.handleFetchResponse(RealImapFolder.kt:748)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.fetch(RealImapFolder.kt:599)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.downloadLargeMessages(ImapSync.kt:561)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.downloadMessages(ImapSync.kt:367)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:198)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:55)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:644)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:584)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.controller.MessagingController.lambda$synchronizeMailbox$3(MessagingController.java:556)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.controller.MessagingController.$r8$lambda$ar_6eNiqt1c67rfo1nCyGoIX3Sg(Unknown Source:0)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda20.run(Unknown Source:10)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:223)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:109)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:164)
09-10 09:26:33.911 22121 22144 E ImapSync: 	at java.lang.Thread.run(Thread.java:923)
09-10 09:26:33.924 22121 22144 E ImapSync: Failed synchronizing folder <REMOVE>:INBOX @ Sat Sep 10 09:26:33 GMT+02:00 2022
09-10 09:26:33.924 22121 22144 I MessagingController:  Command 'synchronizeMailbox' completed
09-10 09:26:33.924 22121 22144 I MessagingController: Running command 'sendPendingMessages', seq = 46 (background priority)
09-10 09:26:33.926 22121 22144 I MessagingController:  Command 'sendPendingMessages' completed
```

**Comment by cketti** [comment]
It looks like the IMAP server is not properly encoding non-ASCII characters. 

Who is your email provider? Do you know what server software they are using?

**Comment by Kcchouette** [comment]
@cketti it's "laposte.net" for this problem.

If I can find the information by myself maybe I can help you to guess the server software, but I don't think they'll give me if I ask

FYI The same email in thunderbird is okay

**Comment by xax** [comment]
[AppVersion: 6.303 (GooglePlay), Android v12]

I seem to encounter the same problem as @Kcchouette in https://github.com/thundernest/k-9/issues/6291#issue-1368551354.

E-Mails do not show up in inbox, as their download after/during sync fails – apparently due to encoding issues with Umlauts in attachment names:
```
000008B0    6E 65 20 47 65 73 63 68 EF BF BD 66 74 73 62 65    neGesch...ftsbe
000008C0    64 69 6E 67 75 6E 67 65 6E 2E 70 64 66 5D 2C 20    dingungen.pdf],
```

```
09-12 19:37:59.369 13678 13697 D ImapSync: SYNC: Synced unsynced messages for folder INBOX
09-12 19:37:59.369 13678 13697 D ImapSync: SYNC: Have 18 large messages and 0 small messages out of 18 unsynced messages
09-12 19:37:59.369 13678 13697 D ImapSync: SYNC: Fetching 0 small messages for folder INBOX
09-12 19:37:59.369 13678 13697 D ImapSync: SYNC: Done fetching small messages for folder INBOX
09-12 19:37:59.369 13678 13697 D ImapSync: SYNC: Fetching large messages for folder INBOX
09-12 19:37:59.370 13678 13697 V RealImapConnection: conn208538447>>> 8 UID FETCH 10010,10011,10012,10013,10015,10019,10021,10023,10024,10026,10030,10031,10043,10044,10046,10048,10049,10050 (UID BODYSTRUCTURE)
09-12 19:37:59.414 13678 13697 V RealImapConnection: conn208538447<<<#null# [1386, FETCH, [UID, 10010, BODYSTRUCTURE, [[[TEXT, plain, [charset, windows-1252], NIL, NIL, BASE64, 2530, 41, NIL, [inline, NIL], NIL, NIL], [[TEXT, html, [charset, windows-1252], NIL, NIL, BASE64, 17382, 281, NIL, [inline, NIL], NIL, NIL], [IMAGE, png, [name, ABCD.png], <ABCD.png>, NIL, BASE64, 67978, NIL, [inline, [filename, ABCD.png]], NIL, NIL], related, [boundary, ----------=_1662453267-18322-2], NIL, NIL, NIL], alternative, [boundary, ----------=_1662453267-18322-1], NIL, NIL, NIL], mixed, [boundary, ----------=_1662453267-18322-0], NIL, NIL, NIL]]]
09-12 19:37:59.417 13678 13697 V RealImapConnection: conn208538447<<<#null# [1387, FETCH, [UID, 10011, BODYSTRUCTURE, [[[TEXT, plain, [charset, windows-1252], NIL, NIL, BASE64, 3510, 57, NIL, [inline, NIL], NIL, NIL], [[TEXT, html, [charset, windows-1252], NIL, NIL, BASE64, 22230, 359, NIL, [inline, NIL], NIL, NIL], [IMAGE, png, [name, ABCD.png], <ABCD.png>, NIL, BASE64, 67978, NIL, [inline, [filename, ABCD.png]], NIL, NIL], related, [boundary, ----------=_1662453269-18322-5], NIL, NIL, NIL], alternative, [boundary, ----------=_1662453269-18322-4], NIL, NIL, NIL], [APPLICATION, pdf, [name, Rechnung_ABCD_12345678.pdf], NIL, NIL, BASE64, 233534, NIL, [attachment, [filename, Rechnung_ABCD_12345678.pdf]], NIL, NIL], [APPLICATION, pdf, [name, Widerruf.pdf], NIL, NIL, BASE64, 133152, NIL, [attachment, [filename, Widerruf.pdf]], NIL, NIL], [APPLICATION, pdf, [name, Allgemeine Gesch�ftsbedingungen.pdf], NIL, NIL, BASE64, 202054, NIL, [attachment, [filename, Allgemeine Gesch�ftsbedingungen.pdf]], NIL, NIL], mixed, [boundary, ----------=_1662453269-18322-3], NIL, NIL, NIL]]]
09-12 19:37:59.417 13678 13697 E ImapSync: synchronizeMailbox
09-12 19:37:59.417 13678 13697 E ImapSync: java.lang.IllegalArgumentException: Unsupported character: �
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.mail.internet.MimeParameterEncoder.quoted(MimeParameterEncoder.kt:161)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.parseBodyStructure(RealImapFolder.kt:894)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.parseBodyStructure(RealImapFolder.kt:830)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.handleFetchResponse(RealImapFolder.kt:748)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.fetch(RealImapFolder.kt:599)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.downloadLargeMessages(ImapSync.kt:561)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.downloadMessages(ImapSync.kt:367)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:198)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:55)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:638)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:578)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.controller.MessagingController.lambda$synchronizeMailbox$3(MessagingController.java:550)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.controller.MessagingController.$r8$lambda$ar_6eNiqt1c67rfo1nCyGoIX3Sg(Unknown Source:0)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda20.run(Unknown Source:10)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:223)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:109)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:164)
09-12 19:37:59.417 13678 13697 E ImapSync: 	at java.lang.Thread.run(Thread.java:1012)
09-12 19:37:59.420 13678 13697 E ImapSync: Failed synchronizing folder SomeGMXaccount:INBOX @ Mo. Sept. 12 19:37:59 MESZ 2022
09-12 19:37:59.420 13678 13697 I MessagingController:  Command 'synchronizeMailbox' completed
```

The mail service provider is GMX. Its IMAP server (`imap.gmx.net:993`) identifies as `IMAP server ready H migmx001 22.1.2`.

**Comment by cketti** [comment]
@xax: Can you please post the `Content-Disposition` header of the "Allgemeine Geschäftsbedingungen.pdf" part of the message?

**Comment by xax** [comment]
> @xax: Can you please post the `Content-Disposition` header of the "Allgemeine Geschäftsbedingungen.pdf" part of the message?
The main mail header states
```
Content-Type: multipart/mixed; boundary="----------=_1662453269-18322-3"
Content-Transfer-Encoding: binary
```
The certain MIME part header is the following:
```
------------=_1662453269-18322-3
Content-Type: APPLICATION/PDF; name="Allgemeine Geschäftsbedingungen.pdf"
Content-Transfer-Encoding: BASE64
Content-Disposition: attachment
X-IMAP-Size: 202054/0
```

**Comment by xax** [comment]
> E-Mails do not show up in inbox, as their download after/during sync fails – apparently due to encoding issues with Umlauts in attachment names:
> 
> ```
> 000008B0    6E 65 20 47 65 73 63 68 EF BF BD 66 74 73 62 65    neGesch...ftsbe
> 000008C0    64 69 6E 67 75 6E 67 65 6E 2E 70 64 66 5D 2C 20    dingungen.pdf],
> ```

My hex representation above is misleading, as the `EF BF BD` sequence is simply the UTF-8 encoding of the REPLACEMENT CHARACTER, probably with origin in the K9 log.

Looking at a (presumed) unaltered raw export of the e-mail, the `ä` is encoded `E4`, which represents an `ä` in CP-1252 or ISO-8852-9/-15, e.g.

**Comment by cketti** [comment]
[RFC 6532 - Internationalized Email Headers](https://www.rfc-editor.org/rfc/rfc6532) only allows UTF-8 in email headers. So if it's anything but that, it's definitely an invalid encoding and the software that the sender is using should be fixed.

For this bug, it doesn't make much difference though. We need to change the IMAP code to handle non-ASCII values in a BODYSTRUCTURE response. 
In my reading of [RFC 3501 - INTERNET MESSAGE ACCESS PROTOCOL - VERSION 4rev1](https://www.rfc-editor.org/rfc/rfc3501) it's a protocol violation ("Characters are 7-bit US-ASCII unless otherwise specified"). However, it's an easy mistake to make. And with UTF-8 in message headers becoming more common, this will happen more often. So we might as well work around this server bug.

**Comment by xax** [comment]
> For this bug, it doesn't make much difference though. We need to change the IMAP code to handle non-ASCII values in a BODYSTRUCTURE response.

What adds to the severity to the current K9 behavior is, that (modulo date span filters) as long as a _large message_ like the (offending?) one above is in a folder of an (offending‽) IMAP server, **no** _large message_ in K9's download/sync pipeline after it will be successfully downloaded and thus will never appear in the K9 IMAP folder view.
