### ISSUE TITLE
Crash at startup - beta 6.309

### ISSUE THREAD

**Issue by PhilJung** [thunderbird/thunderbird-android#6412]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.309

### Where did you get the app from?

Google Play

### Android version

Stock ROM-Android 11

### Device model

Honor Redmi Note 11S

### Steps to reproduce

Start the application.

### Expected behavior

Application started

### Actual behavior

It crashes immediately

### Logs

```
10-19 07:06:40.382 31405 31405 W com.fsck.k9: type=1400 audit(0.0:23895373): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=8110 scontext=u:r:untrusted_app:s0:c19,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.orange.owtv
10-19 07:06:40.390  1442  3852 W ActivityManager: Too many PendingIntent created for uid 10275, aborting Key{broadcastIntent pkg=com.fsck.k9 intent=act=com.fsck.k9.backends.ALARM pkg=com.fsck.k9 flags=0x4000000 u=0} requestCode=1
10-19 07:06:40.396 31405 31405 D AndroidRuntime: Shutting down VM
10-19 07:06:40.396 31405 31405 E AndroidRuntime: FATAL EXCEPTION: main
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Process: com.fsck.k9, PID: 31405
10-19 07:06:40.396 31405 31405 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.fsck.k9.App: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.fsck.k9.job.K9JobManager']
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7056)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:265)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8096)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.fsck.k9.job.K9JobManager']
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:205)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.Core$special$$inlined$inject$default$3.invoke(DI.kt:131)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.Core.getJobManager(Core.kt:17)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.Core.setServicesEnabled(Core.kt:78)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.Core.setServicesEnabled(Core.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.Core.init(Core.kt:35)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.App.onCreate(App.kt:42)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1191)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7050)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	... 8 more
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'androidx.work.WorkManager']
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:205)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.job.KoinModuleKt$jobModule$1$4.invoke(KoinModule.kt:131)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.job.KoinModuleKt$jobModule$1$4.invoke(KoinModule.kt:10)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	... 26 more
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.fsck.k9.job.WorkManagerProvider']
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:205)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.job.KoinModuleKt$jobModule$1$3.invoke(KoinModule.kt:131)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.job.KoinModuleKt$jobModule$1$3.invoke(KoinModule.kt:9)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	... 38 more
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'androidx.work.WorkerFactory']
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:205)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.job.KoinModuleKt$jobModule$1$1.invoke(KoinModule.kt:131)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.job.KoinModuleKt$jobModule$1$1.invoke(KoinModule.kt:7)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	... 50 more
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.fsck.k9.controller.MessagingController']
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:205)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.job.KoinModuleKt$jobModule$1$2.invoke(KoinModule.kt:131)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.job.KoinModuleKt$jobModule$1$2.invoke(KoinModule.kt:8)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	... 62 more
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.fsck.k9.backend.BackendManager']
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:205)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.controller.KoinModuleKt$controllerModule$1$1.invoke(KoinModule.kt:131)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.controller.KoinModuleKt$controllerModule$1$1.invoke(KoinModule.kt:16)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	... 74 more
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.fsck.k9.backends.ImapBackendFactory']
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:205)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.backends.KoinModuleKt$backendsModule$1$1.invoke(KoinModule.kt:131)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.backends.KoinModuleKt$backendsModule$1$1.invoke(KoinModule.kt:14)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	... 86 more
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.fsck.k9.mail.store.imap.IdleRefreshManager']
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:205)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.backends.KoinModuleKt$backendsModule$1$2.invoke(KoinModule.kt:131)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.backends.KoinModuleKt$backendsModule$1$2.invoke(KoinModule.kt:23)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	... 98 more
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.fsck.k9.backend.imap.SystemAlarmManager']
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:205)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.backends.KoinModuleKt$backendsModule$1$4.invoke(KoinModule.kt:131)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.backends.KoinModuleKt$backendsModule$1$4.invoke(KoinModule.kt:34)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	... 110 more
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: java.lang.SecurityException: Too many PendingIntent created for uid 10275, aborting Key{broadcastIntent pkg=com.fsck.k9 intent=act=com.fsck.k9.backends.ALARM pkg=com.fsck.k9 flags=0x4000000 u=0} requestCode=1
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2360)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2343)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2285)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6884)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:586)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:569)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.backends.AndroidAlarmManager.<init>(AndroidAlarmManager.kt:36)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.backends.AndroidAlarmManager.<init>(AndroidAlarmManager.kt:24)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.backends.KoinModuleKt$backendsModule$1$3.invoke(KoinModule.kt:33)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.fsck.k9.backends.KoinModuleKt$backendsModule$1$3.invoke(KoinModule.kt:33)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	... 122 more
10-19 07:06:40.396 31405 31405 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.android.server.am.PendingIntentController.incrementUidStatLocked(PendingIntentController.java:441)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.android.server.am.PendingIntentController.getIntentSender(PendingIntentController.java:165)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:6100)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3110)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3014)
10-19 07:06:40.396 31405 31405 E AndroidRuntime: 
```

**Comment by cketti** [comment]
That's a very strange error to get. How many accounts do you have set up? Do you have notifications enabled for those accounts?

**Comment by PhilJung** [comment]
Something like 10 accounts. Various providers.
Notification is enabled.
I was using beta version since more than 6 months so the problem is related to the very last changes

**Comment by PhilJung** [comment]
Just in case, in Android notification and control center, I don't see the k9 application

**Comment by PhilJung** [comment]
Possible to try /catch the
        PendingIntent.getBroadcast(context, REQUEST_CODE, intent, FLAG_IMMUTABLE)

In https://github.com/thundernest/k-9/blob/main/app/k9mail/src/main/java/com/fsck/k9/backends/AndroidAlarmManager.kt ?

It looks like this one:
https://stackoverflow.com/questions/71266853/xiaomi-android-11-securityexception-too-many-pendingintent-created

:-(

**Comment by PhilJung** [comment]
I upgraded from August security update to September security update which led to phone reboot.
After this k9 works well.
So I don't know if it's related to Android security patch level or to Android needing a reboot
At the end of the day, it works.

I close the issue
