### ISSUE TITLE
UnknownHostException while accessing local mail server

### ISSUE THREAD

**Issue by ego2dot0** [thunderbird/thunderbird-android#6421]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

F-Droid

### Android version

10-12 

### Device model

Fairphone 4, Nokia 5.1, Samsung A52s 

### Steps to reproduce

K9-Mail does not connect to local mail server anymore. It worked once, but does not work currently. It's an mail server which is in the local network without a public ip address. The issue exists much longer, but k9mail does not show any error, but does not receive any mails. Only if I write a mail and send it to myself I get an UknownHostException (no adress assosiated with hostname) in the notification.
The dnssec bypass by android is disabled and there are two dns records send by the dhcp server, so android is not adding 8.8.8.8 as second dns resolver. 
Accessing the server by vivendi or firefox works as expected.
The server has an lets encrypt certificate and it's working fine.

### Expected behavior

resolve dns name with local dns server. 

### Actual behavior

UknownHostException

There is access to ac88393aca5853df7.awsglobalaccelerator.com, while edit the config, but no access to any local dns servers.

**Comment by cketti** [comment]
K-9 Mail doesn't use its own name resolver. Name lookups are handled by Android. So this is most likely a configuration issue. Are you sure DNS over HTTPS is disabled? See https://www.androidpolice.com/android-dns-over-https-mainline/

**Comment by ego2dot0** [comment]
I have added the smtp command, as it's esier to trigger. Maybe there is an new option like usesCleartextTraffic for unsafe DNS?
```
10-24 17:26:46.133  6050  6067 D SmtpTransport: SMTP >>> QUIT
10-24 17:26:46.134  6050  6067 E MessagingController: Failed to send message
10-24 17:26:46.134  6050  6067 E MessagingController: com.fsck.k9.mail.MessagingException: Unable to open connection to SMTP server.
10-24 17:26:46.134  6050  6067 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open$smtp(SmtpTransport.kt:238)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.kt:369)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at com.fsck.k9.backend.imap.ImapBackend.sendMessage(ImapBackend.kt:153)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:1562)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at com.fsck.k9.controller.MessagingController$7.run(MessagingController.java:1447)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:223)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:109)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:164)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at java.lang.Thread.run(Thread.java:920)
10-24 17:26:46.134  6050  6067 E MessagingController: Caused by: java.net.UnknownHostException: Unable to resolve host "mylocalserver.domainname.top": No address associated with hostname
10-24 17:26:46.134  6050  6067 E MessagingController: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.connect(SmtpTransport.kt:243)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open$smtp(SmtpTransport.kt:89)
10-24 17:26:46.134  6050  6067 E MessagingController: 	... 8 more
10-24 17:26:46.134  6050  6067 E MessagingController: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at libcore.io.Linux.android_getaddrinfo(Native Method)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
10-24 17:26:46.134  6050  6067 E MessagingController: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
10-24 17:26:46.134  6050  6067 E MessagingController: 	... 12 more
```

**Comment by cketti** [comment]
The stack trace shows that a framework class, i.e. the OS, is performing the name lookup. You'll have to figure out on your own why that is not working. This is not a K-9 Mail issue.
