### ISSUE TITLE
NoSuchMethodException: com.android.org.conscrypt.Java8EngineSocket.setHostname

### ISSUE THREAD

**Issue by mesonium** [thunderbird/thunderbird-android#6472]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.301

### Where did you get the app from?

F-Droid

### Android version

Android 13 (CalyxOS)

### Device model

Google Pixel 6a

### Steps to reproduce

Synchronize an IMAP folder.

### Expected behavior

Folder is synced and mails are fetched.

### Actual behavior

No mails are fetched in the end. Not sure if this, the other bug https://github.com/thundernest/k-9/issues/6471 is the root cause or both are the root cause.

### Logs

```
16:34:15.714 I/MessagingController( 5526): Running command 'synchronizeMailbox', seq = 50 (background priority)
16:34:15.715 D/MessagingController( 5526): Last folder list refresh @ So. Nov. 13 16:16:13 MEZ 2022. Not refreshing now.
16:34:15.716 I/ImapSync( 5526): Synchronizing folder <snip>:INBOX
16:34:15.716 V/ImapSync( 5526): SYNC: About to get local folder INBOX
16:34:15.716 V/ImapSync( 5526): SYNC: About to get remote folder INBOX
16:34:15.717 V/ImapSync( 5526): SYNC: About to open remote folder INBOX
16:34:15.828 D/RealImapConnection( 5526): Connecting to posteo.de as posteo.de/2a05:bc0:1000:80::169:1
16:34:15.828 D/TrafficStats( 5526): tagSocket(90) with statsTag=0xffffffff, statsUid=-1
16:34:15.933 V/RealImapConnection( 5526): conn104338777 <<< #null# [OK, [CAPABILITY, IMAP4rev1, LITERAL+, SASL-IR, LOGIN-REFERRALS, ID, ENABLE, IDLE, STARTTLS, LOGINDISABLED], Dovecot ready.]
16:34:15.934 D/RealImapConnection( 5526): Saving [LITERAL+, IMAP4REV1, LOGIN-REFERRALS, IDLE, LOGINDISABLED, SASL-IR, ID, ENABLE, STARTTLS] capabilities for conn104338777
16:34:15.934 V/RealImapConnection( 5526): conn104338777>>> 1 STARTTLS
16:34:15.973 V/ImapResponseParser( 5526): conn104338777<<<#1# [OK, Begin TLS negotiation now.]
16:34:15.974 W/com.fsck.k9( 5526): Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
16:34:15.974 W/com.fsck.k9( 5526): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
16:34:15.974 W/com.fsck.k9( 5526): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setHostname(Ljava/lang/String;)V (max-target-q, reflection, denied)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526): Could not call SSLSocket#setHostname(String) method 
16:34:15.975 E/DefaultTrustedSocketFactory( 5526): java.lang.NoSuchMethodException: com.android.org.conscrypt.Java8EngineSocket.setHostname [class java.lang.String]
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at java.lang.Class.getMethod(Class.java:2103)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at java.lang.Class.getMethod(Class.java:1724)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.helper.DefaultTrustedSocketFactory.setHostnameViaReflection(DefaultTrustedSocketFactory.java:160)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.helper.DefaultTrustedSocketFactory.setSniHost(DefaultTrustedSocketFactory.java:154)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.helper.DefaultTrustedSocketFactory.createSocket(DefaultTrustedSocketFactory.java:135)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.mail.store.imap.RealImapConnection.startTLS(RealImapConnection.java:344)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.mail.store.imap.RealImapConnection.upgradeToTls(RealImapConnection.java:334)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.mail.store.imap.RealImapConnection.upgradeToTlsIfNecessary(RealImapConnection.java:318)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.mail.store.imap.RealImapConnection.open(RealImapConnection.java:139)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.mail.store.imap.RealImapConnection.sendCommand(RealImapConnection.java:816)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.java:759)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.java:748)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.mail.store.imap.RealImapFolder.executeSimpleCommand(RealImapFolder.kt:86)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.mail.store.imap.RealImapFolder.internalOpen(RealImapFolder.kt:120)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.mail.store.imap.RealImapFolder.open(RealImapFolder.kt:91)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:81)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:55)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:644)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:584)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.controller.MessagingController.lambda$synchronizeMailbox$3(MessagingController.java:556)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.controller.MessagingController.$r8$lambda$ar_6eNiqt1c67rfo1nCyGoIX3Sg(Unknown Source:0)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda20.run(Unknown Source:10)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:223)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:109)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:164)
16:34:15.975 E/DefaultTrustedSocketFactory( 5526):        at java.lang.Thread.run(Thread.java:1012)
16:34:16.105 I/RealImapConnection( 5526): Updating capabilities after STARTTLS for conn104338777
16:34:16.106 V/RealImapConnection( 5526): conn104338777>>> 2 CAPABILITY
16:34:16.194 V/ImapResponseParser( 5526): conn104338777<<<#null# [CAPABILITY, IMAP4rev1, LITERAL+, SASL-IR, LOGIN-REFERRALS, ID, ENABLE, IDLE, AUTH=PLAIN, AUTH=LOGIN]
16:34:16.194 V/ImapResponseParser( 5526): conn104338777<<<#2# [OK, Pre-login capabilities listed, post-login capabilities have more.]
16:34:16.195 D/RealImapConnection( 5526): Saving [AUTH=PLAIN, LITERAL+, IMAP4REV1, LOGIN-REFERRALS, IDLE, AUTH=LOGIN, SASL-IR, ID, ENABLE] capabilities for conn104338777
16:34:16.195 V/RealImapConnection( 5526): conn104338777>>> 3 AUTHENTICATE PLAIN
16:34:16.229 V/RealImapConnection( 5526): conn104338777<<<#+# []
```

**Comment by cketti** [comment]
Fixed by #6380
