### ISSUE TITLE
Import duplicated account

### ISSUE THREAD

**Issue by mhf1998** [thunderbird/thunderbird-android#6494]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.313-SNAPSHOT

### Where did you get the app from?

Other

### Android version

8.1

### Device model

emulator

### Steps to reproduce

1. Go to the drawer menu
2. Go to Settings
3. Go to "export settings"
4. Select our account option
5. Click export
6. Back
7. Click the "import settings" 
8. Select the file we exported from the previous step
9. Click Import
10. Enter the account password
11. Click ok, and finally, it is successfully imported and goes back to settings
  

### Expected behavior

I expected that the imported account should be replaced with the current account. Or it should not allow me to import a duplicate account at all.
or anything else that you think is better...

### Actual behavior

we see that in the accounts section, there are 2 accounts with our account name. And in the messages and all the parts, there are two separate accounts with the same name and we can switch between the accounts which are duplicated!

**Comment by mhf1998** [comment]
I also find a crash scenario in this issue.
I deleted old account then I returned to inbox and then, I selected another folder from drawer menu (for example, Sent). then app crashed.

crash log:

`
2022-11-27 16:10:45.849 11328-11328/com.fsck.k9 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fsck.k9, PID: 11328
    java.lang.NullPointerException
        at com.fsck.k9.activity.MessageList.configureDrawer(MessageList.kt:1357)
        at com.fsck.k9.activity.MessageList.initializeFromLocalSearch(MessageList.kt:1336)
        at com.fsck.k9.activity.MessageList.performSearch(MessageList.kt:665)
        at com.fsck.k9.activity.MessageList.openFolder(MessageList.kt:621)
        at com.fsck.k9.ui.K9Drawer.handleItemClickListener(K9Drawer.kt:347)
        at com.fsck.k9.ui.K9Drawer.access$handleItemClickListener(K9Drawer.kt:67)
        at com.fsck.k9.ui.K9Drawer$1.invoke(K9Drawer.kt:111)
        at com.fsck.k9.ui.K9Drawer$1.invoke(K9Drawer.kt:110)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView$createContent$2.invoke(MaterialDrawerSliderView.kt:627)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView$createContent$2.invoke(MaterialDrawerSliderView.kt:603)
        at com.mikepenz.fastadapter.FastAdapter$viewClickListener$1.onClick(FastAdapter.kt:119)
        at com.mikepenz.fastadapter.utils.EventHookUtilKt.attachToView$lambda$0(EventHookUtil.kt:49)
        at com.mikepenz.fastadapter.utils.EventHookUtilKt.$r8$lambda$UfMYnnvsh8Q2M7QQxF9GnPD3K-Y(EventHookUtil.kt)
        at com.mikepenz.fastadapter.utils.EventHookUtilKt$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by cketti** [comment]
Please open a separate issue for the crash. Make sure to include detailed instructions on how to reproduce it.

Not overwriting an existing account is intentional. Mainly it's because we don't support changing the account type (e.g. IMAP to POP3).

Allowing an account to be imported twice is supported intentionally. There is code in place that should avoid giving two accounts the same name. If that doesn't work, please open a new issue with more detailed steps on how to reproduce the bug.

**Comment by mhf1998** [comment]
> Please open a separate issue for the crash. Make sure to include detailed instructions on how to reproduce it.
> 
> Not overwriting an existing account is intentional. Mainly it's because we don't support changing the account type (e.g. IMAP to POP3).
> 
> Allowing an account to be imported twice is supported intentionally. There is code in place that should avoid giving two accounts the same name. If that doesn't work, please open a new issue with more detailed steps on how to reproduce the bug.
