### ISSUE TITLE
INBOX won't sync, all other directories are fine

### ISSUE THREAD

**Issue by rixx** [thunderbird/thunderbird-android#6571]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.501

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Pixel 6a

### Steps to reproduce

1. Go to Unified Inbox
2. Pull down (or otherwise trigger sync)
3. See rotating loading indicator for a while
4. It disappears, Unified Inbox remains empty
5. Go to actual INBOX folder
6. Pull down (or otherwise trigger sync)
7. See rotating loading indicator and "Loading messages" text for just a second
8. Both disappear, INBOX remains empty

### Expected behavior

INBOX loads and displays the four mails it contains.

### Actual behavior

Inbox remains empty, **but** also no error message is shown, so I first thought I had no new mails for a while.

Note that **all other folders** on this mailserver work, and the INBOX used to work with k9 for years, too.

I tried exporting the config, removing the server and adding the config agains, which didn't change anything.

I don't think anything on the mailserver has changed in the time this broke, but I can't 100% guarantee that. The server is running a very standard Postfix 3.7.3 with Dovecot 2.3.19. 

### Logs

```
--------- beginning of main
01-11 16:24:02.034  9145  9178 D OpenGLRenderer: endAllActiveAnimators on 0xb40000761cab8470 (FrameLayout) with handle 0xb40000752c99d8f0
01-11 16:24:02.784  9145  9145 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
01-11 16:24:02.784  9145  9145 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
01-11 16:24:04.476  9145 23591 I K9StorageEditor: Committing preference changes
01-11 16:24:04.483  9145 23591 I K9StorageEditor: Preferences commit took 10 ms
01-11 16:24:07.247  9145  9178 D OpenGLRenderer: endAllActiveAnimators on 0xb40000761c9a9190 (RippleDrawable) with handle 0xb40000752c9c5fa0
01-11 16:24:07.816  9145  9177 I MessagingController: Running command 'clearNotifications', seq = 225 (foreground priority)
01-11 16:24:07.820  9145  9177 V NotificationController: Removing some notifications for account d50c7ea9-3c78-43ea-9d88-b315ff063d62
01-11 16:24:07.821  9145  9177 I MessagingController:  Command 'clearNotifications' completed
01-11 16:24:08.352  9145  9178 D OpenGLRenderer: endAllActiveAnimators on 0xb40000761ca38550 (RippleDrawable) with handle 0xb40000752c9a65c0
01-11 16:24:09.335  9145  9177 I MessagingController: Running command 'synchronizeMailbox', seq = 226 (background priority)
01-11 16:24:09.339  9145  9177 D MessagingController: Last folder list refresh @ Wed Jan 11 16:22:53 CET 2023. Not refreshing now.
01-11 16:24:09.342  9145  9177 I ImapSync: Synchronizing folder rixx.de:INBOX
01-11 16:24:09.342  9145  9177 V ImapSync: SYNC: About to get local folder INBOX
01-11 16:24:09.344  9145  9177 V ImapSync: SYNC: About to get remote folder INBOX
01-11 16:24:09.344  9145  9177 V ImapSync: SYNC: About to open remote folder INBOX
01-11 16:24:09.417  9145  9177 D RealImapConnection: Connecting to mail.rixx.de as mail.rixx.de/78.46.142.235
01-11 16:24:09.418  9145  9177 D TrafficStats: tagSocket(235) with statsTag=0xffffffff, statsUid=-1
01-11 16:24:09.555  9145  9177 V RealImapConnection: conn205941146 <<< #null# [OK, [CAPABILITY, IMAP4rev1, SASL-IR, LOGIN-REFERRALS, ID, ENABLE, IDLE, LITERAL+, AUTH=PLAIN, AUTH=LOGIN], Dovecot ready.]
01-11 16:24:09.555  9145  9177 D RealImapConnection: Saving [AUTH=PLAIN, LITERAL+, IMAP4REV1, LOGIN-REFERRALS, IDLE, AUTH=LOGIN, SASL-IR, ID, ENABLE] capabilities for conn205941146
01-11 16:24:09.556  9145  9177 V RealImapConnection: conn205941146>>> 1 AUTHENTICATE PLAIN
01-11 16:24:09.585  9145  9177 V RealImapConnection: conn205941146<<<#+# []
01-11 16:24:09.646  9145  9177 V ImapResponseParser: conn205941146<<<#1# [OK, [CAPABILITY, IMAP4rev1, SASL-IR, LOGIN-REFERRALS, ID, ENABLE, IDLE, SORT, SORT=DISPLAY, THREAD=REFERENCES, THREAD=REFS, THREAD=ORDEREDSUBJECT, MULTIAPPEND, URL-PARTIAL, CATENATE, UNSELECT, CHILDREN, NAMESPACE, UIDPLUS, LIST-EXTENDED, I18NLEVEL=1, CONDSTORE, QRESYNC, ESEARCH, ESORT, SEARCHRES, WITHIN, CONTEXT=SEARCH, LIST-STATUS, BINARY, MOVE, SNIPPET=FUZZY, PREVIEW=FUZZY, PREVIEW, STATUS=SIZE, SAVEDATE, LITERAL+, NOTIFY, SPECIAL-USE], Logged in]
01-11 16:24:09.647  9145  9177 D RealImapConnection: Saving [URL-PARTIAL, NAMESPACE, LIST-STATUS, PREVIEW=FUZZY, THREAD=REFERENCES, BINARY, SAVEDATE, SASL-IR, WITHIN, MULTIAPPEND, SEARCHRES, ESORT, CONDSTORE, NOTIFY, STATUS=SIZE, I18NLEVEL=1, CATENATE, ID, SORT=DISPLAY, SPECIAL-USE, QRESYNC, UNSELECT, ENABLE, THREAD=ORDEREDSUBJECT, UIDPLUS, CHILDREN, CONTEXT=SEARCH, MOVE, SNIPPET=FUZZY, LITERAL+, IMAP4REV1, LOGIN-REFERRALS, IDLE, ESEARCH, SORT, LIST-EXTENDED, THREAD=REFS, PREVIEW] capabilities for conn205941146
01-11 16:24:09.647  9145  9177 V RealImapConnection: conn205941146>>> 2 EXAMINE "INBOX"
01-11 16:24:09.679  9145  9177 V ImapResponseParser: conn205941146<<<#null# [FLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft]]
01-11 16:24:09.679  9145  9177 V ImapResponseParser: conn205941146<<<#null# [OK, [PERMANENTFLAGS, []], Read-only mailbox.]
01-11 16:24:09.679  9145  9177 V ImapResponseParser: conn205941146<<<#null# [10, EXISTS]
01-11 16:24:09.680  9145  9177 V ImapResponseParser: conn205941146<<<#null# [0, RECENT]
01-11 16:24:09.680  9145  9177 V ImapResponseParser: conn205941146<<<#null# [OK, [UNSEEN, 9], First unseen.]
01-11 16:24:09.680  9145  9177 V ImapResponseParser: conn205941146<<<#null# [OK, [UIDVALIDITY, 1611407843], UIDs valid]
01-11 16:24:09.680  9145  9177 V ImapResponseParser: conn205941146<<<#null# [OK, [UIDNEXT, 17718], Predicted next UID]
01-11 16:24:09.681  9145  9177 V ImapResponseParser: conn205941146<<<#null# [OK, [HIGHESTMODSEQ, 1709], Highest]
01-11 16:24:09.683  9145  9177 V ImapResponseParser: conn205941146<<<#2# [OK, [READ-ONLY], Examine completed (0.001 + 0.000 + 0.001 secs).]
01-11 16:24:09.683  9145  9177 D RealImapFolder: Got untagged EXISTS with value 10 for d50c7ea9-3c78-43ea-9d88-b315ff063d62:INBOX/MessagingController/conn205941146
01-11 16:24:09.684  9145  9177 D RealImapFolder: Got UidNext = 17718 for d50c7ea9-3c78-43ea-9d88-b315ff063d62:INBOX/MessagingController/conn205941146
01-11 16:24:09.687  9145  9177 V ImapSync: SYNC: Remote message count for folder INBOX is 10
01-11 16:24:09.687  9145  9177 V ImapSync: SYNC: About to get messages 1 through 10 for folder INBOX
01-11 16:24:09.688  9145  9177 V RealImapConnection: conn205941146>>> 3 UID SEARCH 1:10 NOT DELETED
01-11 16:24:09.722  9145  9177 V ImapResponseParser: conn205941146<<<#null# [SEARCH, 16333, 17124, 17640, 17673, 17688, 17699, 17702, 17704, 17716, 17717]
01-11 16:24:09.722  9145  9177 V ImapResponseParser: conn205941146<<<#3# [OK, Search completed (0.001 + 0.000 secs).]
01-11 16:24:09.723  9145  9177 V ImapSync: SYNC: Got 10 messages for folder INBOX
01-11 16:24:09.724  9145  9177 V ImapSync: Message with uid 17717 has not yet been downloaded
01-11 16:24:09.724  9145  9177 V ImapSync: Message with uid 17716 has not yet been downloaded
01-11 16:24:09.725  9145  9177 V ImapSync: Message with uid 17704 has not yet been downloaded
01-11 16:24:09.725  9145  9177 V ImapSync: Message with uid 17702 has not yet been downloaded
01-11 16:24:09.725  9145  9177 V ImapSync: Message with uid 17699 has not yet been downloaded
01-11 16:24:09.726  9145  9177 V ImapSync: Message with uid 17688 has not yet been downloaded
01-11 16:24:09.726  9145  9177 V ImapSync: Message with uid 17673 has not yet been downloaded
01-11 16:24:09.727  9145  9177 V ImapSync: Message with uid 17640 has not yet been downloaded
01-11 16:24:09.727  9145  9177 V ImapSync: Message with uid 17124 has not yet been downloaded
01-11 16:24:09.728  9145  9177 V ImapSync: Message with uid 16333 has not yet been downloaded
01-11 16:24:09.728  9145  9177 D ImapSync: SYNC: Have 10 unsynced messages
01-11 16:24:09.729  9145  9177 D ImapSync: SYNC: About to fetch 10 unsynced messages for folder INBOX
01-11 16:24:09.730  9145  9177 V RealImapConnection: conn205941146>>> 4 UID FETCH 17717,17716,17704,17702,17699,17688,17673,17640,17124,16333 (UID FLAGS INTERNALDATE RFC822.SIZE BODY.PEEK[HEADER.FIELDS (date subject from content-type to cc reply-to message-id references in-reply-to list-unsubscribe X-K9mail-Identity Chat-Version)])
01-11 16:24:09.766  9145  9177 V RealImapConnection: conn205941146<<<#null# [1, FETCH, [UID, 16333, FLAGS, [\Seen], INTERNALDATE, 04-Nov-2022 22:57:24 +0100, RFC822.SIZE, 3191057, BODY, [HEADER.FIELDS, [DATE, SUBJECT, FROM, CONTENT-TYPE, TO, CC, REPLY-TO, MESSAGE-ID, REFERENCES, IN-REPLY-TO, LIST-UNSUBSCRIBE, X-K9MAIL-IDENTITY, CHAT-VERSION]], Date: Fri, 04 Nov 2022 22:57:22 +0100
01-11 16:24:09.766  9145  9177 V RealImapConnection: From: Tobias Kunze <r@rixx.de>
01-11 16:24:09.766  9145  9177 V RealImapConnection: To: R@rixx.de
01-11 16:24:09.766  9145  9177 V RealImapConnection: Subject: SUBJECT REDACTED
01-11 16:24:09.766  9145  9177 V RealImapConnection: Message-ID: <6B1300DD-3745-4491-99A7-F7251A18034F@rixx.de>
01-11 16:24:09.766  9145  9177 V RealImapConnection: Content-Type: multipart/mixed;
01-11 16:24:09.766  9145  9177 V RealImapConnection:  boundary=----QNLMDVJMOBBPRN0KNBJMU5HEPWIIR1
01-11 16:24:09.766  9145  9177 V RealImapConnection: 
01-11 16:24:09.766  9145  9177 V RealImapConnection: ]]
01-11 16:24:09.768  9145  9177 V RealImapConnection: conn205941146<<<#null# [2, FETCH, [UID, 17124, FLAGS, [\Seen], INTERNALDATE, 07-Dec-2022 21:17:09 +0100, RFC822.SIZE, 77011, BODY, [HEADER.FIELDS, [DATE, SUBJECT, FROM, CONTENT-TYPE, TO, CC, REPLY-TO, MESSAGE-ID, REFERENCES, IN-REPLY-TO, LIST-UNSUBSCRIBE, X-K9MAIL-IDENTITY, CHAT-VERSION]], From: FROM_REDACTED
01-11 16:24:09.768  9145  9177 V RealImapConnection: To: "r@rixx.de" <r@rixx.de>
01-11 16:24:09.768  9145  9177 V RealImapConnection: Subject: 
01-11 16:24:09.768  9145  9177 V RealImapConnection:  =?Windows-1252?Q?CCDB_>_SUBJECT_REDACTED_?=
01-11 16:24:09.768  9145  9177 V RealImapConnection:  =?Windows-1252?Q?poll?=
01-11 16:24:09.768  9145  9177 V RealImapConnection: Date: Wed, 7 Dec 2022 20:17:06 +0000
01-11 16:24:09.768  9145  9177 V RealImapConnection: Message-ID: 
01-11 16:24:09.768  9145  9177 V RealImapConnection:  <FR3P281MB21439E7ABC686141C04A9274FA1A9@FR3P281MB2143.DEUP281.PROD.OUTLOOK.COM>
01-11 16:24:09.768  9145  9177 V RealImapConnection: Content-Type: multipart/related;
01-11 16:24:09.768  9145  9177 V RealImapConnection: 	boundary="_004_FR3P281MB21439E7ABC686141C04A9274FA1A9FR3P281MB2143DEUP_";
01-11 16:24:09.768  9145  9177 V RealImapConnection: 	type="multipart/alternative"
01-11 16:24:09.768  9145  9177 V RealImapConnection: 
01-11 16:24:09.768  9145  9177 V RealImapConnection: ]]
01-11 16:24:09.769  9145  9177 V RealImapConnection: conn205941146<<<#null# [3, FETCH, [UID, 17640, FLAGS, [\Seen], INTERNALDATE, 06-Jan-2023 01:53:48 +0100, RFC822.SIZE, 10287017]]
01-11 16:24:09.769  9145  9177 V RealImapConnection: conn205941146<<<#null# [BYE, FETCH failed: Internal error occurred. Refer to server log for more information. [2023-01-11 16:24:09]]
01-11 16:24:09.771  9145  9177 E RealImapFolder: IOException for d50c7ea9-3c78-43ea-9d88-b315ff063d62:INBOX/MessagingController/conn205941146
01-11 16:24:09.771  9145  9177 E RealImapFolder: java.io.IOException: readStringUntil(): end of stream reached. Read: "" while waiting for ' '
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStringUntil(ImapResponseParser.java:447)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.parseTaggedResponse(ImapResponseParser.java:285)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readTaggedResponse(ImapResponseParser.java:74)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:43)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.mail.store.imap.RealImapConnection.readResponse(RealImapConnection.kt:809)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.mail.store.imap.RealImapFolder.fetch(RealImapFolder.kt:583)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.backend.imap.ImapSync.fetchUnsyncedMessages(ImapSync.kt:452)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.backend.imap.ImapSync.downloadMessages(ImapSync.kt:324)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:198)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:55)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:616)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:556)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.controller.MessagingController.lambda$synchronizeMailbox$3(MessagingController.java:528)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.controller.MessagingController.$r8$lambda$ar_6eNiqt1c67rfo1nCyGoIX3Sg(Unknown Source:0)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda22.run(Unknown Source:10)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:222)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:108)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
01-11 16:24:09.771  9145  9177 E RealImapFolder: 	at java.lang.Thread.run(Thread.java:1012)
01-11 16:24:09.771  9145  9177 E ImapSync: synchronizeMailbox
01-11 16:24:09.771  9145  9177 E ImapSync: com.fsck.k9.mail.MessagingException: IO Error
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.ioExceptionHandler(RealImapFolder.kt:1138)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.fetch(RealImapFolder.kt:623)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.fetchUnsyncedMessages(ImapSync.kt:452)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.downloadMessages(ImapSync.kt:324)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:198)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:55)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:616)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:556)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.controller.MessagingController.lambda$synchronizeMailbox$3(MessagingController.java:528)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.controller.MessagingController.$r8$lambda$ar_6eNiqt1c67rfo1nCyGoIX3Sg(Unknown Source:0)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda22.run(Unknown Source:10)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:222)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:108)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at java.lang.Thread.run(Thread.java:1012)
01-11 16:24:09.771  9145  9177 E ImapSync: Caused by: java.io.IOException: readStringUntil(): end of stream reached. Read: "" while waiting for ' '
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStringUntil(ImapResponseParser.java:447)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.parseTaggedResponse(ImapResponseParser.java:285)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readTaggedResponse(ImapResponseParser.java:74)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:43)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapConnection.readResponse(RealImapConnection.kt:809)
01-11 16:24:09.771  9145  9177 E ImapSync: 	at com.fsck.k9.mail.store.imap.RealImapFolder.fetch(RealImapFolder.kt:583)
01-11 16:24:09.771  9145  9177 E ImapSync: 	... 14 more
01-11 16:24:09.777  9145  9177 E ImapSync: Failed synchronizing folder rixx.de:INBOX @ Wed Jan 11 16:24:09 CET 2023
01-11 16:24:09.777  9145  9177 I MessagingController:  Command 'synchronizeMailbox' completed
01-11 16:24:09.777  9145  9177 I MessagingController: Running command 'sendPendingMessages', seq = 227 (background priority)
01-11 16:24:09.779  9145  9177 I MessagingController:  Command 'sendPendingMessages' completed
01-11 16:24:14.008  9145  9178 D OpenGLRenderer: endAllActiveAnimators on 0xb40000761cbc43d0 (FrameLayout) with handle 0xb40000752c8f4ed0
01-11 16:24:14.890  9145  9145 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
01-11 16:24:14.890  9145  9145 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
01-11 16:24:18.188  9145  9178 D OpenGLRenderer: endAllActiveAnimators on 0xb40000761cdbdfc0 (MenuPopupWindow$MenuDropDownListView) with handle 0xb40000752c9d6ef0
01-11 16:24:20.645  9145  9145 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
01-11 16:24:20.645  9145  9145 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
01-11 16:24:20.646  9145 20531 V LogcatLogFileWriter: Writing logcat output to content URI: content://com.android.providers.downloads.documents/document/19
```

**Comment by rixx** [comment]
Never mind, it turns out it was a postfix problem after all (though it would still be nice if k9 had indicated some sort of server error).

**Comment by cketti** [comment]
Right now the app assumes most errors are transient. In those cases no error is reported to the user. Improving this situation is tracked under #1058.

**Comment by LeahkimRoot** [comment]
> Never mind, it turns out it was a postfix problem after all (though it would still be nice if k9 had indicated some sort of server error).

Hi @rixx,

I reach exactly the same error, same context but I can't find any error on server side. What was your ?
