### ISSUE TITLE
Error when fetching the message list

### ISSUE THREAD

**Issue by sanjaysrikonda66** [thunderbird/thunderbird-android#6572]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.501

### Where did you get the app from?

Google Play

### Android version

No

### Device model

Pixel 7 pro

### Steps to reproduce

1. Open k9
2. Open an email.
3. Scroll down in the email.
4. Watch k9 kick me out of the emails and dump me back in the list of messages. 

### Expected behavior

I should be able to read emails and not be dumped back into the list. 

### Actual behavior

K9 dumps me out of the open email into the list 

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/10405413/k9mail-logs.txt)

**Comment by cketti** [comment]
@daffydock: This issue is not about a problem with WebView.

**Comment by sanjaysrikonda66** [comment]
Not mine. I open an email, I'm going through the email, I'm dumped back into the list of emails. I'm still seeing this behavior on my pixel 7pro (on Fi).

**Comment by cketti** [comment]
Stack trace from the log:

```text
java.lang.IllegalStateException: Couldn't read row 875, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
  at android.database.CursorWindow.nativeGetLong(Native Method)
  at android.database.CursorWindow.getLong(CursorWindow.java:539)
  at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
  at com.fsck.k9.storage.messages.CursorMessageAccessor.getId(RetrieveMessageListOperations.kt:192)
  at com.fsck.k9.mailstore.CacheAwareMessageMapper.map(CacheAwareMessageMapper.kt:10)
  at com.fsck.k9.storage.messages.RetrieveMessageListOperations.getMessages$lambda$2(RetrieveMessageListOperations.kt:54)
  at com.fsck.k9.storage.messages.RetrieveMessageListOperations.$r8$lambda$Mh03lQnrleZzBH53AV2-Paq8QZs(Unknown Source:0)
  at com.fsck.k9.storage.messages.RetrieveMessageListOperations$$ExternalSyntheticLambda0.doDbWork(Unknown Source:8)
  at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:169)
  at com.fsck.k9.storage.messages.RetrieveMessageListOperations.getMessages(RetrieveMessageListOperations.kt:20)
  at com.fsck.k9.storage.messages.K9MessageStore.getMessages(K9MessageStore.kt:111)
  at com.fsck.k9.mailstore.NotifierMessageStore.getMessages(Unknown Source:22)
  at com.fsck.k9.mailstore.ListenableMessageStore.getMessages(Unknown Source:22)
  at com.fsck.k9.mailstore.MessageListRepository.getMessages(MessageListRepository.kt:54)
  at com.fsck.k9.ui.messagelist.MessageListLoader.loadMessageListForAccount(MessageListLoader.kt:63)
  at com.fsck.k9.ui.messagelist.MessageListLoader.getMessageListInfo(MessageListLoader.kt:38)
  at com.fsck.k9.ui.messagelist.MessageListLoader.getMessageList(MessageListLoader.kt:25)
  at com.fsck.k9.ui.messagelist.MessageListLiveData$loadMessageListAsync$1$messageList$1.invokeSuspend(MessageListLiveData.kt:28)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by fereshtehamiri** [comment]
hello sanjaysrikonda66
I have been trying to reproduce the issue you described in my device Samsung A32, Android 13 , But this bug didn't happen for me.
 could you provide me with more information on the scenario you experienced in order to help us resolve the issue.

**Comment by mhf1998** [comment]
Hi.
I tried to repeat this scenario in the latest version (6.804).
The bug does not occur
Because in this version, on the message screen, with swipe, the operation of fetching and refreshing the list does not occur at all.

However, I think this issue can be closed. @cketti
