### ISSUE TITLE
Runtime exception when loading an email in the background.

### ISSUE THREAD

**Issue by taylorkline** [thunderbird/thunderbird-android#690]
Steps to reproduce:
Open an email that contains more data than the threshold to load.
Click "Download complete message" and immediately back out of the message.
When the message finishes downloading, the following exception occurs:

```
com.fsck.k9.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.fsck.k9.debug, PID: 22305
    java.lang.IllegalStateException: Fragment MessageViewFragment{41c41ab0} not attached to Activity
            at android.app.Fragment.getLoaderManager(Fragment.java:1019)
            at com.fsck.k9.ui.messageview.MessageViewFragment.onMessageDownloadFinished(MessageViewFragment.java:247)
            at com.fsck.k9.ui.messageview.MessageViewFragment.access$1400(MessageViewFragment.java:56)
            at com.fsck.k9.ui.messageview.MessageViewFragment$DownloadMessageListener$1.run(MessageViewFragment.java:808)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by jkdf2** [comment]
Loaders should not be used for background tasks, see [this Reddit thread](https://www.reddit.com/r/androiddev/comments/10jwcr/how_to_use_loaders_in_android/) that suggests using an IntentService for background tasks.

**Comment by cketti** [comment]
The problem isn't the loaders but the fact that `MessagingController` retains a reference to the fragment via the `DownloadMessageListener` instance passed to `MessagingController.loadMessageForViewRemote()`.
We should manually register a listener and remove it when the fragment is destroyed.
