### ISSUE TITLE
Import of settings including 1 account fails

### ISSUE THREAD

**Issue by dboehmer** [thunderbird/thunderbird-android#7138]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

F-Droid

### Android version

Android 13 from GrapheneOS

### Device model

Google Pixel 6a

### Steps to reproduce

1. copy settings file
2. open app
3. click "import settings"
4. select file
5. keep the account checked to be imported
6. click "import"

### Expected behavior

Global settings and the 1 account are imported.

### Actual behavior

Error message *Failed to import some settings*.

Import of global settings excluding the account works. #6689 seems to indicate that account details are "invalid" but I don’t see what might be invalid. I tried to
* remove the German umlaut *ö* from my name in sender identities or
* remove all signature texts from all sender identifies

before export but that did not change the result.

### Logs

I needed to create a bogus account in order to access the global settings.

I redacted my private email address in the log for privacy.

```
...
08-20 23:36:27.190 28928 28959 V SettingsImporter: Setting 9124a66f-a9e9-4583-91ac-2715ddf480c0.signatureBeforeQuotedText=false
08-20 23:36:27.190 28928 28959 V SettingsImporter: Setting 9124a66f-a9e9-4583-91ac-2715ddf480c0.accountNumber=1
08-20 23:36:27.190 28928 28959 E SettingsImporter: Encountered invalid setting while importing account "MY_EMAIL@DOMAIN.TLD"
08-20 23:36:27.190 28928 28959 E SettingsImporter: com.fsck.k9.preferences.Settings$InvalidSettingValueException
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at com.fsck.k9.preferences.SettingsImporter.importAccount(SettingsImporter.java:458)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at com.fsck.k9.preferences.SettingsImporter.importSettings(SettingsImporter.java:221)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at com.fsck.k9.ui.settings.import.SettingsImportViewModel.importSettings(SettingsImportViewModel.kt:386)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at com.fsck.k9.ui.settings.import.SettingsImportViewModel.access$importSettings(SettingsImportViewModel.kt:28)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at com.fsck.k9.ui.settings.import.SettingsImportViewModel$startImportSettings$1$1$1.invokeSuspend(SettingsImportViewModel.kt:303)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
08-20 23:36:27.190 28928 28959 E SettingsImporter:      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
08-20 23:36:27.191 28928 28959 I K9StorageEditor: Committing preference changes
08-20 23:36:27.197 28928 28959 I K9StorageEditor: Preferences commit took 6 ms
```

**Comment by wmontwe** [comment]
Right now the debug information is not enough to pinpoint the issue. I'll have a look into it.

**Comment by wmontwe** [comment]
Extended logging will be available with the next beta.

**Comment by wmontwe** [comment]
Extended logging is available with our current beta version: [6.711](https://github.com/thundernest/k-9/releases/tag/6.711)
