### ISSUE TITLE
AuthenticationFailedException occurred when I sent the email

### ISSUE THREAD

**Issue by ssssy1000** [thunderbird/thunderbird-android#7154]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.708

### Where did you get the app from?

F-Droid

### Android version

Android 6.0 x86

### Device model

Pixel 5 API 24

### Steps to reproduce

1. Input the email and wrong password
2. Always clicking “continue”
3. Enter the wrong account
4. create a mail and send it (_AuthenticationFailedException_)
5. delete the mail (_NullPointerException_)

### Expected behavior

When the email cannot be sent successfully, remind the user “the account may be wrong”.
Or check that the account is correct when creating an account.

### Actual behavior

When the account is wrong, I can enter the app but cannot send emails. NullpointerException occurs when you delete this email

### Logs

**When I sent the email:**
`2023-09-04 09:24:35.066  3334-3366  MessagingController     com.fsck.k9.debug                    E  Failed to send message
                                                                                                    com.fsck.k9.mail.AuthenticationFailedException: AUTH PLAIN failed
                                                                                                    	at com.fsck.k9.mail.transport.smtp.SmtpTransport.handlePossibleAuthenticationFailure(SmtpTransport.kt:664)
                                                                                                    	at com.fsck.k9.mail.transport.smtp.SmtpTransport.saslAuthPlain(SmtpTransport.kt:568)
                                                                                                    	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open$smtp(SmtpTransport.kt:160)
                                                                                                    	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.kt:380)
                                                                                                    	at com.fsck.k9.backend.imap.ImapBackend.sendMessage(ImapBackend.kt:152)
                                                                                                    	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:1531)
                                                                                                    	at com.fsck.k9.controller.MessagingController$5.run(MessagingController.java:1416)
                                                                                                    	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:216)
                                                                                                    	at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(MessagingController.java)
                                                                                                    	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:157)
                                                                                                    	at java.lang.Thread.run(Thread.java:818)
                                                                                                    Caused by: com.fsck.k9.mail.transport.smtp.NegativeSmtpReplyException: Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
                                                                                                    	at com.fsck.k9.mail.transport.smtp.SmtpTransport.buildNegativeSmtpReplyException(SmtpTransport.kt:522)
                                                                                                    	at com.fsck.k9.mail.transport.smtp.SmtpTransport.executeCommand(SmtpTransport.kt:515)
                                                                                                    	at com.fsck.k9.mail.transport.smtp.SmtpTransport.executeSensitiveCommand(SmtpTransport.kt:500)
                                                                                                    	at com.fsck.k9.mail.transport.smtp.SmtpTransport.saslAuthPlain(SmtpTransport.kt:566)
                                                                                                    	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open$smtp(SmtpTransport.kt:160) 
                                                                                                    	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.kt:380) 
                                                                                                    	at com.fsck.k9.backend.imap.ImapBackend.sendMessage(ImapBackend.kt:152) 
                                                                                                    	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:1531) 
                                                                                                    	at com.fsck.k9.controller.MessagingController$5.run(MessagingController.java:1416) 
                                                                                                    	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:216) 
                                                                                                    	at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(MessagingController.java) 
                                                                                                    	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:157) 
                                                                                                    	at java.lang.Thread.run(Thread.java:818) `

**When I delete the email:**
`2023-09-04 09:27:04.079  3334-3366  MessagingController     com.fsck.k9.debug                    E  Error running command 'deleteMessages'
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Collection java.util.Map.values()' on a null object reference
                                                                                                    	at com.fsck.k9.controller.MessagingController.deleteMessagesSynchronous(MessagingController.java:2032)
                                                                                                    	at com.fsck.k9.controller.MessagingController.lambda$deleteMessages$25$com-fsck-k9-controller-MessagingController(MessagingController.java:1943)
                                                                                                    	at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda17.run(D8$$SyntheticClass)
                                                                                                    	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:216)
                                                                                                    	at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(MessagingController.java)
                                                                                                    	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:157)
                                                                                                    	at java.lang.Thread.run(Thread.java:818)`****

**Comment by cketti** [comment]
This should no longer be an issue with K-9 Mail 6.710.
