### ISSUE TITLE
K-9 as Stopped when opening messages grouped

### ISSUE THREAD

**Issue by marcosandrade22** [thunderbird/thunderbird-android#730]
Sorry for my bad English, I am Brazilian es'm using google translator.

We compile the k9 master and everything is ok but when I open grouped messages, the application stopped.
follows the error log:

08-03 09:49:07.930      688-688/com.fsck.k9.emailars.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.fsck.k9.ui.messageview.MessageTopView.setMessage(MessageTopView.java:86)
            at com.fsck.k9.ui.messageview.MessageViewFragment.showMessage(MessageViewFragment.java:282)
            at com.fsck.k9.ui.messageview.MessageViewFragment.onDecodeMessageFinished(MessageViewFragment.java:277)
            at com.fsck.k9.ui.messageview.MessageViewFragment.access$1200(MessageViewFragment.java:56)
            at com.fsck.k9.ui.messageview.MessageViewFragment$DecodeMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:756)
            at com.fsck.k9.ui.messageview.MessageViewFragment$DecodeMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:746)
            at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:438)
            at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:406)
            at android.content.Loader.deliverResult(Loader.java:125)
            at com.fsck.k9.ui.message.DecodeMessageLoader.deliverResult(DecodeMessageLoader.java:40)
            at com.fsck.k9.ui.message.DecodeMessageLoader.deliverResult(DecodeMessageLoader.java:15)
            at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:236)
            at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:76)
            at android.os.AsyncTask.finish(AsyncTask.java:602)
            at android.os.AsyncTask.access$600(AsyncTask.java:156)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4424)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by cketti** [comment]
If you report bugs against master please include the hash of the version you checked out.

**Comment by marcosandrade22** [comment]
Sorry about the delay in responding, I am using the master version, 5106

**Comment by philipwhiuk** [comment]
That's not a commit hash, it's an unstable version number (well 5.106 is)

Looking at the code on master on the date this issue was made, I see no line that could have NPE'd. The nearest line that could have been null is the account. But for that to be null, we'd have had to have a bad account uuid in the message reference passed in to the MessageViewFragment. Which seems unlikely.

Closing as invalid - feel free to re-open with an actual commit hash and/or corrected line numbers for the stack trace if you can still reproduce it.
