### ISSUE TITLE
Sending almost always fails (tho *re*send succeeds)

### ISSUE THREAD

**Issue by monnier** [thunderbird/thunderbird-android#7409]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

F-Droid

### Android version

LineageOS 18.1

### Device model

SM-G900W8

### Steps to reproduce

- Use `share` from Firefox or from the photo gallery application (or presumably from any other application).
- Write the destination email address
- Press the ">" arrow to send the email

The sending operation seems to proceed as normal, but after a little while a triangle with "!" appears in the status bar that says:

```
Failed to send some messages
SocketTimeoutException: failed to connect to
disroot.org/178.21.23.139 (port 465) from /
192.168.1.77 (port 50309) after 30000ms
````

### Expected behavior

I expected K9Mail to actually send the mail and if it fails at the first try, it should probably try again once soon after).

### Actual behavior

The mail is not sent.  Instead it's kept in the Outgoing queue (where I can go and request to resend it, which usually succeeds).

### Logs

```
--------- beginning of main
12-03 23:35:13.120 18069 18079 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-03 23:36:50.132 18069 18079 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-03 23:37:00.671 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:37:06.798 18069 18094 I MessagingController: Running command 'clearNotifications', seq = 8 (foreground priority)
12-03 23:37:06.932 18069 18094 V NotificationController: Removing some notifications for account 07cd565f-9921-4ffb-9011-80f28b9223af
12-03 23:37:06.959 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:37:06.978 18069 18094 I MessagingController:  Command 'clearNotifications' completed
12-03 23:38:18.315 18069 18079 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-03 23:39:35.066 18069 18079 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-03 23:39:36.567 18069 18094 I MessagingController: Running command 'clearNotifications', seq = 9 (foreground priority)
12-03 23:39:36.609 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:39:36.897 18069 18094 V NotificationController: Removing some notifications for account 07cd565f-9921-4ffb-9011-80f28b9223af
12-03 23:39:36.897 18069 18094 I MessagingController:  Command 'clearNotifications' completed
12-03 23:39:55.146 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:40:03.441 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:40:07.478 18069 18081 I com.fsck.k9: Background young concurrent copying GC freed 20031(1074KB) AllocSpace objects, 0(0B) LOS objects, 41% free, 6773KB/11MB, paused 317us total 221.385ms
12-03 23:40:20.338 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:40:20.484 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:40:34.302 18069 18639 V LogcatLogFileWriter: Writing logcat output to content URI: content://com.android.providers.downloads.documents/document/13
12-03 23:40:34.388 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:42:58.835 18069 18079 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-03 23:43:01.768 18069 18079 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-03 23:43:01.796 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:43:36.726 18069 18069 I WebViewFactory: Loading com.android.webview version 118.0.5993.111 (code 599311100)
12-03 23:43:36.758 18069 18069 I com.fsck.k9: The ClassLoaderContext is a special shared library.
12-03 23:43:36.991 18069 18069 I cr_WVCFactoryProvider: Loaded version=118.0.5993.111 minSdkVersion=1 isBundle=false multiprocess=true packageId=2
12-03 23:43:37.286 18069 18069 I cr_LibraryLoader: Successfully loaded native library
12-03 23:43:37.297 18069 18069 I cr_CachingUmaRecorder: Flushed 6 samples from 6 histograms, 0 samples were dropped.
12-03 23:43:37.403 18069 18069 I cr_CombinedPProvider: #registerProvider() provider:WV.I6@2a1b7a0 isPolicyCacheEnabled:false policyProvidersSize:0
12-03 23:43:37.408 18069 18069 I cr_PolicyProvider: #setManagerAndSource() 0
12-03 23:43:37.807 18069 18069 I cr_CombinedPProvider: #linkNativeInternal() 1
12-03 23:43:37.889 18069 18069 I cr_AppResProvider: #getApplicationRestrictionsFromUserManager() Bundle[EMPTY_PARCEL]
12-03 23:43:37.889 18069 18069 I cr_PolicyProvider: #notifySettingsAvailable() 0
12-03 23:43:37.890 18069 18069 I cr_CombinedPProvider: #onSettingsAvailable() 0
12-03 23:43:37.890 18069 18069 I cr_CombinedPProvider: #flushPolicies()
12-03 23:43:38.819 18069 18069 D TokenAutoComplete: Current completion text: monnier@iro.umontreal.ca,
12-03 23:43:38.932 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:43:39.484 18069 20476 V AttachmentInfoLoader: old attachment.size: 519534
12-03 23:43:39.496 18069 20476 V AttachmentInfoLoader: new attachment.size: 519534
12-03 23:43:39.627 18069 18081 I com.fsck.k9: Background young concurrent copying GC freed 13023(940KB) AllocSpace objects, 11(220KB) LOS objects, 42% free, 6887KB/11MB, paused 3.994ms total 730.505ms
12-03 23:43:40.087 18069 18069 I Choreographer: Skipped 74 frames!  The application may be doing too much work on its main thread.
12-03 23:43:40.498 18069 20511 V AttachmentContentLoader: Saving attachment to /data/user/0/com.fsck.k9/cache/attachment7302911249020207561.tmp
12-03 23:43:40.606 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:43:42.693 18069 18069 D TokenAutoComplete: Current completion text: mo
12-03 23:43:43.217 18069 18069 D TokenAutoComplete: Current completion text: mon
12-03 23:43:43.393 18069 18069 D TokenAutoComplete: Current completion text: monn
12-03 23:43:43.807 18069 18069 D TokenAutoComplete: Current completion text: monni
12-03 23:43:44.431 18069 18069 D TokenAutoComplete: Current completion text: monnie
12-03 23:43:44.774 18069 18069 D TokenAutoComplete: Current completion text: monnier
12-03 23:43:46.998 18069 18069 D TokenAutoComplete: Current completion text: monnier@
12-03 23:43:48.085 18069 18069 D TokenAutoComplete: Current completion text: monnier@g
12-03 23:43:48.787 18069 18069 D TokenAutoComplete: Current completion text: monnier@gn
12-03 23:43:49.366 18069 18069 D TokenAutoComplete: Current completion text: monnier@gnu
12-03 23:43:50.926 18069 18069 D TokenAutoComplete: Current completion text: monnier@gnu.
12-03 23:43:51.480 18069 18069 D TokenAutoComplete: Current completion text: monnier@gnu.o
12-03 23:43:52.039 18069 18069 D TokenAutoComplete: Current completion text: monnier@gnu.ot
12-03 23:43:52.824 18069 18069 D TokenAutoComplete: Current completion text: monnier@gnu.o
12-03 23:43:53.407 18069 18069 D TokenAutoComplete: Current completion text: monnier@gnu.or
12-03 23:43:53.793 18069 18069 D TokenAutoComplete: Current completion text: monnier@gnu.org
12-03 23:43:55.497 18069 18069 D TokenAutoComplete: Current completion text: monnier@gnu.org
12-03 23:43:55.521 18069 18069 D TokenAutoComplete: Current completion text: monnier@gnu.org,
12-03 23:43:55.561 18069 18069 W IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
12-03 23:44:01.023 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:44:01.093 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:44:07.256 18069 18069 D TokenAutoComplete: Current completion text: 
12-03 23:44:07.257 18069 18069 I chatty  : uid=10175(com.fsck.k9) identical 6 lines
12-03 23:44:07.257 18069 18069 D TokenAutoComplete: Current completion text: 
12-03 23:44:08.773 18069 20577 V LockableDatabase: LockableDatabase: Transaction ended, took 36 ms / com.fsck.k9.storage.messages.SaveMessageOperations.saveMessage(SaveMessageOperations.kt:81)
12-03 23:44:08.800 18069 18094 I MessagingController: Running command 'sendPendingMessages', seq = 10 (background priority)
12-03 23:44:08.841 18069 18094 D LocalMessage: No headers available for this message!
12-03 23:44:08.868 18069 18094 I MessagingController: Scanning Outbox folder for messages to send
12-03 23:44:08.871 18069 18094 I MessagingController: Send count for message K9LOCAL:02c69b43-af94-4a0d-8efa-87630275aa85 is 0
12-03 23:44:08.927 18069 18094 V LockableDatabase: LockableDatabase: Transaction ended, took 23 ms / com.fsck.k9.mailstore.LocalMessage.setFlag(LocalMessage.java:256)
12-03 23:44:08.928 18069 18094 I MessagingController: Sending message with UID K9LOCAL:02c69b43-af94-4a0d-8efa-87630275aa85
12-03 23:44:08.977 18069 18094 D SmtpTransport: Connecting to disroot.org as disroot.org/178.21.23.139
12-03 23:44:39.102 18069 18094 W SmtpTransport: Could not connect to disroot.org/178.21.23.139
12-03 23:44:39.102 18069 18094 W SmtpTransport: java.net.SocketTimeoutException: failed to connect to disroot.org/178.21.23.139 (port 465) from /192.168.1.77 (port 50309) after 30000ms
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at libcore.io.IoBridge.connect(IoBridge.java:134)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at java.net.Socket.connect(Socket.java:621)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:156)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.connectToAddress(SmtpTransport.kt:276)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.connect(SmtpTransport.kt:254)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open$smtp(SmtpTransport.kt:91)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.kt:376)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.fsck.k9.backend.imap.ImapBackend.sendMessage(ImapBackend.kt:152)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:1531)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.fsck.k9.controller.MessagingController$5.run(MessagingController.java:1416)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:216)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(MessagingController.java:0)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:157)
12-03 23:44:39.102 18069 18094 W SmtpTransport: 	at java.lang.Thread.run(Thread.java:923)
12-03 23:44:39.109 18069 18094 D SmtpTransport: SMTP >>> QUIT
12-03 23:44:39.118 18069 18094 E MessagingController: Failed to send message
12-03 23:44:39.118 18069 18094 E MessagingController: com.fsck.k9.mail.MessagingException: Unable to open connection to SMTP server.
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open$smtp(SmtpTransport.kt:244)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.kt:376)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.backend.imap.ImapBackend.sendMessage(ImapBackend.kt:152)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:1531)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.controller.MessagingController$5.run(MessagingController.java:1416)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:216)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(MessagingController.java:0)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:157)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at java.lang.Thread.run(Thread.java:923)
12-03 23:44:39.118 18069 18094 E MessagingController: Caused by: java.net.SocketTimeoutException: failed to connect to disroot.org/178.21.23.139 (port 465) from /192.168.1.77 (port 50309) after 30000ms
12-03 23:44:39.118 18069 18094 E MessagingController: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at libcore.io.IoBridge.connect(IoBridge.java:134)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at java.net.Socket.connect(Socket.java:621)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:156)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.connectToAddress(SmtpTransport.kt:276)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.connect(SmtpTransport.kt:254)
12-03 23:44:39.118 18069 18094 E MessagingController: 	at com.fsck.k9.mail.transport.smtp.SmtpTransport.open$smtp(SmtpTransport.kt:91)
12-03 23:44:39.118 18069 18094 E MessagingController: 	... 8 more
12-03 23:44:39.147 18069 18094 V LockableDatabase: LockableDatabase: Transaction ended, took 24 ms / com.fsck.k9.mailstore.LocalMessage.setFlag(LocalMessage.java:256)
12-03 23:44:39.172 18069 18094 V LockableDatabase: LockableDatabase: Transaction ended, took 10 ms / com.fsck.k9.mailstore.LocalFolder.destroyMessage(LocalFolder.java:989)
12-03 23:44:39.197 18069 18094 I MessagingController:  Command 'sendPendingMessages' completed
12-03 23:46:58.091 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:47:02.723 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:47:02.772 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-03 23:47:04.004 18069 18095 D OpenGLRenderer: endAllActiveAnimators on 0x8f229380 (MenuPopupWindow$MenuDropDownListView) with handle 0xa7d2eba0
12-03 23:47:06.297 18069 18639 V LogcatLogFileWriter: Writing logcat output to content URI: content://com.android.providers.downloads.documents/document/14
12-03 23:47:06.315 18069 18095 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
```

**Comment by cketti** [comment]
The log shows that a connection to the outgoing mail server couldn't be established. That's a problem with your network, not K-9 Mail. The connection timeout is 30 seconds. Typically that's long enough even for slow networks. It's more likely that some network packets are dropped/filtered somewhere between K-9 Mail and the server. That could be Android itself (did you disable background data?), a firewall app on the device, or any network appliance between you and the destination.

**Comment by monnier** [comment]
> The log shows that a connection to the outgoing mail server couldn't be
> established. That's a problem with your network, not K-9 Mail. The
> connection timeout is 30 seconds. Typically that's long enough even for slow
> networks. It's more likely that some network packets are dropped/filtered
> somewhere between K-9 Mail and the server. That could be Android itself (did
> you disable background data?), a firewall app on the device, or any network
> appliance between you and the destination.

I don't have cell service on this device, so I'm very aware that this problem
occurs if I send the email while I'm not connected to a wifi network.

But I file the bug because this happens even when I *am* connected.
And this occurs from various different places, so it does not seem to be
linked to the particular way I'm connected (tho I guess it's possible
that it's linked to the SMTP server I'm using (disroot.org), since this
one doesn't change).
And I can reproduce the problem reliably.
And the message does get sent successfully when I go to the outgoing
folder and ask to resend it.

I have the "TC" firewall/application installed which could get in the way,
but why/how would it get in the way during the initial send and not
during the resend?

Assuming it's not a bug in K9, I guess what I'm asking here is for an
option to tell K9 to retry immediately after an initial failure to send.

**Comment by cketti** [comment]
We're planning to improve the way the app retries sending a message. However, we won't add an option to immediately retry sending a message after a send failure. There will always be a delay after failed attempts.
