### ISSUE TITLE
Absturz beim Antworten

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#7634]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.715

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Nokia 6

### Steps to reproduce

Auf Antworten klicken. 

### Expected behavior

Ich habe ein Update erwartet! K9 Mail liefert keine Lösung. Ich kann nicht programmieren Deshalb muss ich hier jetzt weinen 😭 und kann keine Mails mehr beantworten 😞 Bitte lösen sie das Problem schnell!

### Actual behavior

Absturz k9 Mail wird von Android beendet.

**Comment by cketti** [comment]
Please use English in this issue tracker. Use a translation tool if you have to.

This is most caused by a bug in OpenKeychain 6.0.0. See #7622

If it's not that, please provide a debug log. See https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors

**Comment by call-me-matt** [comment]
Translation: app crashes when pushing reply. 
I had the same issue, the app crashes when pushing the reply icon. Also without typing recipients.
Referenced solution (deactivate openpgp) worked fine for me

**Comment by phmarek** [comment]
I got the crash as well.

```
02-14 08:11:07.199  9491  9491 D TokenAutoComplete: Current completion text: abc
02-14 08:11:07.226 12049 12062 E DatabaseUtils: Writing exception to parcel
02-14 08:11:07.226 12049 12062 E DatabaseUtils: java.lang.NullPointerException: ResultSet returned null for UserPackets.sq:selectUserIdStatusByEmailLike
02-14 08:11:07.226 12049 12062 E DatabaseUtils:     at com.squareup.sqldelight.Query.executeAsOne(SourceFile:16)
02-14 08:11:07.226 12049 12062 E DatabaseUtils:     at org.sufficientlysecure.keychain.daos.UserIdDao.getUidStatusByEmailLike(SourceFile:13)
02-14 08:11:07.226 12049 12062 E DatabaseUtils:     at org.sufficientlysecure.keychain.remote.KeychainExternalProvider.loadUidStatusMap(SourceFile:14)
02-14 08:11:07.226 12049 12062 E DatabaseUtils:     at org.sufficientlysecure.keychain.remote.KeychainExternalProvider.query(SourceFile:246)
02-14 08:11:07.226 12049 12062 E DatabaseUtils:     at android.content.ContentProvider.query(ContentProvider.java:1455)
02-14 08:11:07.226 12049 12062 E DatabaseUtils:     at android.content.ContentProvider.query(ContentProvider.java:1551)
02-14 08:11:07.226 12049 12062 E DatabaseUtils:     at android.content.ContentProvider$Transport.query(ContentProvider.java:285)
02-14 08:11:07.226 12049 12062 E DatabaseUtils:     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
02-14 08:11:07.226 12049 12062 E DatabaseUtils:     at android.os.Binder.execTransactInternal(Binder.java:1280)
02-14 08:11:07.226 12049 12062 E DatabaseUtils:     at android.os.Binder.execTransact(Binder.java:1244)
02-14 08:11:07.228  9491  9741 E AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #2
02-14 08:11:07.228  9491  9741 E AndroidRuntime: Process: com.fsck.k9, PID: 9491
02-14 08:11:07.228  9491  9741 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at java.util.concurrent.FutureTask.run(FutureTask.java:269)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at java.lang.Thread.run(Thread.java:1012)
02-14 08:11:07.228  9491  9741 E AndroidRuntime: Caused by: java.lang.NullPointerException: ResultSet returned null for UserPackets.sq:selectUserIdStatusByEmailLike
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at android.os.Parcel.createException(Parcel.java:2995)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:2978)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at android.content.ContentResolver.query(ContentResolver.java:1219)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at android.content.ContentResolver.query(ContentResolver.java:1151)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at android.content.ContentResolver.query(ContentResolver.java:1107)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at com.fsck.k9.activity.compose.RecipientLoader.fillContactDataFromCryptoProvider(RecipientLoader.java:230)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:200)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:37)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
02-14 08:11:07.228  9491  9741 E AndroidRuntime:    ... 3 more
02-14 08:11:07.236  1313 12075 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-14 08:11:07.238  1313  3035 W ActivityTaskManager:   Force finishing activity com.fsck.k9/.activity.MessageCompose
```

**Comment by WireFighter** [comment]
Hello all friends
I've disabled OpenKeychain in K9 😭
I hope that Thunderbird will soon integrate a function for PGP/Mime encryption. Constantly having to use other apps for certain functions is stupid. 

The latest update of OpenKeychain is junk. 🤭 So I'm going to close here 😎
