### ISSUE TITLE
`TransactionTooLargeException` when replying to message with large body

### ISSUE THREAD

**Issue by Sami32** [thunderbird/thunderbird-android#7702]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.800

### Where did you get the app from?

Other

### Android version

7.0 MIUI 11

### Device model

Xiaomi Redmi Note 4

### Steps to reproduce

1. Answer an encrypted email
2. Select to attach a document
3. Crash happen

### Expected behavior

No crashes like before.

### Actual behavior

Crashes when answering an encrypted email.

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14529688/k9mail-logs.txt)

**Comment by Sami32** [comment]
An other crash condition is when we try to unhide uour password, K-9 Mail crash just after fingerprinting:

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14529883/k9mail-logs.txt)

**Comment by cketti** [comment]
Stack trace from the log:

```text
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 898364 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3873)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: android.os.TransactionTooLargeException: data parcel size 898364 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:622)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3688)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3865)
	... 7 more
```

This is unlikely to be a new bug. It's probably caused by a text field with too much data for the saved instance state mechanism. Fixing this requires changing how we save state in the compose screen.
