### ISSUE TITLE
Crash when unmasking a password field (v. 6.800 from GitHub)

### ISSUE THREAD

**Issue by Sami32** [thunderbird/thunderbird-android#7705]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

GitHub

### Where did you get the app from?

Other

### Android version

7.0 MIUI 11

### Device model

Xiaomi Redmi Note 4

### Steps to reproduce

Settings --> Account settings --> Fetching mail --> Incoming server --> Password unhide

### Expected behavior

No crashes like before

### Actual behavior

Crash when unmasking a password field.

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14535855/k9mail-logs.txt)

**Comment by cketti** [comment]
Stack trace from the log:

```text
java.lang.IllegalStateException: Already in the pool!
	at android.util.Pools$SimplePool.release(Pools.java:112)
	at android.util.Pools$SynchronizedPool.release(Pools.java:161)
	at android.view.accessibility.AccessibilityEvent.recycle(AccessibilityEvent.java:1045)
	at android.view.accessibility.AccessibilityManager.sendAccessibilityEvent(AccessibilityManager.java:421)
	at android.view.ViewRootImpl.requestSendAccessibilityEvent(ViewRootImpl.java:6779)
	at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:891)
	at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:891)
	at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:891)
	at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:891)
	at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:891)
	at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:891)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$onSendAccessibilityEvent$1.invoke(AndroidComposeViewAccessibilityDelegateCompat.android.kt:224)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$onSendAccessibilityEvent$1.invoke(AndroidComposeViewAccessibilityDelegateCompat.android.kt:223)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.sendEvent(AndroidComposeViewAccessibilityDelegateCompat.android.kt:1561)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.sendSemanticsPropertyChangeEvents(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2638)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.checkForSemanticsChanges(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2370)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.semanticsChangeChecker$lambda$46(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2189)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.$r8$lambda$WeiSrUW61031BxwrbdpKiNWr8NE(AndroidComposeViewAccessibilityDelegateCompat.android.kt:0)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

This seems to be a bug in Android 7 and/or a Jetpack Compose component. See https://issuetracker.google.com/issues/297732416

**Comment by cketti** [comment]
I was able to track down the crash to a bug in Jetpack Compose's `AndroidComposeViewAccessibilityDelegateCompat`. See https://issuetracker.google.com/issues/348232635#comment6
