### ISSUE TITLE
Intent to Search K9 Broken

### ISSUE THREAD

**Issue by stardomains3** [thunderbird/thunderbird-android#7724]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.800

### Where did you get the app from?

F-Droid

### Android version

14

### Device model

Pixel 8 Pro

### Steps to reproduce

1. Have app that uses an intent to open K9 to search all messages

This code used to work:

                                       ```
                                        thelastterm = foo
                                        val mapIntent = Intent(Intent.ACTION_SEARCH)
                                        mapIntent.setPackage("com.fsck.k9")
                                        mapIntent.putExtra("query", thelastterm)
                                        mapIntent.flags = Intent.FLAG_ACTIVITY_NEW_TASK
                                        startActivity(mapIntent)
```

### Expected behavior

K9 used to display the results

### Actual behavior

Crash

### Logs

FATAL EXCEPTION: main
Process: com.example999.searchparty, PID: 30613
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SEARCH flg=0x10000000 pkg=com.fsck.k9 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2363)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1949)
	at android.app.Activity.startActivityForResult(Activity.java:5743)
	at a.o.startActivityForResult(SourceFile:2)
	at android.app.Activity.startActivityForResult(Activity.java:5701)
	at a.o.startActivityForResult(SourceFile:1)
	at android.app.Activity.startActivity(Activity.java:6199)
	at android.app.Activity.startActivity(Activity.java:6166)
	at i0.B.onClick(Unknown Source:305)
	at android.view.View.performClick(View.java:7729)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
	at android.view.View.performClickInternal(View.java:7706)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30484)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by cketti** [comment]
We did remove support for this intent action in #7593. However, it was never meant to be a public API. So we don't consider this to be a bug.

Can you provide a use case for such an API?

**Comment by stardomains3** [comment]
> We did remove support for this intent action in #7593. However, it was never meant to be a public API. So we don't consider this to be a bug.
> 
> Can you provide a use case for such an API?

I used it for a personal app as it was handy for searching through all my years of emails.
