### ISSUE TITLE
App crashes when a swipe action is set to "none"

### ISSUE THREAD

**Issue by rei-zero246** [thunderbird/thunderbird-android#7969]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.902

### Where did you get the app from?

Other

### Android version

Grapheneos

### Steps to reproduce

Open the app.
Crashes.

### Expected behavior

Open without crashing. 

### Actual behavior

Opens, and crashes. 

### Logs

```
type: crash
osVersion: google/husky/husky:14/AP2A.240605.024/2024062000:user/release-keys
package: com.fsck.k9:39002
process: com.fsck.k9
processUptime: 335 + 432 ms
installer: com.android.packageinstaller

java.lang.IllegalStateException: action == SwipeAction.None
	at com.fsck.k9.ui.messagelist.SwipeResourceProvider.getActionColor(SwipeResourceProvider.kt:52)
	at com.fsck.k9.ui.messagelist.SwipeResourceProvider.getActionColorRoles(SwipeResourceProvider.kt:44)
	at com.fsck.k9.ui.messagelist.MessageListSwipeCallback.setupSwipeAction(MessageListSwipeCallback.kt:292)
	at com.fsck.k9.ui.messagelist.MessageListSwipeCallback.<init>(MessageListSwipeCallback.kt:60)
	at com.fsck.k9.ui.messagelist.MessageListFragment.initializeRecyclerView(MessageListFragment.kt:337)
	at com.fsck.k9.ui.messagelist.MessageListFragment.initializeMessageListLayout(MessageListFragment.kt:278)
	at com.fsck.k9.ui.messagelist.MessageListFragment.onViewCreated(MessageListFragment.kt:264)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:600)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1663)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3247)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3165)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at com.fsck.k9.activity.MessageList.onStart(MessageList.kt:499)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1706)
	at android.app.Activity.performStart(Activity.java:9056)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4029)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:327)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by cketti** [comment]
Thanks for the report.

This happens when a message list swipe action is set to "None". A new beta with a fix should be available shortly.
