### ISSUE TITLE
java.lang.OutOfMemoryError when fetching mails

### ISSUE THREAD

**Issue by b-pfl** [thunderbird/thunderbird-android#810]
Since a few days, k9mail has issues with retrieving / updating my inbox (both in background operation and when the Inbox is open).

Here is the corresponding log:

```
09-22 21:35:39.633 E/AndroidRuntime(32481): FATAL EXCEPTION: MessagingController
09-22 21:35:39.633 E/AndroidRuntime(32481): Process: com.fsck.k9, PID: 32481
09-22 21:35:39.633 E/AndroidRuntime(32481): java.lang.OutOfMemoryError: Failed to allocate a 32547414 byte allocation with 16777216 free bytes and 21MB until OOM
09-22 21:35:39.633 E/AndroidRuntime(32481):     at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:163)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at java.lang.StringBuilder.append(StringBuilder.java:288)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.mail.internet.MimeUtility.extractTextAndAttachments(MimeUtility.java:1445)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.mail.store.LocalStore$LocalFolder$15.doDbWork(LocalStore.java:2576)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.mail.store.LocalStore$LocalFolder$15.doDbWork(LocalStore.java:2507)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.mail.store.LockableDatabase.execute(LockableDatabase.java:283)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.mail.store.LocalStore$LocalFolder.appendMessages(LocalStore.java:2507)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.mail.store.LocalStore$LocalFolder.appendMessages(LocalStore.java:2437)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.controller.MessagingController.downloadLargeMessages(MessagingController.java:1773)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1372)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1141)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
09-22 21:35:39.633 E/AndroidRuntime(32481):     at java.lang.Thread.run(Thread.java:818)
```

**Comment by vis-bp** [comment]
Seems like this was caused by an e-mail that contained 23 MB of data (plain text of a former e-mail that contained a PDF file...)

**Comment by philipwhiuk** [comment]
This behaviour has changed (in master). The log above shows an OOM while downloading a large message and extracting the attachments in the background.

Now however, we only call the modern version of `MimeUtility.extractTextAndAttachments` - `LocalMessageExtractor.extractTextAndAttachments` when displaying an actual message.

When downloading a message, we call `LocalFolder.saveMessage()` which doesn't seem to do the same appending routine. 

We may still crash when either displaying a huge message or saving a whole bunch of larger ones, but I think would need to see the new use case and new stack trace to work out exactly how it was occurring now.

**Comment by philipwhiuk** [comment]
See also #1241

**Comment by cketti** [comment]
Please create a new issue if this still happening.
