### ISSUE TITLE
ClassCastException on IMAP sync

### ISSUE THREAD

**Issue by albatros69** [thunderbird/thunderbird-android#811]
On a fresh install of k9Mail on a new phone, one of my IMAP accounts stops suddenly with the below error. It worked like a charm for a few days prior to that. I've another IMAP account on the same server which still works and isn't affected.

K9-Mail version: 5.006
Device make: motorola
Device model: MotoG3
Android version: 5.1.1

java.lang.ClassCastException: com.fsck.k9.mail.store.ImapResponseParser$ImapList cannot be cast to java.lang.String
    at com.fsck.k9.mail.store.ImapResponseParser.readTokens(ImapResponseParser.java:69)
    at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:51)
    at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
    at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2775)
    at com.fsck.k9.mail.store.ImapStore$ImapConnection.saslAuthPlain(ImapStore.java:2727)
    at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2530)
    at com.fsck.k9.mail.store.ImapStore$ImapConnection.sendCommand(ImapStore.java:2872)
    at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2921)
    at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2902)
    at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:858)
    at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:904)
    at com.fsck.k9.mail.store.ImapStore$ImapFolder.open(ImapStore.java:867)
    at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1041)
    at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
    at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
    at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
    at java.lang.Thread.run(Thread.java:818)

**Comment by albatros69** [comment]
On a fresh install of k9Mail on a new phone, one of my IMAP accounts stops suddenly with the below error. It worked like a charm for a few days prior to that. I've another IMAP account on the same server which still works and isn't affected.

K9-Mail version: 5.006
Device make: motorola
Device model: MotoG3
Android version: 5.1.1

java.lang.ClassCastException: com.fsck.k9.mail.store.ImapResponseParser$ImapList cannot be cast to java.lang.String
	at com.fsck.k9.mail.store.ImapResponseParser.readTokens(ImapResponseParser.java:69)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:51)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2775)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.saslAuthPlain(ImapStore.java:2727)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2530)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.sendCommand(ImapStore.java:2872)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2921)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2902)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:858)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:904)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.open(ImapStore.java:867)
	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1041)
	at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
	at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
	at java.lang.Thread.run(Thread.java:818)

**Comment by cketti** [comment]
My guess is the server sends an unexpected (and maybe invalid) response to the `AUTHENTICATE PLAIN` command.
Still, we should be able to avoid the `ClassCastException`.

**Comment by albatros69** [comment]
Strange is that I deleted and recreated the account and it's working fine now.

**Comment by fkbreitl** [comment]
Hi, I see the same error of `classcastexception: com.fsc` on my Inbox folder after a mail server was changed.
Other folders look fine but I cannot receive new mail now.
I am using K-9 Mail 5.203
