### ISSUE TITLE
[bug] Delete doesn't update to imap server / IOException readStringUnti

### ISSUE THREAD

**Issue by david-a-wheeler** [thunderbird/thunderbird-android#815]
Deleting an email in my inbox deletes it locally but does not delete it on the imap server.  It used to work.

When I look at folders I see this message for inbox:
 IOException readStringUnti
Or
 Exception: Message count -1

This is a big deal for me.  The inbox is large, and I get lots of spam I want to delete.

**Comment by david-a-wheeler** [comment]
I turned on debugging, and looked at k9mail-errors.
There is a massage with subject Push error for INBOX.
Comtents below.

~~~~
K9-Mail version: 5.006
Device make: samsung
Device model: SCH-I545
Android version: 5.0.1

java.io.IOException: readStringUntil(): end of stream reached
	at com.fsck.k9.mail.store.ImapResponseParser.readStringUntil(ImapResponseParser.java:356)
	at com.fsck.k9.mail.store.ImapResponseParser.parseTaggedResponse(ImapResponseParser.java:198)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:50)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2775)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2925)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:862)
	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3151)
	at java.lang.Thread.run(Thread.java:818)
~~~~

**Comment by david-a-wheeler** [comment]
There are also a lot of debug messages that look like this.

They have subject
IOException readStringUntil(): end of stream reached


~~~~
K9-Mail version: 5.006
Device make: samsung
Device model: SCH-I545
Android version: 5.0.1

com.fsck.k9.mail.MessagingException: IO Error
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.ioExceptionHandler(ImapStore.java:2208)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.expunge(ImapStore.java:2117)
	at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:2342)
	at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:1997)
	at com.fsck.k9.controller.MessagingController.access$1000(MessagingController.java:111)
	at com.fsck.k9.controller.MessagingController$12.run(MessagingController.java:1935)
	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: readStringUntil(): end of stream reached
	at com.fsck.k9.mail.store.ImapResponseParser.readStringUntil(ImapResponseParser.java:356)
	at com.fsck.k9.mail.store.ImapResponseParser.parseTaggedResponse(ImapResponseParser.java:198)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:50)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2775)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2925)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2902)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:858)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.expunge(ImapStore.java:2115)
	... 6 more
~~~~

**Comment by cketti** [comment]
The stack traces indicate that K-9 Mail reaches the end of the stream while parsing the response to a sent command. It's possible that the app sends an invalid command that leads to the server closing the connection to the client.

When debug logging is enabled K-9 Mail writes the commands sent to the server to Android's (in-memory) system log. Can you please try to get us these messages.
Instructions can be found here: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by david-a-wheeler** [comment]
Yes, I'll get the system log info.  Unfortunately I won't be able to do all those debug logging extraction steps today (that is a *LOT* of setup steps!), but I'll get them done ASAP.

Is there any other data I can provide that'd be useful *without* having adb attached, beyond the k9mail-errors I've already included?

**Comment by david-a-wheeler** [comment]
I got the log, but it's big; GitHub won't let me post it here. Please look here for the log:
https://drive.google.com/file/d/0B6AaBLBsShVbODJnVm5vcEtIdFU/view?usp=sharing

Suggestions eagerly welcome.  Thanks.

**Comment by david-a-wheeler** [comment]
I've also posted the log here: http://www.dwheeler.com/misc/k9-log.txt - it's exactly the same file as on Google Drive, it's just in two places to make sure you can see the information.

If there's something else you need me to do to help debug, let me know.  Thanks.

**Comment by david-a-wheeler** [comment]
Do you need any other info?

**Comment by david-a-wheeler** [comment]
I switched to a different mail server with the same email, still fails.  Here's another K9mail internal error message..


> -------- Original Message --------
> From: K9mail internal ...
> Sent: October 18, 2015 8:36:36 PM EDT
> Subject: SocketTimeoutException: Read timed out
> 
> K9-Mail version: 5.006
> Device make: samsung
> Device model: SCH-I545
> Android version: 5.0.1
> 
> com.fsck.k9.mail.MessagingException: IO Error
> 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.ioExceptionHandler(ImapStore.java:2208)
> 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.setFlags(ImapStore.java:2192)
> 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.moveMessages(ImapStore.java:1230)
> 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.delete(ImapStore.java:1258)
> 	at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:2328)
> 	at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:1997)
> 	at com.fsck.k9.controller.MessagingController.access$1000(MessagingController.java:111)
> 	at com.fsck.k9.controller.MessagingController$12.run(MessagingController.java:1935)
> 	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
> 	at java.lang.Thread.run(Thread.java:818)
> Caused by: java.net.SocketTimeoutException: Read timed out
> 	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
> 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:728)
> 	at java.io.InputStream.read(InputStream.java:162)
> 	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
> 	at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
> 	at com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:34)
> 	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:42)
> 	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
> 	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2775)
> 	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2925)
> 	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2902)
> 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:858)
> 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.setFlags(ImapStore.java:2187)
> 	... 8 more

**Comment by david-a-wheeler** [comment]
The new update fixed this bug.  THANK YOU VERY MUCH.  I'm closing this bug out.

**Comment by udgithub** [comment]
On my S7 (Android 6) with K9 version 5.010 I can't delete mails on the server. It's very strange cause on my previous Smartphone S3 (Android 4.4.x) it worked pretty well. Any ideas?

**Comment by philipwhiuk** [comment]
Please raise a separate issue rather than commenting on this one and provide device logs.
