### ISSUE TITLE
App crashed when clicked on Sent mail item

### ISSUE THREAD

**Issue by shuvashish76** [thunderbird/thunderbird-android#8156]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

_6.904_

### Where did you get the app from?

F-Droid

### Android version

9

### Device model

Lenovo Tab4 8 plus (TB-8704X)

### Steps to reproduce

1. Open "Sent mail" folder
2. Click one of the item
3. App crashed

One time crash, can't reproduce it.

### Expected behavior

Open the sent mail.

### Actual behavior

App crashed

### Logs

```
FATAL EXCEPTION: main
Process: com.fsck.k9, PID: 16322
java.lang.NullPointerException
	at com.fsck.k9.activity.MessageList.showMessageView(MessageList.kt:1244)
	at com.fsck.k9.activity.MessageList.openMessage(MessageList.kt:986)
	at com.fsck.k9.ui.messagelist.MessageListFragment.openMessage(MessageListFragment.kt:1310)
	at com.fsck.k9.ui.messagelist.MessageListFragment.onMessageClicked(MessageListFragment.kt:530)
	at com.fsck.k9.ui.messagelist.MessageListAdapter.messageClickedListener$lambda$12(MessageListAdapter.kt:187)
	at com.fsck.k9.ui.messagelist.MessageListAdapter.$r8$lambda$Uo2pSIFtB9TYkTOVPEJJYCICEG8(MessageListAdapter.kt:0)
	at com.fsck.k9.ui.messagelist.MessageListAdapter$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25906)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by kewisch** [comment]
Can you please try again with Thunderbird 8.2 or later? We've resolved a number of crashes since.
