### ISSUE TITLE
Crash when setting up an account

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#8502]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

6.804 (probably)

### Where did you get the app from?

None

### Android version

Android 14

### Steps to reproduce

Try to set up an account while "using SuperProxy with Always-On VPN and blocking connections that wants to bypass VPN."

See https://forum.k9mail.app/t/cannot-add-new-accounts/10463

### Expected behavior

Account setup should continue with manual setup.

### Actual behavior

Crash

### Logs

```text
--------- beginning of crash
10-01 06:25:13.550  8736  8736 E AndroidRuntime: FATAL EXCEPTION: main
10-01 06:25:13.550  8736  8736 E AndroidRuntime: Process: com.fsck.k9, PID: 8736
10-01 06:25:13.550  8736  8736 E AndroidRuntime: org.minidns.dnsname.InvalidDnsNameException$LabelTooLongException: The DNS name 'pÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀ' contains the label 'pÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀÀ' which exceeds the maximum label length of 63 octets by 29 octets.
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.dnsname.DnsName.getLabels(DnsName.java:256)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.dnsname.DnsName.setLabelsIfRequired(DnsName.java:238)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.dnsname.DnsName.setBytesIfRequired(DnsName.java:213)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.dnsname.DnsName.validateMaxDnsnameLengthInOctets(DnsName.java:179)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.dnsname.DnsName.<init>(DnsName.java:143)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.dnsname.DnsName.<init>(DnsName.java:112)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.dnsname.DnsName.parse(DnsName.java:443)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.record.MX.parse(MX.java:46)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.record.Record.parse(Record.java:349)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.dnsmessage.DnsMessage.<init>(DnsMessage.java:414)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.source.NetworkDataSource.queryUdp(NetworkDataSource.java:97)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.source.NetworkDataSource.query(NetworkDataSource.java:60)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.source.NetworkDataSource.query(NetworkDataSource.java:34)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.AbstractDnsClient.query(AbstractDnsClient.java:250)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.AbstractDnsClient.query(AbstractDnsClient.java:360)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.DnsClient.query(DnsClient.java:157)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.iterative.ReliableDnsClient.query(ReliableDnsClient.java:99)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.AbstractDnsClient.query(AbstractDnsClient.java:188)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.dnssec.DnssecClient.queryDnssec(DnssecClient.java:104)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.hla.DnssecResolverApi.resolve(DnssecResolverApi.java:65)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.hla.ResolverApi.resolve(ResolverApi.java:114)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at org.minidns.hla.ResolverApi.resolve(ResolverApi.java:108)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.MiniDnsMxResolver.lookup-R1J1zPY(MiniDnsMxResolver.kt:10)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.SuspendableMxResolver$lookup$2.invoke(SuspendableMxResolver.kt:10)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.SuspendableMxResolver$lookup$2.invoke(SuspendableMxResolver.kt:9)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:52)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:44)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt:0)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt:0)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:43)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.SuspendableMxResolver.lookup-sHpvUBc(SuspendableMxResolver.kt:9)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.MxLookupAutoconfigDiscovery.mxLookup-sHpvUBc(MxLookupAutoconfigDiscovery.kt:68)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.MxLookupAutoconfigDiscovery.mxLookupAutoconfig(MxLookupAutoconfigDiscovery.kt:35)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.MxLookupAutoconfigDiscovery.access$mxLookupAutoconfig(MxLookupAutoconfigDiscovery.kt:15)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.MxLookupAutoconfigDiscovery$initDiscovery$1.run(MxLookupAutoconfigDiscovery.kt:26)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at app.k9mail.autodiscovery.service.PriorityParallelRunner$run$2$deferredList$1$deferred$1.invokeSuspend(PriorityParallelRunner.kt:35)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
10-01 06:25:13.550  8736  8736 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6cf08a2, Dispatchers.Main.immediate]
```

**Comment by cketti** [comment]
We should catch `InvalidDnsNameException` in `MxLookupAutoconfigDiscovery.mxLookup()`.
