### ISSUE TITLE
S/MIME crashes app

### ISSUE THREAD

**Issue by wfdewith** [thunderbird/thunderbird-android#916]
I'm using the master branch and opening PGP/MIME signed/encrypted mail works fine, but when I open a S/MIME signed mail, the app crashes.

```
11-28 11:26:29.522 21844 21844 D AndroidRuntime: Shutting down VM
11-28 11:26:29.530 21844 21844 E AndroidRuntime: FATAL EXCEPTION: main
11-28 11:26:29.530 21844 21844 E AndroidRuntime: Process: com.fsck.k9.debug, PID: 21844
11-28 11:26:29.530 21844 21844 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.openintents.openpgp.OpenPgpSignatureResult.getResult()' on a null object reference
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.messageview.OpenPgpHeaderView.displayVerificationResult(OpenPgpHeaderView.java:184)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.messageview.OpenPgpHeaderView.initializeSignatureHeader(OpenPgpHeaderView.java:164)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.messageview.OpenPgpHeaderView.setOpenPgpData(OpenPgpHeaderView.java:70)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.messageview.MessageContainerView.displayMessageViewContainer(MessageContainerView.java:444)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.messageview.MessageTopView.setMessage(MessageTopView.java:94)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.messageview.MessageViewFragment.showMessage(MessageViewFragment.java:277)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.messageview.MessageViewFragment.onDecodeMessageFinished(MessageViewFragment.java:272)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.messageview.MessageViewFragment.access$1200(MessageViewFragment.java:56)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.messageview.MessageViewFragment$DecodeMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:751)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.messageview.MessageViewFragment$DecodeMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:741)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:451)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.content.Loader.deliverResult(Loader.java:144)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.message.DecodeMessageLoader.deliverResult(DecodeMessageLoader.java:40)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.fsck.k9.ui.message.DecodeMessageLoader.deliverResult(DecodeMessageLoader.java:15)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:265)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.os.AsyncTask.finish(AsyncTask.java:651)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.os.AsyncTask.-wrap1(AsyncTask.java)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5417)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-28 11:26:29.530 21844 21844 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-28 11:26:29.533  2062  5906 W ActivityManager:   Force finishing activity com.fsck.k9.debug/com.fsck.k9.activity.MessageList
```

**Comment by cketti** [comment]
This should be fixed by no longer attempting to decrypt S/MIME messages and not crashing when decryption fails.

**Comment by philipwhiuk** [comment]
This has regressed in master.

We throw a runtime exception when extracting the part (which is a BinaryMemoryBody with base64 encoding), then an NPE because we have a null MessageViewInfo.

```
03-23 11:13:49.646 23361-23405/com.fsck.k9.debug E/k9: Error while decoding message
java.lang.RuntimeException: Not supported
    at com.fsck.k9.mailstore.LocalMessageExtractor.extractAttachmentInfo(LocalMessageExtractor.java:529)
    at com.fsck.k9.mailstore.LocalMessageExtractor.extractAttachmentInfos(LocalMessageExtractor.java:502)
    at com.fsck.k9.mailstore.LocalMessageExtractor.decodeMessageForView(LocalMessageExtractor.java:444)
    at com.fsck.k9.ui.message.DecodeMessageLoader.loadInBackground(DecodeMessageLoader.java:46)
    at com.fsck.k9.ui.message.DecodeMessageLoader.loadInBackground(DecodeMessageLoader.java:15)
    at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
    at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
    at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
03-23 11:13:49.671 23361-23361/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.fsck.k9.debug, PID: 23361
java.lang.NullPointerException: Attempt to read from field 'com.fsck.k9.mail.Message com.fsck.k9.mailstore.MessageViewInfo.message' on a null object reference
    at com.fsck.k9.ui.messageview.MessageTopView.setMessage(MessageTopView.java:90)
    at com.fsck.k9.ui.messageview.MessageViewFragment.showMessage(MessageViewFragment.java:281)
    at com.fsck.k9.ui.messageview.MessageViewFragment.onDecodeMessageFinished(MessageViewFragment.java:276)
    at com.fsck.k9.ui.messageview.MessageViewFragment.access$1200(MessageViewFragment.java:57)
    at com.fsck.k9.ui.messageview.MessageViewFragment$DecodeMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:755)
    at com.fsck.k9.ui.messageview.MessageViewFragment$DecodeMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:745)
    at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)
    at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:451)
    at android.content.Loader.deliverResult(Loader.java:144)
    at com.fsck.k9.ui.message.DecodeMessageLoader.deliverResult(DecodeMessageLoader.java:40)
    at com.fsck.k9.ui.message.DecodeMessageLoader.deliverResult(DecodeMessageLoader.java:15)
    at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:265)
    at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
    at android.os.AsyncTask.finish(AsyncTask.java:651)
    at android.os.AsyncTask.-wrap1(AsyncTask.java)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
